### ISSUE TITLE
Add registry filter to the podman pull command

### ISSUE THREAD

**Issue by PavelSosin-320** [containers/podman#10098]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**
Please, add --filter option to the podman pull command to eliminate dependency on terminal behavior and improve the usability

Podman pull command displays an unfiltered list of repositories that requires manual selection of the repository using Up/Down arrows. The arrows button behavior is not standard and involves terminal application configuration. This is also time-consuming: #10095  

Please, add registry-filter option in the form --registry registry-pattern or --filter registry=registry-pattern to the podman pull command that restricts the displayed proposal list applying regex pattern on the registry portion. Then accept the selection automatically in the case of one option left. 

**Describe the results you expected:**
podman pull --registry registry docker nvidia/cuda
podman pull --filter registry=docker /nvidia/cuda
should expose nvidia/cuda from the docker.io and accept it without interaction with the user.
podman pull --registry 
RedHat and podman pull --filter registry=RedHat ubuntu:18_04
should expose ubuntu images from the RedHat Access and accept the single left registry without interaction with the user.
benefits:

1. No dependency on Terminal and Up/Down arrow behavior
2. Fully non-interactive mode is possible with less configuration
3. Less podman logins are required.

**Comment by vrothberg** [comment]
As mentioned in the other issue, you can configure `/etc/containers/registries.conf` and set `unqualified-search-registries` to the one registry you want to use. Typing `pull --registry docker nvidia/cuda` is much more work than just referring directly to the image `pull docker.io/nvidia/cuda`.  

Since you asked to change the behavior many times already, please note that there are no plans to change the current mechanism.  We've been talking _extensively_ about `/etc/containers/registries.conf`.  You can also set the `short-name-mode` as described in the blog on short-name aliases: https://www.redhat.com/sysadmin/container-image-short-names

**Comment by PavelSosin-320** [comment]
@vrothberg I saw the Podman as an organic part of **RedHat development pipeline**, either scripting or declarative. Unfortunately, the user interaction using the keyboard will make the implementation of Jenkins agent too complex and the syntax of pipeline stage

 definition unclear. Changing configuration is hardly possible in the Unit test Before or BeforeAll section. I don't believe that DevOps team will accept such Unit test. Podman's Repository configuration, unlike tiny Docker's is  simply too big to make it a part of a Test suit,
![image](https://user-images.githubusercontent.com/54495912/115550478-943f8000-a2b2-11eb-97a4-5278f9445791.png)
