### ISSUE TITLE
podman generate systemd for kube

### ISSUE THREAD

**Issue by vorburger** [containers/podman#10189]
/kind feature

**Description**

It would be cool if there was something like a `podman generate kube systemd` kind of command.

The `kube systemd` is not a typo, but intentional - that (obviously) doesn't work today.

The idea would be that it would generate a suitable systemd unit using `podman play kube` (instead of `podman run`.

I imagine it would look something like my (manually cobbled together) https://github.com/vorburger/vorburger.ch-Notes/tree/develop/linux/coreos#podman-play-kube-in-systemd.

**Comment by rhatdan** [comment]
Well we could consider this more like 

podman generate kube --systemd

Which would generate the kube yaml file along with a systemd unit file.

Would you be interested in opening a PR?

**Comment by vrothberg** [comment]
At first glance, it seems a bit like mixing apples and oranges.  Why not use `podman generate kube container/pod` and then use `podman generate systemd container/pod`?

A systemd unit executing `podman play kube` is not supported since `play kube` is setting up a pod which requires one systemd unit file for the pod and for each container within the pod.

**Comment by rhatdan** [comment]
Well since no argument was made against @vrothberg suggestion, I am going to close.  Reopen if you want to continue the discussion.
