### ISSUE TITLE
PODMAN and systemd immediate halt

### ISSUE THREAD

**Issue by psaini79** [containers/podman#10462]
kind bug

**Description**

I am testing systemd based containers and one of the env I found the issue when I pass kill -RTMIN+13 but the container doesn't get restarted. However, it works perfectly fine on other containers.

Do we know at which version of systemd we have the fix immediate halt using real-time signals? The systemd version where it didn't work is systemd-libs-208-71  and where it worked the systemd version is systemd-libs-219-78.

If I look at the following snippet https://github.com/systemd/systemd/blob/main/src/core/manager.c, I can see systemd can handle the following:

```
sigset_add_many(
/* ... space for more special targets ... */
                        SIGRTMIN+13, /* systemd: Immediate halt */                        SIGRTMIN+14, /* systemd: Immediate poweroff */                        SIGRTMIN+15, /* systemd: Immediate reboot */                        SIGRTMIN+16, /* systemd: Immediate kexec */
```

I am wondering with PODMAN what is the minimum version of systemd is required to make sure that `SIGRTMIN+13, /* systemd: Immediate halt */  `  will work inside the container.

**Comment by mheon** [comment]
Can you clarify what your problem is here? I'm having trouble understanding.

Podman automatically sets container stop signal to RTMIN+3 on any container where we detect that systemd is PID 1 (or when you force systemd detection with the `--systemd=always` flag). The `podman stop` command will automatically send this signal when stopping containers with systemd PID 1. We have done this since before Podman 1.0. I don't see RTMIN+3 on your signal listing, but I'm quite certain that it's the correct one, since we've extensively tested Podman + Systemd integration.

You can definitely send RTMIN+13 with `podman kill -s rtmin+13` and if your description of systemd's behavior is correct, it should result in the container being shut down. Specifying signal number to `podman kill` has also been supported since before 1.0.

**Comment by psaini79** [comment]
@mheon 

I am killing podman containers from inside the container and these containers are systemd-based. My concern is to understand what is the minimum version of systemd is required to pass `kill -RTMIN+13` from inside the container to make sure the container will exit.

I think podman is doing its job but it is mainly systemd that performs immediate halt so I need to make sure my containers must have the correct systemd version.

**Comment by mheon** [comment]
This sounds more like a systemd question than a Podman question, then - I can't give you any help as to what versions of systemd behave in specific ways. I recommend opening an issue against Systemd for more information.

**Comment by rhatdan** [comment]
Yes please ask SYStemd this.
