### ISSUE TITLE
RFC: image exists on registry

### ISSUE THREAD

**Issue by vrothberg** [containers/podman#10780]
Based on an internal user issue:

`podman search` is not a reliable indicator whether an image exists or not since the search semantics of registries differ. `podman image exists`, however, only works on images in the local container storage.

I'd love to extend `podman image exists` by supporting all kinds of transports.  This way, a `podman image exists docker://...` would indicate if there's a matching image or not. The remote client should be limited to the containers-storage and the docker transport.

@rhatdan @mtrmac PTAL

**Comment by rhatdan** [comment]
SGTM, is there a way to do this, without triggering a pull?

**Comment by vrothberg** [comment]
> SGTM, is there a way to do this, without triggering a pull?

I would always just read the manifest which should be portable across the transports.  Maybe @mtrmac has an even less expensive idea?

**Comment by mtrmac** [comment]
(My first instinct is to ask “why is this necessary”, it’s a TOCTOU-as-a-feature and the caller almost certainly wants something a bit different. “Is the image {accessible using $credentials, accessible anonymously, exactly the same as $my_built_image }?” In the extreme, “is the image in the top 10 search results for $term?”

`podman image exists` might well be a useful way to answer a large set of such questions, or maybe the original request could actually point at some other feature. I don’t have the full context.)

---

To an extent, `skopeo inspect` works for this already. It does not immediately spring to mind, though.

---

Yes, reading the manifest is portable, but involving the transport abstraction somewhat increases the importance of the question of what should the result mean _precisely_. (Consider the case of a valid image upload, with a layer lost due to a storage failure. The manifest can be pulled, the whole image can’t. Does the image “exist”?)

Specifically for `docker://`, note `c/image/docker.GetDigest` for its interaction with the current Docker.io pull limits. OTOH it is very specific to that transport, and it might also be distinctly less useful for specific use cases because of what exactly it checks.

**Comment by vrothberg** [comment]
Thanks, @mtrmac!   I keep forgetting about the TOCTOU.  Unless there's a convincing argument (which I do not have), I think we're at a good place.

**Comment by mtrmac** [comment]
To be fair, “is the image accessible using $credentials” might be reasonable to express as a `podman --authfile … image exists …`. OTOH pointing users to Skopeo can work well enough that writing extra code is probably not worth it.
