### ISSUE TITLE
can't start container: rootless, systemd, uidmap

### ISSUE THREAD

**Issue by LucaFulchir** [containers/podman#10902]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**
Trying to run a rootless, unprivileged fedora container with systemd and uidmap in podman.  
System on a raspberry pi4, nixos aarch64, with kernel `5.10.17`, podman `3.2.2`, cgroup2 only, *no* selinux

The container fails to start because it can not create the proper structure in `/sys/fs/cgroup`

**Steps to reproduce the issue:**

I traced it tho this use case, as my user, rootless:
```
$ podman unshare cat /proc/self/uid_map
         0       1000          1
         1     100000      65536
``` 
working:
```
$ podman run --rm -it --security-opt unmask=/sys/fs/cgroup '--uidmap=0:0:65535' '--gidmap=0:0:65535' alpine mkdir /sys/fs/cgroup/eee && echo success
success
```
**not** working (notice the `uidmap` and `gidmap` change):
```
$ podman run --rm -it --security-opt unmask=/sys/fs/cgroup '--uidmap=0:1:65535' '--gidmap=0:1:65535' alpine mkdir /sys/fs/cgroup/eee && echo success
mkdir: can't create directory '/sys/fs/cgroup/eee': Permission denied
```

Which kind of make sense, podman is only making the `/sys/fs/cgroup` available, but if `root` inside of the container does not match my user it can't write there

Is this expected? Any way to get around that? I will have multiple containers and would like to avoid sharing any user between them

**Describe the results you received:**

systemd error:
```
systemd v248.3-1.fc34 running in system mode. (+PAM +AUDIT +SELINUX -APPARMOR +IMA +SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTS
ETUP +LIBFDISK +PCRE2 +PWQUALITY +P11KIT +QRENCODE +BZIP2 +LZ4 +XZ +ZLIB +ZSTD +XKBCOMMON +UTMP +SYSVINIT default-hierarchy=unified)
Detected virtualization podman.
Detected architecture arm64.
Initializing machine ID from random generator.
Failed to create /init.scope control group: Permission denied
Failed to allocate manager object: Permission denied
[!!!!!!] Failed to allocate manager object.
Exiting PID 1...
```

**Describe the results you expected:**

normal systemd start

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:      3.2.2
API Version:  3.2.2
Go Version:   go1.16.5
Built:        Tue Jan  1 00:00:00 1980
OS/Arch:      linux/arm64
```

**Output of `podman info --debug`:**

```
$ podman info --debug
host:
  arch: arm64
  buildahVersion: 1.21.0
  cgroupControllers: []
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: Unknown
    path: /nix/store/z53q7bl7bxr40d9ls6bdbb2frzipbgla-conmon-2.0.29/bin/conmon
    version: 'conmon version 2.0.29, commit: '
  cpus: 4
  distribution:
    distribution: nixos
    version: 21.11pre300226.20887e4bbfd
  eventLogger: journald
  hostname: multivac
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.10.17
  linkmode: dynamic
  memFree: 3078615040
  memTotal: 3976482816
  ociRuntime:
    name: crun
    package: Unknown
    path: /nix/store/adaj6caw3ln2q4lw05mhv83pnzggqs3r-crun-0.20.1/bin/crun
    version: |-
      crun version 0.20.1
      commit: 0.20.1
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_AUDIT_WRITE,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_MKNOD,CAP_NET_BIND_SERVICE,CAP_NET_RAW,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: ""
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /nix/store/571bjjj8ijq300lqjjcj8mzan6psvayr-slirp4netns-1.1.11/bin/slirp4netns
    package: Unknown
    version: |-
      slirp4netns version 1.1.11
      commit: 368e69ccc074628d17a9bb9a35b8f4b9f74db4c6
      libslirp: 4.6.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.1
  swapFree: 8422436864
  swapTotal: 8589926400
  uptime: 120h 19m 26.71s (Approximately 5.00 days)
registries:
  search:
  - docker.io
  - quay.io
store:
  configFile: /home/luker/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /nix/store/4zip3ngm2vj4npkq79jim5wwyx1cxw6g-fuse-overlayfs-1.6/bin/fuse-overlayfs
      Package: Unknown
      Version: |-
        fuse-overlayfs: version 1.6
        FUSE library version 3.10.4
        using FUSE kernel interface version 7.31
  graphRoot: /home/luker/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: btrfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 3
  runRoot: /tmp/podman-run-1000/containers
  volumePath: /home/luker/.local/share/containers/storage/volumes
version:
  APIVersion: 3.2.2
  Built: 315532800
  BuiltTime: Tue Jan  1 00:00:00 1980
  GitCommit: ""
  GoVersion: go1.16.5
  OsArch: linux/arm64
  Version: 3.2.2
```

**Comment by mheon** [comment]
That uid/gid map does not look usable. You're only allocating a single UID and GID for use in the container - any files and folders not owned by that single UID and GID will be unusable. What are you trying to do such that you need the extra UID/GID map?

Also - can you provide the command you're using to launch the systemd container? That should definitely work as rootless, especially on v2.

**Comment by LucaFulchir** [comment]
uhm... `--uidmap` should give the container `65535` uid/gids if I'm reading the manpage right: `--uidmap=container_uid:from_uid:amount`. Did I understand wrong how to use it?  

`container_uid` I don't really understand, it's always `0` everywhere I find. Userid for the entrypoint inside the container?  
`from_uid` is just the starting point from which to count...  
`amount` the number of uid allocated to the container  
ok, `from_uid` has different usage depending on rootless or rootful, but what I was trying to do was allocate `65535` uid/gids to the container, starting with uid/gid `100000`


I'm playing around with `freeipa:fedora-34-4.9.6`, which I had to build manually for `arm64` since they don't publish that architecture.  it's centos or fedora based (both give me the same problem) but they change the entrypoint to systemd.

The minimum `Dockerfile` I have is:
```
FROM registry.fedoraproject.org/fedora:34

RUN dnf install -y systemd
ENTRYPOINT ["/usr/sbin/init"]
```
then `$ podman build -t fedora:34-systemd Dockerfile`  (the base image is around 60-70MB)
and run with `$ podman run --rm -it --security-opt unmask=/sys/fs/cgroup '--uidmap=0:1:65535' '--gidmap=0:1:65535' fedora:34-systemd`

**Comment by mheon** [comment]
I think you're misunderstanding how the `--uidmap` and `--gidmap` flags work with rootless. Rootless containers are already running inside a user namespace, which has a number of UIDs and GIDs allocated to it (the user running Podman plus any UIDs and GIDs they have allocated in /etc/subuid and /etc/subgid). The container's UID and GID maps are subordinate to this - you aren't working with UIDs and GIDs on the host, but UIDs and GIDs in the rootless user namespace. We primarily use it to shuffle where the user launching Podman appears at in the user range (root is the default, `--userns=keep-id` moves it to the same UID/GID as on the host). It cannot be used to bring additional UIDs from the host into the container - rootless users do not have privileges to do this.

You're quite correct that you are allocating 65536 UIDs and GIDs, not 1 - sorry, I misread. However, all you're really doing is trimming UID/GID 0 in the rootless user namespace (the user that launched Podman) out of the container (by starting at 1, instead of 0, for the host UID, the second argument).

If what you are trying to do is allocate UIDs and GIDs to the rootless container - that's already done, by `/etc/subuid` and `/etc/subgid`. You can see them in the `idMappings` section of `podman info`. Podman handles this automatically as containers would be entirely unusable as rootless if we did not.

This brings us back to the systemd issue. Please add `--log-level debug` to the very end of your `podman run` command for systemd (also, remove `--security-opt unmask=` and the `--uidmap` and `--gidmap` bits - those are not necessary for systemd in a container). This will tell systemd to provide us with additional debug info, including (hopefully) exactly what is going wrong.

**Comment by LucaFulchir** [comment]
I put the `--log-level debug` `--uidmap 0:1:65536` failed run here: https://pastebin.com/QKG04nh6

If I avoid using `uidmap`, `gidmap` and `security-opt` it works fine, and the container has full access to the cgroup

I was under the impression that starting multiple containers this way would give the same mapping to all of them.  
I was trying to separate all mappings so that even in the case of bugs (unlikely) or shared resources (more likely for me, e.g: mounted filesystem) the ownership would prevent the two containers from interacting  
A quick test with two containers confirms this.

> However, all you're really doing is trimming UID/GID 0 in the rootless user namespace 

uh... I am not sure what you mean. With a quick test with the filesystem (touching a file owned by container root) tells me that:
* without `uidmap` `root` in the container has the same uid as my user (on the fs at least)
* with `--uidmap=0:1:65536` the container root equals to subuid `100000` which was what I was trying to do.

Basically without `uidmap` they might be different namespaces, but the uids match.

But with `uidmap` I can't start systemd since the permission of the dir `/sys/fs/cgroup`are those of the user that creates the container. `uidmap` does not affect those, but only some sub-files inside the cgroup

e.g:, with `--uidmap 0:1:655536`
```
[root@b2473b58f4ee luker]# ls -ahl /sys/fs/cgroup/
total 0
drwxr-xr-x 2 nobody nobody 0 Jul 12 15:27 .
drwxr-xr-x 9 nobody nobody 0 Jul 12 15:27 ..
-r--r--r-- 1 nobody nobody 0 Jul 12 15:27 cgroup.controllers
-r--r--r-- 1 nobody nobody 0 Jul 12 15:27 cgroup.events
-rw-r--r-- 1 nobody nobody 0 Jul 12 15:27 cgroup.freeze
-rw-r--r-- 1 nobody nobody 0 Jul 12 15:27 cgroup.max.depth
-rw-r--r-- 1 nobody nobody 0 Jul 12 15:27 cgroup.max.descendants
-rw-r--r-- 1 root   root   0 Jul 12 15:27 cgroup.procs
-r--r--r-- 1 nobody nobody 0 Jul 12 15:27 cgroup.stat
-rw-r--r-- 1 root   root   0 Jul 12 15:27 cgroup.subtree_control
-rw-r--r-- 1 root   root   0 Jul 12 15:27 cgroup.threads
-rw-r--r-- 1 nobody nobody
[...cut...]
```
while without `uidmap` the directory and all its files are `root:root` inside the container

So, long story short, the only ways I can start a rootless systemd container are:
* not use `uidmap` (tested, ok)
* with `--uidmap 0:0:1 --uidmap 1:X:65535`, where `X` is any starting point in your subuid space that has those `65535` uids after it (tested, ok)

At this point I am not sure if this is intended or not, but if you tell me it's fine I'll work this way

**Comment by mheon** [comment]
I think this is expected, since you're effectively eliminating the root user in the rootless user namespace (the user that ran Podman) from the container. Without that user, you don't have ownership of the cgroups in the container (please note that these are namespaced cgroups, not the host's `/sys/fs/cgroup`, as you are on CGroupsv2 + a recent kernel).

I suppose that what you're attempting, UID separation for individual rootless containers, is possible, but be aware that you have a total of 65537 UIDs available to that user right now per your `podman inspect` (65536 from subuid/subgid and your own UID) so you can only do one container if you retain a size of 65536. You can potentially increase the number allocated in `/etc/subuid` and `/etc/subgid` (please make sure to run `podman system migrate` if you do) but this is not something we test with or have really considered before - most people doing this are using multiple users on the host system, running rootless Podman under each.

**Comment by LucaFulchir** [comment]
Sure, I just need to reserve more subuids for that user, that was expected.

Having one user per container feels... Hacky.  
There's already problems with autostarting rootless containers for non-logged users, `XDG_RUNTIME_DIR`  and `loginctl enable-linger`

...should I close this ticket and open a ticket for a feature request, like `--security-opt=chown-cgroup` or something? A complete remap sounds still safer than multiple users, so there should be some demand.  
It would remove the one-user-per container requirement too, simplifying container management

**Comment by mheon** [comment]
I'll tag in @giuseppe and @rhatdan here for further discussion - is a rootless container that does not include the UID/GID of the user launching the container something we can support? I'm worried the cgroup problem is the tip of the iceberg.

**Comment by rhatdan** [comment]
@giuseppe PTAL

**Comment by giuseppe** [comment]
I think this is fixed in crun with: https://github.com/containers/crun/pull/714

**Comment by rhatdan** [comment]
@LucaFulchir Please try out new crun, and reopen if this does not fix the issue.
