### ISSUE TITLE
How to enable systemd in containers?

### ISSUE THREAD

**Issue by AriFordsham** [containers/podman#11247]
Where can I get containers for running systemd inside podman? Is it only the Fedora containers from the Fedora registry?

What needs to be done to modify a container to run systemd inside it on podman? I would like to run Ubuntu.

**Comment by mheon** [comment]
Podman natively supports systemd in a container; if we detect that a container is using systemd as PID1, we will automatically add support (alternatively, you can manually enable it with the `--systemd=always` flag).

It is sufficient to take any container image that contains systemd and set the entrypoint to `/usr/sbin/init` (or whatever the path to the systemd binary happens to be).

**Comment by AriFordsham** [comment]
> It is sufficient to take any container image that contains systemd

That is my question. Such containers are hard to come by - Docker doesn't support systemd. Either 1) where can I find such a container, or 2) how can I modify a typical Docker container to use systemd init?

**Comment by mheon** [comment]
I would imagine that you could build using a standard Ubuntu image as your base and run an `apt install` inside to grab systemd and associated dependencies?

**Comment by mheon** [comment]
To be clear, there should be no magic here. The container has access to the standard Ubuntu repositories, which will container systemd to service all non-container installs. Said package can be installed from a `RUN` instruction while building a container, and then you can set systemd as the entrypoint via `ENTRYPOINT`.

I can't speak more specifically because I'm a Fedora user myself (Fedora image include systemd by default, so no need to rebuild) - but figuring out what package provides systemd should not be difficult.

**Comment by AriFordsham** [comment]
Thank you @mheon. I think I'm working it out.

**Comment by rhatdan** [comment]
ubi8-init
Image comes ready to run systemd as pid1.
