### ISSUE TITLE
Most podman commands hung after improper container shutdown

### ISSUE THREAD

**Issue by PhracturedBlue** [containers/podman#11283]
/kind bug
**Description**

After doing a `systemctl restart <podman container>` , the process hung.  after a 'ctrl-c' all attempts to access that container now hang:
```
podman ps  --> hangs
podman info --> hangs
podman inspect <broken container> --> hangs
podman inspect <other container> --> success
podman inpect <network> --> success
podman stop <broken container> -->hangs
```

```
podman version
Version:      3.2.3
API Version:  3.2.3
Go Version:   go1.16.6
Built:        Wed Dec 31 16:00:00 1969
OS/Arch:      linux/amd64
```

```
podman --log-level=debug ps
INFO[0000] podman filtering at log level debug          
DEBU[0000] Called ps.PersistentPreRunE(podman --log-level=debug ps) 
DEBU[0000] Merged system config "/etc/containers/containers.conf" 
DEBU[0000] Using conmon: "/opt/podman/libexec/podman/conmon" 
DEBU[0000] Initializing boltdb state at /var/lib/containers/storage/libpod/bolt_state.db 
DEBU[0000] Overriding run root "/var/run/containers/storage" with "/run/containers/storage" from database 
DEBU[0000] Using graph driver overlay                   
DEBU[0000] Using graph root /var/lib/containers/storage 
DEBU[0000] Using run root /run/containers/storage       
DEBU[0000] Using static dir /var/lib/containers/storage/libpod 
DEBU[0000] Using tmp dir /run/libpod                    
DEBU[0000] Using volume path /var/lib/containers/storage/volumes 
DEBU[0000] Set libpod namespace to ""                   
DEBU[0000] [graphdriver] trying provided driver "overlay" 
DEBU[0000] overlay: ignore_chown_errors=true            
DEBU[0000] overlay: mount_program=/opt/podman/bin/fuse-overlayfs 
DEBU[0000] backingFs=extfs, projectQuotaSupported=false, useNativeDiff=false, usingMetacopy=false 
DEBU[0000] Initializing event backend file              
DEBU[0000] configured OCI runtime crun initialization failed: no valid executable found for OCI runtime crun: invalid argument 
DEBU[0000] configured OCI runtime kata initialization failed: no valid executable found for OCI runtime kata: invalid argument 
DEBU[0000] configured OCI runtime runsc initialization failed: no valid executable found for OCI runtime runsc: invalid argument 
DEBU[0000] Using OCI runtime "/usr/bin/runc"            
INFO[0000] Found CNI network podman (type=bridge) at /etc/cni/net.d/87-podman-bridge.conflist 
INFO[0000] Found CNI network inter-cont (type=bridge) at /etc/cni/net.d/inter-cont.conflist 
DEBU[0000] Default CNI network name podman is unchangeable 
INFO[0000] Setting parallel job count to 13             
<< hang >>
```
There are no containers running:
```
ps -ef | grep podman
root     14813  3790  0 10:14 pts/1    00:00:00 grep podman
ps -ef | grep conmon
root     14816  3790  0 10:15 pts/1    00:00:00 grep conmon
```

```podman stop 920ddf1d
DEBU[0000] Using OCI runtime "/usr/bin/runc"            
INFO[0000] Found CNI network podman (type=bridge) at /etc/cni/net.d/87-podman-bridge.conflist 
INFO[0000] Found CNI network inter-cont (type=bridge) at /etc/cni/net.d/inter-cont.conflist 
DEBU[0000] Default CNI network name podman is unchangeable 
INFO[0000] Setting parallel job count to 13             
DEBU[0000] Starting parallel job on container 920ddf1d9675a312ab6802d2c6f91e8a2beb85a6f5778794652c608833c02bc0 
<< hang >>
```

I'd like to figure out how I can unlock my system so I can delete this container and move forward.

**Comment by mheon** [comment]
You can force Podman to detect that a reboot has occurred (which will reset all container states) by removing `/run/libpod/alive` file. You can also remove the `/dev/shm/libpod_lock` file at the same time to force a full recreation of shared container locks.

Otherwise - can you provide additional information on your environment (distribution, architecture, etc)? This looks like a container lock is being held despite no Podman process running, but that should not be possible - we're using standard library locks which guarantee stale locks can be detected and freed.

Otherwise, please provide the systemd unit you're using - could have some bearing on why this failed.

**Comment by PhracturedBlue** [comment]
I'm running on debian-buster x86_64, with ext4 filesystem, but am using statically built podman, conmon, runc.
I'm in the process of moving my docker based images to podman so I have both podman and docker installed and running concurrently.

There is nothing special about my unit files:
```
[Unit]
Description=Syncthing container
After=docker.service
Requires=docker.service

[Service]
#TimeoutStartSec=0
Restart=always
ExecStartPre=-/usr/local/sbin/systemd_docker stop %N
ExecStartPre=-/usr/local/sbin/systemd_docker rm %N
ExecStart=/usr/local/sbin/systemd_docker run --name %N \
  -e VIRTUAL_HOST=syncthing.lan \
  -e VIRTUAL_PORT=8384 \
  --network inter-cont \
  -p 22000:22000/tcp \
  -p 22000:22000/udp \
  -v syncthing:/var/syncthing \
    syncthing/syncthing:latest

[Install]
WantedBy=multi-user.target
```
You can ignore the 'docker' stuff in there.  I use the same service files for docker or podman depending on configuration, so 'systemd_docker' is just a wrapper:
```
#!/bin/sh
exec /opt/podman/bin/podman "$@"
```
If I remove the `/run/libpod/alive` while containers are running, will they be re-detected as running? (I don't actually have any running containers, but would like to understand the process).  While I appreciate the steps to get mysystem unstuck, I'm much more interested in ensuring that podman is robust for my use case.  I haven't actually run the steps you proposed in the hope I can provide more information first.

**Comment by mheon** [comment]
That unit file doesn't look correct - systemd defaults to `type=simple`, which has issues with tracking container state (it tracks the Podman binary, but Podman is not the container, and the Podman process dying does not mean the container process stopped - this can cause systemd to become confused as to the state of the container). We strongly recommend that you use `podman generate systemd` (`podman generate systemd --new` in this case) to create unit files that are guaranteed to avoid pitfalls like this.

That said - there's nothing in there that would cause the issues you're seeing.

To answer your question: no - the post-restart state refresh resets container state on all containers to either Exited or Created, assuming that no process can survive a restart.

If I had to hazard a guess, this might be caused by static linking? The locks in question are pthread Mutexes - possible that static-linking brought in a version of that library that doesn't support the advanced shared-memory locking features we're using. Seems unlikely, but it's the best guess I have at present.

**Comment by PhracturedBlue** [comment]
Actually, the pthread idea may be more likely.  my static build was done using musl.  I have no idea if they have a fully compliant pthread implementation or not (though I guess there would be more reports of failures on Alpine linux if it was common.  I'll try rebuilding the binaries with glibc and see if I can reproduce the issue.

**Comment by vrothberg** [comment]
I assume the issue was caused by using a static build with musl.  Please reopen if I am mistaken.
