### ISSUE TITLE
Windows Installer breaks PATH variable

### ISSUE THREAD

**Issue by max06** [containers/podman#11416]
Your Windows Installer is breaking the users environment by adding a single `"` at the end of the path-variable.

Can only be reverted via registry editor:
![image](https://user-images.githubusercontent.com/7556827/131900627-01d3e293-56b2-40c8-ae92-065883e2a715.png)

Windows UI for env vars doesn't show it anymore. 

Also, as a side note: It doesn't clean up the env var when uninstalling.

**Comment by mheon** [comment]
@jwhonce PTAL

**Comment by jwhonce** [comment]
The clean up issue is being tracked here: https://github.com/containers/podman/issues/11089 

We are waiting on PR to wixl to support clean up.

@baude @ashley-cui I seem to remember the quote issue being addressed or at least discussed before. Do you have any input?

**Comment by nathandavidson** [comment]
One non-obvious symptom of this issue is that, after installing Podman, the CLI can only be called from the traditional Windows Command Prompt (CMD) and not from PowerShell. Apparently CMD will parse PATH with the invalid trailing quote, but PowerShell will not. So PowerShell users will just get the usual error message indicating a missing command:
```
podman: The term 'podman' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

CMD:
![image](https://user-images.githubusercontent.com/2791258/132583265-0fd03e66-7439-495b-8a11-0c02dc2a392c.png)

PowerShell:
![image](https://user-images.githubusercontent.com/2791258/132583330-a42b5c57-9b84-4ec2-a984-740593b990d7.png)

Not that this changes anything about the underlying problem, but it might help to direct PowerShell users' searches to this issue where the fix is described.

**Comment by ndavids-msft** [comment]
So I found that you can actually edit it in the regular environment variables UI, you just need to use the "Edit text" option.

Steps
1. Open the System Properties windows (sysdm.cpl)
2. Under the Advanced tab click "Environment Variables..."
3. Edit the Path variable in the User variables section (top section of the window)
4. In the Edit dialog, click the "Edit text..." button 
![image](https://user-images.githubusercontent.com/2791258/132586741-96d30296-ae84-4198-aa2e-fcc77f410885.png)
5. Remove the trailing quote, then "OK" through all the open dialogs
![image](https://user-images.githubusercontent.com/2791258/132586843-80214fce-f4a0-46e0-8f93-63dd4a25c02b.png)

**Comment by max06** [comment]
I should have confirmed that dialog box when I had the chance ... that's easier than using the registry 💯

**Comment by max06** [comment]
The latest installer is still adding a single double-quote to the Path...

**Comment by rhatdan** [comment]
Is this fixed in podman 3.4.1

**Comment by max06** [comment]
@rhatdan Sorry, I completely missed this... 

Just tested: Removed all previous versions, made sure my env vars are clean. Still a lost double-quote after 3.4.1...

**Comment by rhatdan** [comment]
28 days ago, I nagged the PR to MSI, but still no movement that I can see.

**Comment by max06** [comment]
/shrug
Can I add some WD-40 somewhere?

**Comment by rhatdan** [comment]
Go add a further whine to #11089
