### ISSUE TITLE
Does the unprivileged user namespace that podman relies on really has serious security risks?

### ISSUE THREAD

**Issue by daiaji** [containers/podman#11443]
ArchWiki's [Rootless Podman](https://wiki.archlinux.org/title/Podman#Rootless_Podman)  chapter in the podman entry points out that there are very serious security risks in the non-privileged user namespace. I want to know whether these security risks still exist in the kernel of version 5.14 or 5.13.  Rootless makes the deployment of containers more dangerous, which makes me somewhat unacceptable.

**Comment by mheon** [comment]
Unprivileged access to user namespaces does significantly increase the amount of attack surface available to unprivileged users, which does introduce potential vulnerability. A recent example of this is [here](https://nvd.nist.gov/vuln/detail/CVE-2021-22555). This is the only example of such a CVE I am presently aware of. If your kernel has been patched (and I presume all major distributions have rolled out such patches) you should be safe.

We strongly feel that the potential risks of increased attack surface are worth it, as the alternative is running containers as the real root user on the system. Rootless containers mitigate many types of container breakout attacks simply by ensuring the user in the container has no permissions to affect the system. Either way, you expose yourself to risk (the potential for a new container breakout CVE, versus a new privilege escalation CVE specifically in the areas exposed by a user namespace). Anecdotally, I've seen a lot more container breakouts than I have user namespace privilege escalations, and I strongly believe that rootless containers are the more secure option.

**Comment by daiaji** [comment]
Is the fix for CVE-2021-22555 still not accepted by the mainline kernel?
Buffer overflow attack?  As linus said, many components of the kernel are indeed worth refactoring using Rust language.

**Comment by mheon** [comment]
I'm fairly certain that CVE-2021-22555 is fixed in the upstream kernel, but honestly, I don't follow that very closely; I only really know that it's been fixed in RHEL and similar distributions.

Unprivileged user namespace attacks are all going to be directly against syscalls, so Seccomp is the best defense - preventing users from making unnecessary syscalls should prevent any potential breakouts. Apparmor and SELinux aren't really about stopping the attack so much as they are about limiting the ability to do damage.

I don't know of a way to enable rootless user namespaces for just specific users. It would be interesting to see a more limited form of unprivileged user namespaces than what we have now (I've imagined a file capability that allows only specific binaries to use `CLONE_NEWUSER` without root, which Podman could be shipped with), but that will require additional work on the upstream kernel. Unfortunately, rootless Podman can't function without it (we need several of the things it enables to function, most notably mounting tmpfs and FUSE filesystems).

**Comment by rhatdan** [comment]
Almost every linux distribution now supports rootless user namespace, so the bulk of the Linux world considers User Namespace for rootless users to be safe.  Any CVEs will be addressed quickly and since we have had this enabled by default for many years, we should have seen a flood of CVEs.  In my opinion this means the kernel has done a good job of controlling the attack surface.

Bottom line is Podman takes advantage of this feature for rootless containers and on systems that don't have rootless usernamespace you can run rootfull podman.
