### ISSUE TITLE
podman machine init Support emulating different architectures

### ISSUE THREAD

**Issue by IamEld3st** [containers/podman#11458]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

It would be nice to be able to init a machine with different architecture type than the host machine. Should be supported through qemu. For example run x86 on arm or arm on x86.

Something like:
```
podman machine init --arch=x86_64 x86_machine
```

**Comment by rhatdan** [comment]
SGTM
Interested in opening a PR?

**Comment by rhatdan** [comment]
@baude @jwhonce @ashley-cui WDYT?

**Comment by vladdy** [comment]
I would be interested in working on a PR for this if OP is not availble.

**Comment by IamEld3st** [comment]
I didn't do any real work on this except look at parts of the code... If @vladdy wants to take the PR or anybody else, feel free to do so.

**Comment by vladdy** [comment]
Sounds good. @rhatdan, could I get this assigned to me please?

**Comment by rhatdan** [comment]
yup

**Comment by IamEld3st** [comment]
@vladdy Any updates on this?

**Comment by vladdy** [comment]
@IamEld3st I've made some progress and planning to create a PR on Saturday. I'll let you know if that delays.

**Comment by rhatdan** [comment]
This is being worked on .

**Comment by afbjorklund** [comment]
It is possible to use lima for this, if urgent. (Hint: it is rather slow)

**Comment by bkrugerp99** [comment]
What testing can be done to help this along?   I can definitely help test arm mac running x84_64.

**Comment by rhatdan** [comment]
@dustymabe Any chance of us getting this package installed by default?

**Comment by dustymabe** [comment]
@rhatdan - see request and discussion at https://github.com/coreos/fedora-coreos-tracker/issues/1088

**Comment by sanyer** [comment]
Would be nice to have it also for macOS. @rhatdan

**Comment by rhatdan** [comment]
Yes we are working on this upstream right now,  basically trying to get qemu-user-static split into separate packages so we could install fewer of them on Fedora CoreOS.

https://bugzilla.redhat.com/show_bug.cgi?id=2061584

**Comment by cpolizzi** [comment]
Thank you for working on having the podman managed machine incorporate the QEMU emulation packages. Currently I have had to handle this in a restrictive corporate environment and specifically for an M1 Mac. By restrictive I mean:
1. End computing assets must be routed through a proxy server to access public / external / Internet resources.
2. Proxy infrastructure are SSL inspecting.

Combined this needs to be a consideration, unless, the multi-architecture support emulation is going to be packaged with the podman managed machine. The remainder of this assumes that the emulation support is not packaged with the podman managed machine. To that end, this is how one can get the necessary dependencies installed in the podman managed machine, in a restrictive corporate environment. Please note that none of this applies to a true disconnected environment.

The second part is trivial but due to an inspecting SSL proxy one must be able to provision those specific certificates for the inspection solution (e.g., Menlo Security as an example but has a ton of competitors with varying degrees of solution approaches).

For the first part, I had to configure the podman managed machine to use a proxy in order to install the **qemu-user-static** package (and yes, all of its dependencies) at this point in time.

Assuming one creates a simple configuration file defining the desired proxy configuration, entitled simply as **proxy.env**, such as:
```
FTP_PROXY=http://<proxy-host>[:<proxy-port>]
HTTPS_PROXY=http://<proxy-host>[:<proxy-port>]
HTTP_PROXY=http://<proxy-host>[:<proxy-port>]
NO_PROXY=.<private-domain>,localhost,127.0.0.1,0.0.0.0,::1
ftp_proxy=http://proxy-host/[:proxy-port]
http_proxy=http://proxy-host/[:proxy-port]
https_proxy=http://proxy-host/[:proxy-port]
no_proxy=.<private-domain>,localhost,127.0.0.1,0.0.0.0,::1
```

1. Install any necessary SSL inspection CA certificates and update CA trust system wide:
```
    sudo install -o root -g root -m 0644 *.crt /etc/pki/ca-trust/source/anchors/
    sudo update-ca-trust
```
2. Configure proxy variables for **rpm-ostree** SystemD service:
```
    sudo install -o root -g root -m 0644 proxy.env /etc/proxy.env
```
4. Ensure **rpm-ostreed** SystemD service uses a proxy to download the QEMU support package:
```
    sudo mkdir /etc/systemd/system/rpm-ostreed.service.d
    sudo install -o root -g root -m 0644 rpm-ostreed.conf /etc/systemd/system/rpm-ostreed.service.d/
    sudo systemctl daemon-reload
    sudo systemctl restart rpm-ostreed.service
```
5. Determine if emulation package is installed (exit status 0 means it is present, stdout will have full package name; non-zero otherwise):
```
    rpm -q qemu-user-static
```
6. Install emulation package if needed (this takes awhile, not due to connectivity but due to FCOS processing):
```
    sudo rpm-ostree install qemu-user-static
    sudo systemctl reboot
```

**Comment by protosam** [comment]
Avoid rebooting inside qemu, podman wont do things like mounting your volumes when it comes back up. Rely on the machine stop and start commands.
```
podman machine stop
podman machine start
```

**Comment by cpolizzi** [comment]
Podman perfectly re-mounts any volumes upon start up regardless of how the managed machine is terminated (e.g., `podman machine stop`, `pkill -9 qemu`, `podman machine ssh sudo systemctl poweroff` or even for a one-stop shop for restarting `podman machine ssh sudo systemctl reboot`). I have yet to see a problem in regard to Podman mounting volumes. This is working for hundreds of people for my work across both Intel and M1 Mac's.

Curious why you state to "avoid rebooting inside qemu" and "podman wont do things like mounting your volumes when it comes back up." Because this is a behavior that I do not see (volumes are always remounted without issue on start).

Now I

**Comment by dustymabe** [comment]
> Yes we are working on this upstream right now, basically trying to get qemu-user-static split into separate packages so we could install fewer of them on Fedora CoreOS.
> 
> https://bugzilla.redhat.com/show_bug.cgi?id=2061584

Note that this is done now and the `qemu-user-static-x86` package will be in the next `testing` and `next` Fedora CoreOS release on aarch64. Follow https://github.com/coreos/fedora-coreos-tracker/issues/1088 for updates.

**Comment by pawilon** [comment]
A TL;DR for people like me for whom it wasn't immediately clear how to use the solution from this issue. Here's how this works on a x86 Mac.

An initial attempt to run aarch64 architecture while on x86 will give you an error:

```
$ podman run --rm --arch aarch64 -it alpine
{"msg":"exec container process `/bin/sh`: Exec format error","level":"error","time":"2022-09-25T00:59:46.000783556Z"}
```

In order to fix it, you do the following:

```
$ podman machine ssh
# Inside the machine
$ sudo rpm-ostree install qemu-user-static-aarch64
$ sudo systemctl reboot
```

Now you just wait for the machine to come back up, and voila:

```
podman run --rm --arch aarch64 -it alpine
/ #
```

In case you're on MacOS with M1 and want to run x86 containers, you instead install `qemu-user-static-x86` on your podman machine.

**Comment by dustymabe** [comment]
> In case you're on MacOS with M1 and want to run x86 containers, you instead install `qemu-user-static-x86` on your podman machine.

In that case there is no need since `qemu-user-static-x86` is already installed on `aarch64` FCOS. See https://github.com/coreos/fedora-coreos-tracker/issues/1088 and https://github.com/coreos/fedora-coreos-tracker/issues/1237.

**Comment by multimeric** [comment]
Yep, in my case on an ARM MacOS, the default `podman machine init` machine had this built in. I just had to remember to use `--arch amd64` to my build/run commands.
