### ISSUE TITLE
Cannot install podman on ubuntu 20.04

### ISSUE THREAD

**Issue by graywolf-at-work** [containers/podman#11571]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Installing podman on ubuntu 20.04 fails. Used source:

```
deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04/ /
```

**Steps to reproduce the issue:**

1. apt-get update

2. apt-get install podman

**Describe the results you received:**

```
# apt-get install podman
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 podman : Depends: containers-common (>= 100:1-21) but 100:1-17 is to be installed
E: Unable to correct problems, you have held broken packages.
```

**Describe the results you expected:**

The installation to succeed.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

Hard to since I cannot install podman, but apt-cache info says 100:3.3.1-1.

**Output of `podman info --debug`:**

Cannot get this info.

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
# apt list podman
Listing... Done
podman/unknown 100:3.3.1-1 amd64
podman/unknown 100:3.3.1-1 arm64
podman/unknown 100:3.3.1-1 armhf
podman/unknown 100:3.3.1-1 s390x
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

N/A

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Local container, but should not be relevant.

**Comment by Luap99** [comment]
@lsm5 PTAL

**Comment by themreza** [comment]
Why is it so difficult to install this package?
The current issue is that OpenSUSE has built podman with a requirement for `containers-common (>= 100:1-20)` but the `.deb` file they provide for Ubuntu 20.04 is for version `100:1-17`.

**Comment by guss77** [comment]
I always assumed the "stable" label means that things don't get put in until they are tested.

BTW, "testing" seems to install fine (it has the same podman version and a correct containers-common version). So this is currently my workaround to enable **production** workloads - use the "testing" repository - because it is stable (for now)...

**Comment by unuunn** [comment]
Thanks the university of chicago for saving old versions.

As a temporary solution, you can install a previous version of the podman deb package from their mirror. The other packages will be pulled in automatically from the opensuse.org repository. 

`wget https://mirror.cs.uchicago.edu/libcontainers/xUbuntu_20.04/arm64/podman_3.2.3-1_arm64.deb && apt install ./podman_3.2.3-1_arm64.deb`

**Comment by guss77** [comment]
The official kubic "stable" repository is now working well.

Is it possible to have the repository retain older versions as well - so that if there are issues with the latest version, we can still install an older one?

**Comment by mheon** [comment]
It is not. We've looked into this on numerous occasions, without success. Our current approach is to get Podman into official repositories for as many distros as we can. For Ubuntu we are in the official repos from 20.10 onward.

**Comment by lsm5** [comment]
@guss77 The Kubic stable repo only gets stable upstream releases, while the testing repo gets RCs as well, so that's why the stable and testing names. I realize the issue with the names but too late to change it now. 

Once podman lands in ubuntu 22.04 LTS, the kubic packages will no longer be updated. The kubic packages are not official packages and they get nowhere close to the amount of testing as the official distro packages do. This issue occurred because I copied the podman packaging files yesterday from testing to stable but not the containers-common files. I'll ensure I move dependencies  along with the main package going forward and run a manual installation check everytime.

And as @mheon mentioned, OBS didn't let us save older builds on the repo. That and quality control issues are the reasons we try to support work on getting podman into official repos and recommend official repos over Kubic repos wherever possible.

HTH. Closing...
