### ISSUE TITLE
Detailed API changelog

### ISSUE THREAD

**Issue by arctic-alpaca** [containers/podman#11829]
/kind feature

**Description**
The [networks API endpoint](https://docs.podman.io/en/latest/_static/api.html#tag/networks) has recently been changed. As far as I can tell, there is no changelog detailing what exactly changed. It would be really helpful for developers targeting the API to have some kind of changelog.

**Comment by Luap99** [comment]
That is definitely something I want to, at least for the breaking changes in 4.0.
@mheon did you ever get started on a document with the 4.0 changes? If I remember correctly you want do this.

**Comment by mheon** [comment]
I did not. Let me get one going today.

**Comment by arctic-alpaca** [comment]
A somewhat related feature that would help here is versioning of the API reference. At the moment there is only the latest as far as I can tell.

**Comment by Luap99** [comment]
You can get the one for 3.4.0 here: https://docs.podman.io/en/v3.4.0/_static/api.html

**Comment by Luap99** [comment]
Actually looking at this the v3.4 one contains wrong information about the network API endpoints.
I also have no idea how users can browse to this site.

**Comment by arctic-alpaca** [comment]
> You can get the one for 3.4.0 here: https://docs.podman.io/en/v3.4.0/_static/api.html

As far as I can tell, this is always the same documentation since it loads `https://storage.googleapis.com/libpod-master-releases/swagger-latest.yaml` with every version I tried.

> I also have no idea how users can browse to this site.

I think this is possible on the bottom right on this site: https://docs.podman.io/en/latest/Reference.html

But the link in `To see full screen version please visit: API documentation` always leads to the latest reference. The general user experience regarding the API documentation could be improved.

**Comment by mheon** [comment]
I can't do this alone; the existing release notes are a massive time investment, adding this would make things much more difficult and time-consuming. I think we may need to spread the burden around and require PR authors to document what changes their PRs made.

**Comment by Luap99** [comment]
Docker compat api network/create accepts now more than 1 ipam config and also accepts other drivers than bridge, e.g. macvlan

Container list endpoint now displays ports in specgen port format (already used for container create)

The network list and inspect endpoint now return the new network struct as json instead of the CNI config, see https://docs.podman.io/en/latest/_static/api.html?version=v4.0#operation/NetworkInspectLibpod
The network create endpoint now accepts the new network struct as json in the body.

**Comment by Luap99** [comment]
Regarding an actual changelog I think it would be good if we enforce this for new PRs. This would also help when we have to debug new API issues to see whenever an API change was on purpose or accidental.

**Comment by arctic-alpaca** [comment]
@Luap99 Thank you for listing the specific changes here.

Requiring some kind of changelog for PRs changing the API interface would be great. Having a list of changed endpoints with explicitly listed modifications would help greatly and also improve confidence when updating.

**Comment by Luap99** [comment]
I think someone should create a document in the repo where we could track API changes more detailed.
Reviewers would need to enforce that this documented is updated when API endpoints are changed.

**Comment by rhatdan** [comment]
@edsantiago Any idea on how we could get the CI/CD system to enforce this?  Potentially watching for changes in pkg/api subdirs and making PRs add a [NO API CHANGE] commend to PR or change the newly create APICHANGES.md file?

**Comment by vrothberg** [comment]
I am going to take a shot and close the issue.  I believe our changelogs have improved with PRs enforcing release notes.

**Comment by edsantiago** [comment]
>@edsantiago Any idea on how we could get the CI/CD system to enforce this? Potentially watching for changes in pkg/api subdirs and making PRs add a [NO API CHANGE] commend to PR or change the newly create APICHANGES.md file?

Really, really sorry to take so long on this. It's just something I don't have expertise on, so I had to poke in unknown places.

Turns out, we already have a tool that can help: `issue-labeler`, which we use for adding windows, mac, and remote labels.

It should be very easy to add a new rule to https://github.com/containers/podman/blob/main/.github/issue-labeler.yml such that files touched under `pkg/api` will trigger the `kind/api-change` label[1]. The release-notes tool groks `kind/foo` labels, and sorts closed PRs into buckets, making it easy for the release person to spot those. Is that worth pursuing?

 [1] `kind/api-change` does not exist as a label yet, but it's very easy to create

**Comment by mheon** [comment]
Even if we don't decide to add enforcement through the release-notes tool, having a label on PRs saying that an API change was made is useful. We're pretty lenient about letting these in, and something to invite more scrutiny would be welcome.
