### ISSUE TITLE
Update CentOS 8 packages

### ISSUE THREAD

**Issue by srbala** [containers/podman#11852]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug 

**Description**
Dev releases for CentOS `podman` at https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/CentOS_8/ is no longer updated, last version build was `3.2.3`

currnet release version is `3.4.x`, please update buids to newer version

**Comment by mheon** [comment]
@lsm5 PTAL

**Comment by mheon** [comment]
No, that's the current upstream development version - 4.0 will be released in January.

**Comment by srbala** [comment]
@lsm5 is it possible to setup some GH workflow actions to update sources. Now OBS build service supports GitHub integraions. Give me some guidelines, I would be happy help/maintain

**Comment by lsm5** [comment]
@srbala we recently removed installation steps for Kubic packages on CentOS 8 from the official podman docs because the Kubic packages were causing issues for someone (I think it was the Ceph team). Given that removal + CentOS 8 going EOL sometime this December (IIRC) + availability of latest podman builds in in the default repos on CentOS 8 Stream (& 9 Stream), it's really not worth maintaining the Kubic CentOS packages.

HTH.
