### ISSUE TITLE
Static "nix" build fails for v3.4 on Ubuntu 21.10 (Mate)

### ISSUE THREAD

**Issue by jradxl** [containers/podman#12022]
**Steps to reproduce the issue:**

1. Carry out your instructions to achieve a NIX build
```
john@u2110ab:~$ curl -L https://nixos.org/nix/install | sh
<and reboot>
john@u2110ab:~$  git clone -b v3.4 https://github.com/containers/podman.git 
john@u2110ab:~$  cd podman
```

**Describe the results you received:**

```
john@u2110ab:~$ nix build -f nix/
builder for '/nix/store/jb63gx4wwr661p3vbg2k6500haada84g-go-1.16.5.drv' failed with exit code 1; last 10 log lines:
  ok        cmd/link/internal/benchmark     0.046s
  ok     cmd/link/internal/ld    2.420s
  ok     cmd/link/internal/loader        0.046s
  ok     cmd/nm  4.410s
  ok     cmd/objdump     4.681s
  ok     cmd/pack        1.257s
  ok     cmd/trace       0.265s
  ok     cmd/vet 6.965s
  FAIL
  go tool dist: Failed: exit status 1
cannot build derivation '/nix/store/gwhv6qvrjkn9ddmxm0ikf60m08wmm2rb-podman.drv': 1 dependencies couldn't be built
[21 built (1 failed), 273 copied (1485.5 MiB), 364.7 MiB DL]
error: build of '/nix/store/gwhv6qvrjkn9ddmxm0ikf60m08wmm2rb-podman.drv' failed

```

**Describe the results you expected:**
Satisfactory build, so I can get....
./result/bin/podman --version

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Doesn't apply here
```

**Output of `podman info --debug`:**

```
Doesn't apply here
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
Doesn't apply here
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**
Doesn't apply here

Yes/No
Building in a VirtualBox instance of Ubuntu 21:10

**Comment by mheon** [comment]
None of the maintainers here are Nix experts - can you bit a bit more clear as to what's going wrong? I can't see any error message from there that's directly related to the source.

**Comment by rhatdan** [comment]
I don't see this as a podman issue. you can continue the conversation on this closed issue.

**Comment by stellarpower** [comment]
I don't know anything about nix either, but I think overall the static build could be simplified. I've spent the last 12 hours trying now, to no avail. I was making a recipe using podman to run the build with the intention of uploading, but I'm just hitting new failures all the time. It seems to be building a large amount from source; go fails because the os library's tests don't succeed, git is failing because some tests there don't pass. So I haven't even been able to get onto the podman sources yet if there's no go compiler, I feel this all probably ought to be overkill. Not knowing anything about nix, I haven't found a way to disable the testing phase by searching online. If git isn't technically passing a few tests from being inside a container environment that shouldn't matter for us, as long as podman itself works once built. Could the nix build be modified just to pull pre-built packages for the build dependencies? Or else, could someone point me to where exactly it's being built (as part of CI?) for the releases section on GitHub, so I can try and replicate the settings there? Thanks
