### ISSUE TITLE
Run --requires with port

### ISSUE THREAD

**Issue by PumpkinSeed** [containers/podman#12044]
Actually it's more like a question/feature idea rather a bug. My original problem with Docker that we need to hack the hell out of it if we want to wait for a specific port in a certain container. Is it possible to tell the podman run that it requires that container with that certain port?

**Comment by flouthoc** [comment]
@PumpkinSeed I am not sure if this will be ever directly supported in podman `run` since this looks like a very specific use-case  and as suggested by @mheon with little bit of manual plumbing `socket-actived containers` would be better solution for this.

Just marking this issue as closed but feel free to re-open or continue discussion in this thread.
