### ISSUE TITLE
Static Build for #11728 isn't static

### ISSUE THREAD

**Issue by gliptak** [containers/podman#12198]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Downloaded `Static Build` for #11728 isn't static

```
ldd podman
./podman: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./podman)
./podman: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./podman)
	linux-vdso.so.1 (0x00007ffc47492000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fc78e5cd000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fc78e5c7000)
	libgpgme.so.11 => /lib/x86_64-linux-gnu/libgpgme.so.11 (0x00007fc78e576000)
	libassuan.so.0 => /lib/x86_64-linux-gnu/libassuan.so.0 (0x00007fc78e561000)
	libgpg-error.so.0 => /lib/x86_64-linux-gnu/libgpg-error.so.0 (0x00007fc78e53e000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fc78e533000)
	libseccomp.so.2 => /lib/x86_64-linux-gnu/libseccomp.so.2 (0x00007fc78e50f000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fc78e31d000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fc78e60b000)
```

```
ldd podman-remote 
./podman-remote: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./podman-remote)
./podman-remote: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./podman-remote)
	linux-vdso.so.1 (0x00007fff29bdb000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f52e5230000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f52e522a000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f52e5038000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f52e526e000)
```

**Steps to reproduce the issue:**

1. Download (current) Static Build

2. Validate with `ldd`

**Describe the results you received:**

**Describe the results you expected:**

```
ldd podman
	not a dynamic executable
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

N/A

#10656
#10679
#8943

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by mheon** [comment]
What do you mean by "Downloaded static build" for that issue? It's not a release so no build is associated with it? Are you trying to download a specific static build for a specific release? Please be more specific.

**Comment by rhatdan** [comment]
We don't support static builds.  If users want static builds they should attempt to do them on their own.

**Comment by gliptak** [comment]
@mheon I'm referring to Staic Build section on https://cirrus-ci.com/build/6564084112949248 (sorry Cirrus isn't very linking friendly)

![image](https://user-images.githubusercontent.com/50109/140800957-5abc286f-6848-40bf-b9bb-73eeeec51d7c.png)

@rhatdan the main README specifically highlights static build for testing purposes https://github.com/containers/podman/blob/main/README.md#static-binary-builds

https://github.com/containers/podman/pull/12197

**Comment by mheon** [comment]
@cevich PTAL

**Comment by cevich** [comment]
Hmm, indeed it doesn't appear to be working properly. I wonder if [this warning message gives any clue as to why](https://cirrus-ci.com/task/5724808781496320?logs=main#L437).  In any case, I didn't write the static-build task nor do I fully understand the underlying build system :confused: We'll need to tap the person who set this up, and I can't remember who that is off-hand, we'll need to go digging through git history...

**Comment by cevich** [comment]
@hswong3i or @saschagrunert either of you can tell what might be going wrong here?  I will add that we do pre-build non-static `./bin/podman` and `./bin/podman-remote`, so maybe those are getting in the way somehow?

**Comment by hswong3i** [comment]
Sorry all I may no longer contribute for static build maintenance, since I had shift my focus to per-OS native deb/rpm packaging: https://build.opensuse.org/project/show/home:alvistack

e.g. When https://github.com/containers/podman/releases/tag/v3.4.1 released, I could taking care its packaging within 30mins for both Ubuntu/Debian/CentOS/Fedora/openSUSE recent releases as below:
* https://github.com/alvistack/containers-podman/commit/fd9e1d2ffdf61e76b316c91a22149ac1f4bb92f9
* https://build.opensuse.org/package/show/home:alvistack/containers-podman-3.4.1

Also some limitation for static build:
* Some platform native compile flag need to build with dynamic for better support, e.g. libsystemd-dev, libseccomp-dev, libapparmor-dev, selinux, etc
* Maintain static build support with Nix's upstream changes is extremely time consuming
* A single static build binary usually not enough for production installation, e.g. missing systemd service files, config file, etc. If we handle that with Makefile or .tar.gz archive then we are most likely redoing what deb/rpm packaging system duty
* Single static binary also didn't handle package dependency, e.g. podman depends on crun, conmon, containers-common, etc. With deb/rpm packaging again this is super simple
* It is difficult for system admin to handle static binary upgrade and inventory auditing (with deb/rpm we could simply use `apt-get upgrade` and `dpkg-query -l` to handle it)
* About build and distribute: with static binary I need to build it locally and upload to GitHub release manually, where with https://build.opensuse.org + https://build.opensuse.org/package/show/openSUSE:Tools/osc I could quickly do a mockup build with my local Ubuntu 21.10, then push with `osc` and all being automated.

Please kindly forgive me for no longer contributing static binary build; but switching to OBS + `osc` is super easy and greatly reduce my daily workload.

P.S. kubic toolchain for podman/cri-o always conflict with kubernetes official https://apt.kubernetes.io/ or https://packages.cloud.google.com/; in order to making them all working well together I am now maintenance 300+ OBS-based packages, with daily update ;-)

**Comment by saschagrunert** [comment]
The issue seems to be in those lines: https://cirrus-ci.com/task/5724808781496320?logs=main#L421-L423

We copy the `bin` directory to the target sources and therefore the Makefile thinks everything is already up to date.
