### ISSUE TITLE
apiv2 tests: mirroring doesn't play well with multiarch?

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#12631]
In @jwhonce's PR #12527, the apiv2 test [failed](https://api.cirrus-ci.com/v1/task/6216807318028288/logs/main.log) (not clear if it's a flake) with:
```
[+0020s] ok 89 [10-images] POST images/create?fromImage=alpine&platform=linux/arm64 [-d {}] : status=200
         ok 90 [10-images] GET images/alpine/json : status=200
         not ok 91 [10-images] GET images/alpine/json : .Architecture
         #  expected: arm64
         #    actual: amd64
```
The test code in question is https://github.com/containers/podman/blob/b9141c06f0350c0ec53b8dc3246d1dbd5c72e2a9/test/apiv2/10-images.at#L51-L58

This is a test that hasn't otherwise failed. It seems possible that the root cause is my recent PR #12596, in which I added:
```
env CONTAINERS_REGISTRIES_CONF=$TESTS_DIR/../registries.conf podman ...
```
...to make podman (client and server) use our [local registries.conf setup](https://github.com/containers/podman/blob/b9141c06f0350c0ec53b8dc3246d1dbd5c72e2a9/test/registries.conf) to avoid hitting the docker.io throttling.

I can't reproduce the failure on my laptop, leading me to wonder if this is one of those cases where a CDN delivers different images at different times/places. 

But anyhow. I no longer care about understanding the error. I would like to just do things differently. @vrothberg, the test above is your code. Given your views on shortnames, would it be possible to rewrite that test so it uses `quay.io/libpod/testimage:20210610` instead of unadorned `alpine`? (Yes, I tried before filing this, but couldn't get it to work).

**Comment by vrothberg** [comment]
Thank you for filing this issue, @edsantiago.

Multi-arch images in the wild have a looooooong history of sometimes screwing things up.  For instance, a "multi-arch" image (or manifest list) would have an entry for `arm64` while the image it points to claims to be an `amd64` one. There was a bug in Docker that lead to it. A prominent example was the k8s pause image. This is my best guess. I don't think that a CDN could screw things up since that would have changed the digest and hence led to an error during validation.

What we can do is to add an alias for `alpine`. I can wrap something up!

**Comment by vrothberg** [comment]
Curious, that is already covered:
```TOML
[[registry]]              
prefix="docker.io/library"
location="quay.io/libpod" 
```

If we pull `alpine` we'll pull `docker.io/library/alpine` which gets translated to `quay.io/libpod/alpine`.  That being said, I have no explanation since the arm64 image of `quay.io/libpod/alpine` has the correct architecture:
```
 skopeo inspect --config docker://quay.io/libpod/alpine@sha256:f270dcd11e64b85919c3bab66886e59d677cf657528ac0e4805d3c71e458e525|jq .architecture
"arm64"
```
