### ISSUE TITLE
Add squash option to podman commit

### ISSUE THREAD

**Issue by pbrezina** [containers/podman#12889]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

Please, add --squash option to `podman commit` so the new image does not create a new layer but is instead squashed to the latest layer.

**Comment by baude** [comment]
at @vrothberg wdyt?

**Comment by vrothberg** [comment]
Thanks for the proposal, @pbrezina!

I think it's fairly easy to get done since the backend in Buildah already supports squashing on commit. What had to be done is to extend the Podman CLI with a `--squash` flag and do the plumbing down to when committing the container (i.e., https://github.com/containers/podman/blob/main/libpod/container_commit.go#L63).

@ncrowe200, that would a cool project to work on when you find time.

**Comment by pbrezina** [comment]
Thank you for looking into it. To explain the use case - I want to setup some applications that requires systemd and a specific hostname (FreeIPA precisely), which is currently not possible to do during build time. But I also want to trim down unneeded layer to reduce size of the resulting image.

**Comment by rhatdan** [comment]
@flouthoc PTAL

**Comment by flouthoc** [comment]
ackd. I'll take a look.

**Comment by flouthoc** [comment]
Above PR should close this.
