### ISSUE TITLE
How to disable podman from managing it's own firewalld rules

### ISSUE THREAD

**Issue by mnsmithuk** [containers/podman#13046]
Hi

Is there a way to stop podman from managing it's own firewall rules?  Podman is putting all of the container's open ports in trusted  zone of firewalld and I can't find a way to limit access to a set of ip addresses only over the internet.

Ideally I think podman should configure it's own zone rather than use the built-in trusted zone.

**Comment by mheon** [comment]
With Podman v4.0, we are looking into implementing this via the new Netavark network stack, but it will not be available in the initial release due to missing features in firewalld (https://github.com/firewalld/firewalld/pull/903 which will arrive in Firewalld 1.1.0). Using the present stack, you can theoretically disable the firewalld code by removing the `firewall` plugin from your CNI configurations, but no traffic will pass through the firewall without it (unless you manually add rules to do so)

**Comment by mnsmithuk** [comment]
also how do you remove plugin via command line or do you hva eto manually edit the conlist file ?

**Comment by mheon** [comment]
You'd have to manually edit the conflist.

Removing the firewall plugin will prevent the firewalld rules from being added, but the normal iptables rules used by Podman would still be created. Unfortunately, firewalld will deny traffic from these rules unless you allow the relevant subnets through firewalld.
