### ISSUE TITLE
[CI] please save artefacts of the builds

### ISSUE THREAD

**Issue by tobwen** [containers/podman#13162]
/kind feature

**Description**
_Github_ allows exporting of the artifacts, which are built in _Actions_, for later use. 

Could you expose those artifacts? Users might use them without needing compiling them on their own.

**Comment by rhatdan** [comment]
Is this really a Buildah issue?
@nalind WDYT?

**Comment by nalind** [comment]
@rhatdan maybe not as much for buildah as for podman.  There, a PR can be for fixing logic in podman-remote that runs on platforms where setting up a development environment is a lot more involved than it is on Linux, and that can be too much for someone to just to be able to answer "does this PR fix it for you?".  Being able to point someone to a functioning binary that was built as part of the CI for that PR would be useful, assuming there is one.

We use Cirrus for buildah CI, and artifacts in the task for https://cirrus-ci.com/task/6125904056287232, for example, are built without Cgo support, since that test is mainly about making sure to Go bits are portable.  Our unshare package requires cgo, and the stub we get without it is not actually functional, so most of the binaries there aren't actually useful.  I haven't looked into how difficult it would be to fix that, but if it's doable, well, we're already saving those binaries.

**Comment by liebig** [comment]
I have created [my own fork](https://github.com/liebig/podman) and have the Linux AMD64 binaries (releases and nightly builds) built here automatically. Maybe [my workflow YAML](https://github.com/liebig/podman/blob/main/.github/workflows/build_linux_nightly.yml) helps with this issue?

**Comment by rhatdan** [comment]
Is this still an issue that anyone cares about?

**Comment by tobwen** [comment]
Of course. Anyone who wants an up-to-date Podman. But I've also created my own workflow...
