### ISSUE TITLE
[RFE] [API] Filter registry searches on supported architecture

### ISSUE THREAD

**Issue by jelly** [containers/podman#13199]
/kind feature

**Description**

Currently when searching for an container image the returned images also return images which do not run on the used architecture. The easiest example is the official `archlinux` image which has no aarch64 support.

**Steps to reproduce the issue:**

1. curl -X GET -s -g --no-buffer --unix-socket /run/user/1000/podman/podman.sock 'http://localhost/v1.12/libpod/images/search?term=docker.io/archlinux&limit=10&listTags=true'

2. curl -X POST -s -g --no-buffer --unix-socket /run/user/1000/podman/podman.sock 'http://localhost/v1.12/libpod/images/pull?reference=docker.io/archlinux'

**Describe the results you received:**

```
[jelle@fedora ~]$ curl -X POST -s -g --no-buffer --unix-socket /run/user/1000/podman/podman.sock 'http://localhost/v1.12/libpod/images/pull?reference=docker.io/archlinux'
{"stream":"Trying to pull docker.io/library/archlinux:latest...\n"}
{"error":"choosing an image from manifest list docker://archlinux:latest: no image found in manifest list for architecture arm64, variant \"v8\", OS linux"}
```

Same for CLI

```
[jelle@fedora ~]$ podman pull archlinux
✔ docker.io/library/archlinux:latest
Trying to pull docker.io/library/archlinux:latest...
Error: choosing an image from manifest list docker://archlinux:latest: no image found in manifest list for architecture arm64, variant "v8", OS linux
```

**Describe the results you expected:**

Podman should filter images based on the host architecture.

**Additional information you deem important (e.g. issue happens only occasionally):**

https://github.com/cockpit-project/cockpit-podman/issues/914

**Output of `podman version`:**

```
podman version 3.4.4
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Raspberry Pi

**Comment by rhatdan** [comment]
@mtrmac PTAL

**Comment by mtrmac** [comment]
The searches, roughly speaking, just return what the registry reports; the registry API doesn’t have any architecture restriction, AFAIK.

So Podman could only inspect the search results one by one, and filter. One can just as well do that with a shell script or other software processing the search results (though enhancing `skopeo inspect` to return easily-digestible information about architectures supported in multi-arch images would certainly help, https://github.com/containers/skopeo/issues/1283 ).

---

It’s also not at all _obvious_ that the search is supposed to be exclusive to the _current_ machine. “Your vendor does provide an image that matches, but it isn’t available for your architecture” can very well be _useful_, whereas just returning nothing may not be.

My first impression is that silently filtering out results would be _very_ unintuitive and surprising.

OTOH adding an arch filter as an opt-in option, off by default, wouldn’t hurt, of course.

---

(Parenthetically, a registry search is… just like a Google search. I wouldn’t recommend running software just because it came up first in search results in either. Figuring out (or negotiating with the author!) which architectures are supported in an image is a very small part of the due diligence I’d expect to be almost always necessary. So I struggle a bit with what the search is for… _maybe_ for a search within a single trusted vendor’s registry, but even in that case one should understand the relevant support/security update timelines.)

**Comment by rhatdan** [comment]
I agree, I don't see this worth changing.

**Comment by gbraad** [comment]
> I don't see this worth changing.

> OTOH adding an arch filter as an opt-in option, off by default, wouldn’t hurt, of course.

Which sounds like a viable alternative, as we did get reports from people downloading `ibmjava` which result in an error. It is shown in the search results of Cockpit, so people have an expectation this would be supported/available.

**Comment by gbraad** [comment]
When you create a container in the Cockpit UI you search for the image and start it:

https://user-images.githubusercontent.com/67428/153281950-4049725a-156c-4cd1-a225-771d4f35eea6.png

and only on the failure of the Download you are informed of a problem. This UI flow is therefore very different from the CLI; instead of a single step to `podman run` you would have performed a 'search' and 'start', which would give more expectation that this should succeed as the 'search' is expected to return only 'compatible' containers, hence the 'arch' predicate makes sense as a possibility.

**Comment by rhatdan** [comment]
Please open a PR to add the filter and option.

**Comment by gbraad** [comment]
@rhatdan very UI unfriendly stance

**Comment by rhatdan** [comment]
Huh?  How I am asking you to open a PR to fix this, if you want the interface.  You can also add the filter to the API.

**Comment by gbraad** [comment]
I can define the interface for you in a PR, but I am pretty sure you know better how to implement this.

**Comment by vrothberg** [comment]
Note that I asked @jelly on IRC to open an issue as I think that search could very well offer this functionality.

**Comment by vrothberg** [comment]
Reopening as I think the conversation was a bit too short.  What I think we can do is to add an option to search to further inspect the images returned from the registry and filter the ones matching the specified/current platform.  Certainly this should be opt-in as it would otherwise be a breaking change _AND_ it can be _very_ expensive to remote inspect the manifest{s, lists} of N images.

**Comment by vrothberg** [comment]
Regarding implementation:
* The gross of the work had to happen in [libimage](https://github.com/containers/common/blob/main/libimage/search.go).
* Once we have received the results from the registries (see https://github.com/containers/common/blob/main/libimage/search.go#L179), we need to have a look at each `libimage.SearchResult.Name` and remote inspect the image.
* [skopeo-inspect](https://github.com/containers/skopeo/blob/main/cmd/skopeo/inspect.go) is a good example of how to inspect an image.

Further notes:
* I think that we should only inspecting image indexes (OCI) or manifest lists (Docker) and check whether there's a manifest item providing the desired platform (arch/os/variant).
* We could also inspect the config of individual images but those are oftentimes wrong. For instance, ARM images oftentimes specify AMD64 in their config.

**Comment by mtrmac** [comment]
Personally I think the whole idea of an UI flow starting with full text search (or regex search? or whatever the registry does) is questionable, but I’ll shut up and I won’t stand in the way if other people want to write that code.

**Comment by rhatdan** [comment]
Since no one ever wrote the code or picked this up, and @mtrmac thought this was questionable, closing.
