### ISSUE TITLE
Can't enter containers permission denied: OCI permission denied 

### ISSUE THREAD

**Issue by InvisibleRasta** [containers/podman#13328]
Fedora 35
I tried first with the fedora 35 repos version  podman 3.4.4-1 and then with  podman 4.0.0-10.fc35.x86_64

`Error: unable to start container "d03e19bcfad2991a9bd4fd5069d8c2148e964f547a1f6c87e01f1c29832448f3": runc: runc create failed: unable to start container process: error during container init: error preparing rootfs: mount /home/user/.local/share/containers/storage/overlay/f28d4e438e68177945fc2750a8ec7dfb2527ee7b68d9aed866ac476b7df5b5f1/merged:/home/user/.local/share/containers/storage/overlay/f28d4e438e68177945fc2750a8ec7dfb2527ee7b68d9aed866ac476b7df5b5f1/merged, flags: 0x5000: permission denied: OCI permission denied`

I also tried this as user
```
~  podman run --rm -ti --ipc host --network host --privileged --security-opt label=disable --user root:root --pid host --userns keep-id --ulimit host --annotation run.oci.keep_original_groups=1 --mount type=devpts,destination=/dev/pts docker.io/archlinux:latest bash
Trying to pull docker.io/library/archlinux:latest...
Getting image source signatures
Copying blob 9ae2c166397c done
Copying blob baca2b2a1f03 done
Copying config 80d141e567 done
Writing manifest to image destination
Storing signatures
Error: runc: runc create failed: unable to start container process: error during container init: error preparing rootfs: mount /home/user/.local/share/containers/storage/overlay/f4aaf8174628f76592d7574d496594a9406b86dd7f98e6f5ee1aec5252442d12/merged:/home/user/.local/share/containers/storage/overlay/f4aaf8174628f76592d7574d496594a9406b86dd7f98e6f5ee1aec5252442d12/merged, flags: 0x5000: permission denied: OCI permission denied 
```

**Comment by mheon** [comment]
Please provide the full output of `podman info`

**Comment by InvisibleRasta** [comment]
```
~  podman info
host:
  arch: amd64
  buildahVersion: 1.24.1
  cgroupControllers:
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.0-2.fc35.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.0, commit: '
  cpus: 12
  distribution:
    distribution: fedora
    version: "35"
  eventLogger: journald
  hostname: fedora
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1001
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.16.9-200.fc35.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 941457408
  memTotal: 16696578048
  networkBackend: cni
  ociRuntime:
    name: runc
    package: runc-1.1.0-1.fc35.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.1.0
      commit: 9ac869a-dirty
      spec: 1.0.2-dev
      go: go1.16.13
      libseccomp: 2.5.3
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /bin/slirp4netns
    package: slirp4netns-1.1.12-2.fc35.x86_64
    version: |-
      slirp4netns version 1.1.12
      commit: 7a104a101aa3278a2152351a082a6df71f57c9a3
      libslirp: 4.6.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.3
  swapFree: 12884893696
  swapTotal: 12884893696
  uptime: 2h 48m 36.59s (Approximately 0.08 days)
plugins:
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
  - quay.io
store:
  configFile: /home/invra/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/invra/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: btrfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 1
  runRoot: /run/user/1000/containers
  volumePath: /home/invra/.local/share/containers/storage/volumes
version:
  APIVersion: 4.0.0
  Built: 1645468298
  BuiltTime: Mon Feb 21 19:31:38 2022
  GitCommit: ""
  GoVersion: go1.16.13
  OsArch: linux/amd64
  Version: 4.0.0
```

**Comment by mheon** [comment]
If you install `crun` and use `--runtime crun` does it work?

**Comment by InvisibleRasta** [comment]
Seems like it is working. Anyway to make crun the default without having to specify it every time?
```
~  podman run --runtime crun -it  docker.io/archlinux:latest bash
[root@c57795cdc87c /]#
```

**Comment by rhatdan** [comment]
You can do this in containers.conf

**Comment by rhatdan** [comment]
Could you check if SELinux AVCs were generated?

**Comment by InvisibleRasta** [comment]
how do i check that?

**Comment by rhatdan** [comment]
Make it fail again then

sudo ausearch -m avc -ts recent

**Comment by InvisibleRasta** [comment]
➜ @fedora  ~  podman run --rm -ti --ipc host --network host --privileged --security-opt label=disable --user root:root --pid host --userns keep-id --ulimit host --annotation run.oci.keep_original_groups=1 --mount type=devpts,destination=/dev/pts docker.io/archlinux:latest bash
Error: crun: make `/home/user/.local/share/containers/storage/overlay/e13933a3f8ed141358e00e79ab18b975c3e02c2751aa55967dcf1c04a0780f46/merged` private: Permission denied: OCI permission denied                                                                                                                    /0.3s
➜ @fedora  ~  sudo ausearch -m avc -ts recent
<no matches>

**Comment by InvisibleRasta** [comment]
I did a "cp /usr/share/containers/containers.conf $HOME/.config/containers/containers.conf" but I am not sure on what to modify
http://sprunge.us/ShRu1D

**Comment by rhatdan** [comment]
```
# Default OCI runtime
#
#runtime = "crun"
```
Uncomment the runtime line.

**Comment by InvisibleRasta** [comment]
podman run -it docker.io/archlinux:latest bash  is working now.

 podman run --rm -ti --ipc host --network host --privileged --security-opt label=disable --user root:root --pid host --userns keep-id --ulimit host --mount type=devpts,destination=/dev/pts docker.io/archlinux:latest bash
Error: crun: make `/home/invra/.local/share/containers/storage/overlay/89d157c9307189f6162a94d5589d8d87ce3604aa5b2042632f68ce3fe2022c8a/merged` private: Permission denied: OCI permission denied

**Comment by giuseppe** [comment]
can you share the content of `/proc/self/mountinfo`?

**Comment by rhatdan** [comment]
Since we got no more feedback, closing.  Reopen if you still want us to work on this issue.

**Comment by rhatdan** [comment]
Not sure what Podman could do to fix this?

**Comment by PavelSosin-320** [comment]
@rhatdan systemd-tmpfiles.conf in /usr/lib/tmpfiles.d used by root contains some lines that protect the Podman's storage in the root mode from been touched by tmpfiles daemon. 
Line 6 in the podman.conf in  podman.conf. 
But tmpfiles unit runs also on every Session login as I see. If user-level tmpfiles configuration for podman is missed mean s that any part of disk space used by Podman in the rootless mode can be managed by tmpfiles daemon randomly, It is good for disk space management per user and security but [tmpfiles conf doc](https://www.freedesktop.org/software/systemd/man/tmpfiles.d.html) is not enough detailed to understand how tmpfiles rules are applied. If mode can be changed on-the-fly "access denied" can happen without any SELinux involvement. Indeed, switching seinforce changes nothing.

**Comment by PavelSosin-320** [comment]
Hm, Podman Podman runtime directory always contains btrfs-locks lock file. Is it OK? When I switch to another user it doesn't disappear and keeps the same owner that created it. It looks strange. I would expect that the lock is cleaned up by tmpfiles daemon because its owner gnome-terminal process is certainly dead.

**Comment by PavelSosin-320** [comment]
This issue looks like hangs but it prevents podman from using in Fedora 36. Just another observation: the AVC error tells that the systemd-journald attempts to access sys_ptrace and blocked. On other hand podman passes to conmon 2 options according to debug log: ol journald and --syslog. When the 1st one results in regular journald log recording the conmon documentation says that the last one will result in writing dumps to syslog but it is impossible userns due to lack of required cap. This is more or less SETroubleshut says me.

**Comment by rhatdan** [comment]
Please show me the AVCs?

**Comment by PavelSosin-320** [comment]
Raw Audit Messages
type=AVC msg=audit(1652897010.86:799): avc:  denied  { sys_ptrace } for  pid=590 comm="systemd-journal" capability=19  scontext=system_u:system_r:syslogd_t:s0 tcontext=system_u:system_r:syslogd_t:s0 tclass=cap_userns permissive=0


@rhatdan 
This is what SELinux troubleshooting shows:
type=SYSCALL msg=audit(1652897010.86:799): arch=x86_64 syscall=readlinkat success=no exit=EACCES a0=ffffff9c a1=7ffc5763db20 a2=55d0dc98daf0 a3=1000 items=1 ppid=1 pid=590 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm=systemd-journal exe=/usr/lib/systemd/systemd-journald subj=system_u:system_r:syslogd_t:s0 key=(null)

type=CWD msg=audit(1652897010.86:799): cwd=/

type=PATH msg=audit(1652897010.86:799): item=0 name=/proc/28238/exe inode=146288 dev=00:17 mode=0120777 ouid=1000 ogid=1000 rdev=00:00 obj=unconfined_u:system_r:**container_runtime**_t:s0 nametype=NORMAL cap_fp=0 cap_fi=0 cap_fe=0 cap_fver=0 cap_frootid=0
P.S. I looked into systemd core dump daemon and reinstalled/rechecked if it is running on my machine. All Kernel, Core dump config files, unit files and activated socket are in the correct place. Maybe, the direct write into core dump files by rootless users is not expected anymore.

Hash: systemd-journal,syslogd_t,syslogd_t,cap_userns,sys_ptrace

**Comment by PavelSosin-320** [comment]
And more: although capsh --print
Current: =
Bounding set =cap_chown,cap_dac_override,cap_dac_read_search,cap_fowner,cap_fsetid,cap_kill,cap_setgid,cap_setuid,cap_setpcap,cap_linux_immutable,cap_net_bind_service,cap_net_broadcast,cap_net_admin,cap_net_raw,cap_ipc_lock,cap_ipc_owner,cap_sys_module,cap_sys_rawio,cap_sys_chroot,cap_sys_ptrace,cap_sys_pacct,cap_sys_admin,cap_sys_boot,cap_sys_nice,cap_sys_resource,cap_sys_time,cap_sys_tty_config,cap_mknod,cap_lease,cap_audit_write,cap_audit_control,cap_setfcap,cap_mac_override,cap_mac_admin,cap_syslog,cap_wake_alarm,cap_block_suspend,cap_audit_read,cap_perfmon,cap_bpf,cap_checkpoint_restore
Ambient set =
Current IAB: 
Securebits: 00/0x0/1'b0 (no-new-privs=0)
 secure-noroot: no (unlocked)
 secure-no-suid-fixup: no (unlocked)
 secure-keep-caps: no (unlocked)
 secure-no-ambient-raise: no (unlocked)
uid=1000(pavelsosin) euid=1000(pavelsosin)
gid=1000(pavelsosin)
groups=10(wheel),1000(pavelsosin)
Guessed mode: UNCERTAIN (0)
crun and conmon have no caps. If all necessary caps are propagated to the OCI runtime?

**Comment by rhatdan** [comment]
Could you attach the output of
sudo ausesearch -m avc

**Comment by PavelSosin-320** [comment]
@rhatdan This is the portion after | grep container:
name=".containerenv" dev="tmpfs" ino=1386 scontext=system_u:system_r:systemd_logind_t:s0 tcontext=system_u:object_r:container_file_t:s0:c757,c967 tclass=file permissive=1
type=PATH msg=audit(1652897010.015:795): item=0 name="/proc/28228/exe" inode=148265 dev=00:17 mode=0120777 ouid=0 ogid=0 rdev=00:00 obj=unconfined_u:system_r:container_runtime_t:s0 nametype=NORMAL cap_fp=0 cap_fi=0 cap_fe=0 cap_fver=0 cap_frootid=0
type=PATH msg=audit(1652897010.016:796): item=0 name="/proc/28229/exe" inode=148269 dev=00:17 mode=0120777 ouid=1000 ogid=1000 rdev=00:00 obj=unconfined_u:system_r:container_runtime_t:s0 nametype=NORMAL cap_fp=0 cap_fi=0 cap_fe=0 cap_fver=0 cap_frootid=0
type=PATH msg=audit(1652897010.017:797): item=0 name="/proc/28230/exe" inode=147244 dev=00:17 mode=0120777 ouid=1000 ogid=1000 rdev=00:00 obj=unconfined_u:system_r:container_runtime_t:s0 nametype=NORMAL cap_fp=0 cap_fi=0 cap_fe=0 cap_fver=0 cap_frootid=0
type=PATH msg=audit(1652897010.086:799): item=0 name="/proc/28238/exe" inode=146288 dev=00:17 mode=0120777 ouid=1000 ogid=1000 rdev=00:00 obj=unconfined_u:system_r:container_runtime_t:s0 nametype=NORMAL cap_fp=0 cap_fi=0 cap_fe=0 cap_fver=0 cap_frootid=0
type=PATH msg=audit(1652897214.508:820): item=0 name="/proc/28752/exe" inode=150403 dev=00:17 mode=0120777 ouid=1000 ogid=1000 rdev=00:00 obj=unconfined_u:system_r:container_runtime_t:s0 nametype=NORMAL cap_fp=0 cap_fi=0 cap_fe=0 cap_fver=0 cap_frootid=0
type=PATH msg=audit(1652897214.527:821): item=0 name="/proc/28759/exe" inode=155768 dev=00:17 mode=0120777 ouid=1000 ogid=1000 rdev=00:00 obj=unconfined_u:system_r:container_runtime_t:s0 nametype=NORMAL cap_fp=0 cap_fi=0 cap_fe=0 cap_fver=0 cap_frootid=0
type=PATH msg=audit(1652941702.993:4717): item=0 name="/proc/54645/exe" inode=451165 dev=00:17 mode=0120777 ouid=0 ogid=0 rdev=00:00 obj=unconfined_u:system_r:container_runtime_t:s0 nametype=NORMAL cap_fp=0 cap_fi=0 cap_fe=0 cap_fver=0 cap_frootid=0
type=PATH msg=audit(1652941702.996:4718): item=0 name="/proc/54646/exe" inode=451170 dev=00:17 mode=0120777 ouid=1000 ogid=1000 rdev=00:00 obj=unconfined_u:system_r:container_runtime_t:s0 nametype=NORMAL cap_fp=0 cap_fi=0 cap_fe=0 cap_fver=0 cap_frootid=0
type=PATH msg=audit(1652941703.001:4719): item=0 name="/proc/54647/exe" inode=451177 dev=00:17 mode=0120777 ouid=1000 ogid=1000 rdev=00:00 obj=unconfined_u:system_r:container_runtime_t:s0 nametype=NORMAL cap_fp=0 cap_fi=0 cap_fe=0 cap_fver=0 cap_frootid=0
type=PATH msg=audit(1652941703.238:4721): item=0 name="/proc/54655/exe" inode=448395 dev=00:17 mode=0120777 ouid=1000 ogid=1000 rdev=00:00 obj=unconfined_u:system_r:container_runtime_t:s0 nametype=NORMAL cap_fp=0 cap_fi=0 cap_fe=0 cap_fver=0 cap_frootid=0

Even redirection  of output > AVCError.txt in my homedir causes Permission denied error. 
Doe SELinux work at all on dynamically mounted filesystems like tmp and home?

**Comment by PavelSosin-320** [comment]
It is not necessary to dig too deep. : wrong parameter is passed to conmon. Podman passes --syslog
_DEBU[0000] /usr/bin/conmon **messages will be logged to syslog** 
DEBU[0000] running conmon: /usr/bin/conmon               args="[--api-version 1 -c 1ae55650cee30350731332132760b1e772b071127d143b79dfed57e517b2fa08 -u 1ae55650cee30350731332132760b1e772b071127d143b79dfed57e517b2fa08 -r /usr/bin/crun -b /home/pavelsosin/.local/share/containers/storage/btrfs-containers/1ae55650cee30350731332132760b1e772b071127d143b79dfed57e517b2fa08/userdata -p /run/user/1000/containers/storage/btrfs-containers/1ae55650cee30350731332132760b1e772b071127d143b79dfed57e517b2fa08/userdata/pidfile -n elated_johnson --exit-dir /run/user/1000/libpod/tmp/exits --full-attach -s -l journald -**-log-level debug --syslog --conmon-pidfile** /run/user/1000/containers/storage/btrfs-containers/1ae55650cee30350731332132760b1e772b071127d143b79dfed57e517b2fa08/userdata/conmon.pid --exit-command /usr/bin/podman --exit-command-arg --root --exit-command-arg /home/pavelsosin/.local/share/containers/storage --exit-command-arg --runroot --exit-command-arg /run/user/1000/containers/storage --exit-command-arg --log-level --exit-command-arg debug --exit-command-arg --cgroup-manager --exit-command-arg systemd --exit-command-arg --tmpdir --exit-command-arg /run/user/1000/libpod/tmp --exit-command-arg --network-config-dir --exit-command-arg  --exit-command-arg --network-backend --exit-command-arg cni --exit-command-arg --volumepath --exit-command-arg /home/pavelsosin/.local/share/containers/storage/volumes --exit-command-arg --runtime --exit-command-arg crun --exit-command-arg --storage-driver --exit-command-arg btrfs --exit-command-arg --events-backend --exit-command-arg journald --exit-command-arg --syslog --exit-command-arg container --exit-command-arg cleanup --exit-command-arg 1ae55650cee30350731332132760b1e772b071127d143b79dfed57e517b2fa08]"
INFO[0000] Running conmon under slice user.slice and unitName libpod-conmon-1ae55650cee30350731332132760b1e772b071127d143b79dfed57e517b2fa08.scope 
[conmon:d]: failed to write to /proc/self/oom_score_adj: Permission denied

DEBU[0000] Received: -1                                 
DEBU[0000] Cleaning up container 1ae55650cee30350731332132760b1e772b071127d143b79dfed57e517b2fa08 
DEBU[0000] Tearing down network namespace at /run/user/1000/netns/netns-13872b40-cd2d-07e7-6ec7-b9c87a2b9aa0 for container 1ae55650cee30350731332132760b1e772b071127d143b79dfed57e517b2fa08 
DEBU[0000] Unmounted container "1ae55650cee30350731332132760b1e772b071127d143b79dfed57e517b2fa08" 
Error: unable to start container "1ae55650cee30350731332132760b1e772b071127d143b79dfed57e517b2fa08": crun: [conmon:d]: failed to write to /proc/self/oom_score_adj: Permission denied_

open executable: Permission denied: OCI permission denied

when conmon cleary states in its help --syslog                     Log to syslog (use with cgroupfs cgroup manager)
If systemd is already in use then using journald and coredumpd sockets  is assumed to **keep podman secure**.
conmon running in the user space has very few chances to write into syslog due to lack of required capability.

**Comment by PavelSosin-320** [comment]
@InvisibleRasta Are you satisfied with this issue status? Please, reopen or send me mail directly to create a new issue. Podman still doesn't work on Fedora 36 modular with Kernel 5.17 after upgrade when podman start command is executed from the gnome-terminal as rootless user. No SeLinux events are registered. Podman info shows that syslog capability is missed when conmon explicitly says that the target of the log is syslog ignoring configuration and passed option. capsh --print from the gnome-terminal shows  that the bash process has syslog capabilities.
It looks like podman,conmon,crun capability  set is too narrow to perform some operations.
