### ISSUE TITLE
Add quiet flag to `containers.StartOptions`

### ISSUE THREAD

**Issue by reavessm** [containers/podman#13504]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

I am writing a golang application application utilizing various podman bindings and I am creating my own UI.  I would like to hide/silence all of podman's messages.  Other operations have a `Quiet` flag (like [PullOptions](https://github.com/containers/podman/blob/33d808108f837e70dc7cc0803bfa4684953fe05e/pkg/bindings/images/pull.go#L61-L65)).  I would like to add a quiet flag to StartOptions to hide this line:

https://github.com/containers/podman/blob/29d7ab3f82e38c442e449739e218349b9a4a16ea/pkg/bindings/containers/containers.go#L204

**Comment by Luap99** [comment]
Assuming you do not use logrus yourself you can use `logrus.SetLevel(logrus.ErrorLevel)` to set the log level higher.

**Comment by vrothberg** [comment]
I agree that using `logrus.SetLevel` is the best way to silence logs.  The `Quiet` flag in pull controls the pull stream, so it's a different kind of log.

**Comment by Luap99** [comment]
I don't think we should close this. IMO we should do not blindly use logrus in the bindings. What if the consumer already uses logus in his code with a log level but do not want the bindings to log or the other way around.

I think we need to give the callers more options to configure this, at least we should use a custom logrus instance instead of the global one.

**Comment by rhatdan** [comment]
Would removing logrus from the bindings be enough?

**Comment by Luap99** [comment]
If we do not want to log anything there, then yes.
