### ISSUE TITLE
Shell completion: date fields: long list of unusable subfields

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#14222]
This seems to be a longstanding issue, unrelated to recent fixes in completion code:
```console
$ bin/podman __completeNoDesc ps --format '{{.Created.' 
{{.Created.wall}}
{{.Created.ext}}
{{.Created.loc.
{{.Created.Add}}
{{.Created.AddDate}}
{{.Created.After}}
{{.Created.AppendFormat}}
{{.Created.Before}}
{{.Created.Clock}}
{{.Created.Date}}
{{.Created.Day}}
{{.Created.Equal}}
{{.Created.Format}}
{{.Created.GobEncode}}
{{.Created.Hour}}
{{.Created.ISOWeek}}
{{.Created.In}}
{{.Created.IsZero}}
{{.Created.Local}}
{{.Created.Location}}
{{.Created.MarshalBinary}}
{{.Created.MarshalJSON}}
{{.Created.MarshalText}}
{{.Created.Minute}}
{{.Created.Month}}
{{.Created.Nanosecond}}
{{.Created.Round}}
{{.Created.Second}}
{{.Created.String}}
{{.Created.Sub}}
{{.Created.Truncate}}
{{.Created.UTC}}
{{.Created.Unix}}
{{.Created.UnixNano}}
{{.Created.Weekday}}
{{.Created.Year}}
{{.Created.YearDay}}
{{.Created.Zone}}
```
(same with `secret ls/inspect`, `volume ls/inspect`, `image`, `events`, and others)

In `ps`, some of those actually work, and others fail with reasonable messages:
```console
$ bin/podman ps --format '{{.Created.UTC}}'
2022-05-11 16:33:53.341353432 +0000 UTC
$ bin/podman ps --format '{{.Created.Minute}}'
33
$ bin/podman ps --format '{{.Created.Zone}}'
Error: template: ps:1:21: executing "ps" at <.Created.Zone>: can't call method/function "Zone" with 2 results
$ bin/podman ps --format '{{.Created.wall}}'
Error: template: ps:1:21: executing "ps" at <.Created.wall>: wall is an unexported field of struct type time.Time
$ bin/podman ps --format '{{.Created.Truncate}}'
Error: template: ps:1:21: executing "ps" at <.Created.Truncate>: wrong number of args for Truncate: want 1 got 0
```
I don't know if it's possible to (programmatically) exclude the nonworking fields. If it's possible, it would make things user-friendlier.

In other podman subcommands, none of the subfields are usable at all:
```console
$ bin/podman secret ls --format '{{.UpdatedAt.Year}}'  (or whatever)
Error: template: list:1:23: executing "list" at <.UpdatedAt.Year>: can't evaluate field Year in type string
```
My uneducated guess is that these could (and should?) easily be fixed to handle date fields more like `ps` by just making a library call or two. But I'm just guessing.

**Comment by Luap99** [comment]
The reason this happens is because the builtin time.Time struct has all these methods. The fact that it also show unexported fields (lowecase) such as `.wall` or `.ext` is new to me. AFAIK reflect cannot access the unexported fields but it looks like there are some special cases where this works?!

Other listed functions accept either arguments which makes then more difficult to use in templates.
If a function returns more than one argument it cannot be used in a template, so in this case it should not be shown. (I just need to figure out how to get this information)

This works for example because Truncate needs one argument:
```
podman ps --format "{{.Created.Truncate 1000000}}" -a
```

**Comment by edsantiago** [comment]
Ah, thanks for the argument-passing explanation. I had tried parentheses, that failed.

This is probably ultra-low priority.

**Comment by edsantiago** [comment]
>If a function returns more than one argument it cannot be used in a template, so in this case it should not be shown. (I just need to figure out how to get this information)

This might not be possible, since some of those multi-value returns can be filtered by other `.Foo` subfields and the completer has no way of knowing. Again, low priority.

**Comment by Luap99** [comment]
If you want to read the official docs for the template syntax: https://pkg.go.dev/text/template

**Comment by Luap99** [comment]
> > If a function returns more than one argument it cannot be used in a template, so in this case it should not be shown. (I just need to figure out how to get this information)
> 
> This might not be possible, since some of those multi-value returns can be filtered by other `.Foo` subfields and the completer has no way of knowing. Again, low priority.

Well I definitely can get this, I know this is a function so reflect should be able to tell me the signature. I could then look a) this function needs at least one argument -> do not add `}}` automatically and b) this function returns more than one, or no argument -> do not show it in the completions.

Also next week is for pet projects, so this is definitely something I am very interested in.

**Comment by edsantiago** [comment]
I'm going to assume that this is the same issue:
```console
$ bin/podman __completeNoDesc ps --format '{{.Size.'
{{.Size.RootFsSize}}
{{.Size.RwSize}}
$ bin/podman ps --size --format '{{.Size.RootFsSize}}'
Error: template: ps:1:18: executing "ps" at <.Size.RootFsSize>: can't evaluate field RootFsSize in type string
```

**Comment by Luap99** [comment]
> I'm going to assume that this is the same issue:
> 
> ```
> $ bin/podman __completeNoDesc ps --format '{{.Size.'
> {{.Size.RootFsSize}}
> {{.Size.RwSize}}
> $ bin/podman ps --size --format '{{.Size.RootFsSize}}'
> Error: template: ps:1:18: executing "ps" at <.Size.RootFsSize>: can't evaluate field RootFsSize in type string
> ```

No this is different, basically we have a `Size()` function which returns a string and a `Size` struct filed which is a struct with the `RootFsSize` and `RwSize` fields. Since the template logic uses the same syntax for methods it cannot differ between these two and use the method instead. Note that you cannot normally define this in go code, this only happens with the embedded structs. I think it will always prefer the not embedded version, in this case the method`

This would be the correct way to get the struct:
```
$ bin/podman ps --size --format {{.ListContainer.Size.RootFsSize}} -a
```

**Comment by edsantiago** [comment]
>This would be the correct way to get the struct:

Okay... but as a very dumb end user, I'm only going by what command-completion suggests. I do not see `.ListContainer` as a suggestion (although once I type it, I get suggestions). It's OK if this is one of those corner cases that can't be fixed, I'm just reporting usability problems that someone may find surprising.

**Comment by Luap99** [comment]
I am not saying you are wrong. The most import rule for me is that the shell completion should never suggest anything that will not work. I can enable `ListContainer` easily but this is also kinda confusing because all fields are already present because it is embedded unless the fields share the name in which case it will conflict.

But since it works in the template it makes sense to show it so I will enable it.
