### ISSUE TITLE
buildkit's --mount - at least ignore

### ISSUE THREAD

**Issue by geoynomous** [containers/podman#14431]
Some of our Dockerfile have

`RUN --mount=type=cache,id=apt,target=/var/cache/apt doFoo` , ie following the [syntax of buildkit](https://github.com/moby/buildkit/blob/master/frontend/dockerfile/docs/syntax.md).

But `podman build` exists with an error when these are present - supporting this functionality would be great - but if this is too complicated, could it at least be ignored - such that the Dockerfiles can be used with docker AND with podman?

/kind feature

**Comment by mheon** [comment]
What Podman version are you using? It was my understanding that 4.1 supports type=cache

**Comment by geoynomous** [comment]
this is the version that comes with alpine 3.15 ... and it somehow does not install 4.1.0 on it ... not sure what I a missing

**Comment by flouthoc** [comment]
> What Podman version are you using? It was my understanding that 4.1 supports type=cache

Yes this is already supported in latest podman. If there is bug could you please open a new issue on buildah repo.

> this is the version that comes with alpine 3.15 ...though there is a package ... https://pkgs.alpinelinux.org/package/edge/community/x86/podman
but it somehow does not install 4.1.0 on it ... not sure what I a missing

Could you try installing by sticking to a package version on alpine ? PS ( not tried this ) : https://superuser.com/a/1058665

I am closing this issue since this feature is already implemented in latest released version of podman and at this current moment issue looks specific to alpine rather than podman but please feel free to continue discussion below.
