### ISSUE TITLE
CLI Flags To Specify Custom Config File Path

### ISSUE THREAD

**Issue by p0da** [containers/podman#14817]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

Currently a number of environment variables are used to specify the custom config file paths (CONTAINERS_CONF, CONTAINERS_STORAGE_CONF, CONTAINERS_REGISTRIES_CONF) would it be possible to consolidate this into a CLI flag format? For example --config, --storage, --registry, etc. An alternative, potentially superior approach, could also be the addition of a --config-dir flag which directs podman to only recognize config files in the specified directory.

**Comment by Luap99** [comment]
The problem with a cli option is that config files (at least containers.conf) are parsed before cli options.
This doesn't necessarily mean that it cannot be implemented but doing so would require big changes.

Is there a specific reason why using environment variables does not work for you?

**Comment by rhatdan** [comment]
We have tried this in the past and end up with a catch-22, which is why we use Environment variables.

**Comment by p0da** [comment]
@rhatdan I understand, as an alternative would it be possible to add an environment variable to force podman to only recognize config files in the specified directory? Similar to the behavior of the --config-dir flag I mentioned previously. This would disable the merging/referencing behavior where instead of searching /usr, then /etc, then $XDG_CONFIG_HOME paths for configs
podman would simply only recognize files in the specific directory.

Having the guarantee that only configuration files in a certain directory are parsed (regardless of the way that the directory is specified) would be immensely useful.

**Comment by rhatdan** [comment]
The problem is Podman is using configuration files from 4 different projects.  containers/storage, containers/image, containers/common and Podman itself.  Not all of the configuration files are in the same directories and are handled the same way.  Your request would need to be in each of the subpackages, and could cause breaking changes. IE XDG_CONFIG_HOME is too generic. CONTAINERS_CONFIG_DIR, might be something we would consider, but you need to get maintainers of containers/image and Storage to agree.
