### ISSUE TITLE
rootless podman with userns=keep-id result with drop all caps

### ISSUE THREAD

**Issue by Tokariew** [containers/podman#14882]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Adding `--userns=keep-id` result with container dropping all caps from rootless container, resulting in some containers to malfunction

**Steps to reproduce the issue:**

1. `podman run -it --rm --name busy busybox`

2. `podman inspect --format="{{.EffectiveCaps}}" busy` Will display list of default capabilities of container

3. kill container and run `podman run -it --rm --name busy --userns=keep-id  busybox`

4. podman inspect --format="{{.EffectiveCaps}}" busy` Will display empty list

**Describe the results you received:**
container lost it default capabilities, in some cases it's needed to re add them to run other containers sucesfully

**Describe the results you expected:**

Adding `--userns=keep-id` don't behave like `--cap-drop=all` 

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
podman version 4.1.1
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.26.1
  cgroupControllers:
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.0-2.fc36.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.0, commit: '
  cpuUtilization:
    idlePercent: 78
    systemPercent: 1.76
    userPercent: 20.24
  cpus: 12
  distribution:
    distribution: fedora
    version: "36"
  eventLogger: journald
  hostname: ryzen.tokariew.xyz
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.18.10-200.fc36.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 1007284224
  memTotal: 33485463552
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: crun-1.4.5-1.fc36.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.4.5
      commit: c381048530aa750495cf502ddb7181f2ded5b400
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.0-0.2.beta.0.fc36.x86_64
    version: |-
      slirp4netns version 1.2.0-beta.0
      commit: 477db14a24ff1a3de3a705e51ca2c4c1fe3dda64
      libslirp: 4.6.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.3
  swapFree: 7620784128
  swapTotal: 8589930496
  uptime: 27h 46m 23.74s (Approximately 1.12 days)
plugins:
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
  - quay.io
store:
  configFile: /home/tokariew/.config/containers/storage.conf
  containerStore:
    number: 1
    paused: 0
    running: 0
    stopped: 1
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/tokariew/.local/share/containers/storage
  graphRootAllocated: 998500204544
  graphRootUsed: 214595084288
  graphStatus:
    Backing Filesystem: btrfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 4
  runRoot: /run/user/1000/containers
  volumePath: /home/tokariew/.local/share/containers/storage/volumes
version:
  APIVersion: 4.1.1
  Built: 1655303518
  BuiltTime: Wed Jun 15 16:31:58 2022
  GitCommit: ""
  GoVersion: go1.18.3
  Os: linux
  OsArch: linux/amd64
  Version: 4.1.1

```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-4.1.1-1.fc36.x86_64

```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

**Comment by rhatdan** [comment]
This looks correct to me.  The default for this container is to run as the UID of the user who launched it.  Since the default user namespace for rootless containers maps the users UID to UID 0 inside of the usernamespace.  And root defaults to get default caps.
$ podman run -it --rm --name busy busybox grep Cap /proc/self/status
CapInh:	0000000000000000
CapPrm:	00000000800405fb
CapEff:	00000000800405fb
CapBnd:	00000000800405fb
CapAmb:	0000000000000000

The --userns=keep-id changes rootless podman user namespace to map the users UID to itself.  Since this user is NOT root, you get no default capabilities, and have to use a setuid program like root to get the binding capabilities.
 
$ podman run -it --rm --name busy --userns=keep-id busybox grep Cap /proc/self/status
CapInh:	0000000000000000
CapPrm:	0000000000000000
CapEff:	0000000000000000
CapBnd:	00000000800405fb
CapAmb:	0000000000000000

If you override the default and tell podman to run as root, then the root process will have the default capabilities.

$ podman run -it --rm --name busy --userns=keep-id --user root busybox grep Cap /proc/self/status
CapInh:	0000000000000000
CapPrm:	00000000800405fb
CapEff:	00000000800405fb
CapBnd:	00000000800405fb
CapAmb:	0000000000000000
