### ISSUE TITLE
`podman network` still mentions CNI in several places

### ISSUE THREAD

**Issue by apollo13** [containers/podman#14990]
Now that we have multiple network backends it might make sense to remove CNI from the help pages:

```
$ podman network create --help|grep CNI
  create CNI networks for containers and pods
$ podman network|grep CNI       
Error: missing command 'podman network COMMAND'
  inspect     Displays the raw CNI network configuration for one or more networks.
$ podman --version
podman version 4.1.1
`

**Comment by Luap99** [comment]
Just want to add that this is not only documentation but also internal code although this is obviously less important to fix.

I feel like we should get at the docs right for v4.2.

**Comment by dilyanpalauzov** [comment]
The `podman.git/cni/` subdirectory explains how to utilize CNI.  https://podman.io/blogs/2022/02/04/network-usage.html says podman has implemented a CNI-alternative, but can still use CNI.

Please document in https://github.com/containers/podman/blob/main/cni/README.md which cniVersion is supported.  [The file ](https://github.com/containers/podman/blob/main/cni/87-podman-bridge.conflist) contains `"cniVersion": "0.4.0"`, but this might be outdated.

**Comment by Luap99** [comment]
Yes we still can use CNI that is fine. But the examples from @apollo13 show that the docs are misleading. It doesn't matter if you use netavark or cni, `podman network create` will create a config file for this backend at the correct location. For podman inspect it is wrong we display a fixed structure and no longer the raw cni config.

We support all cni versions (I think) but the problem is that some distros ship older CNI versions, so we still use 0.4.0 when create cni configs to make them work.

**Comment by dilyanpalauzov** [comment]
> We support all cni versions (I think)

Please document somewhere the supported CNI specification versions.

**Comment by Luap99** [comment]
I am not willing to test all versions so I cannot say if all of them work. We use the go library `v1.1.1` currently and fedora ships `containernetworking-plugins-1.1.0-1.fc36.x86_64` which seems to work at least for the normal podman use cases.
I cannot say anything about other versions.

**Comment by dilyanpalauzov** [comment]
The ` "cniVersion"` parameter indicates the version of the intefrace specification.  The last interface specification is 1.0.0.  A cni plugin can implement more than one specification versions. `containernetworking-plugins-1.1.0-1.fc36.x86_64` means that the plugins version is 1.1.1.  This does not mean, that the CNI-1.0.0-interface specification is utilized.

In any case, there shall be someone who knows which CNI-specification version can be used with podman, which not, and what version is recommended.

**Comment by Luap99** [comment]
My point is that it is impossible for us to test. The Podman team is working on netavark not CNI.
You can test the different versions and submit a PR to document that if you like. We still create 0.4.0 configs with podman network create since 1.0.0 did not work when I added this about a year ago. What CNI versions are supported depends on what version you have installed. We (Podman) have no control over that. We just keep the go library at the latest version, so assuming the CNI authors keep the lib backwards compatible it should work with all versions

Anyway this is completely unrelated to this issue. I recommend to start a [discussion](https://github.com/containers/podman/discussions) there you might get input from others.
