### ISSUE TITLE
Provides binaries on github releases for Release Candidates

### ISSUE THREAD

**Issue by benoitf** [containers/podman#15106]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

Lot of bugs are fixed and new enhancements are coming for 4.2.0 version

And some RC are tagged. But, from end user perspective, I think it's hard to ask people to build from sources.
For example some people may want to experiment the new Windows Installer (.msi) or the macOS installer (.pkg) and it's then hard to get feedback from people if there are no binaries to test

**Describe the results you received:**

Go to the release page of RCs. You only see the tag and have access to .tgz and zip in the assets which is the source code
https://github.com/containers/podman/releases/tag/v4.2.0-rc2

**Describe the results you expected:**
- .msi installer
- pkg installer
- brew package for this specific RC

So it would be then really convenient for people that want to test (from consumer) but not build the project as they might not have any development environment.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
(paste your output here)
```

**Output of `podman info --debug`:**

```
(paste your output here)
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
(paste your output here)
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes/No

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by rhatdan** [comment]
@mheon PTAL

**Comment by mheon** [comment]
In the past, we haven't provided binaries because we only provide remote client binaries on Github, and without an associated Podman server binary they're not really useful. The OS X and Windows binaries, doubly so - we won't have a FCOS image with a Podman server of an appropriate version until some time after the final release.

We could look into providing a static binary of the full Podman client, which would make providing the remote client binaries sensible, but historically there have been significant problems with providing a static version of Podman that includes libpod. @cevich We killed the static build job in CI, right?

**Comment by benoitf** [comment]
@mheon but for example for Windows there were improvements on the installer (it's now using Fedora 36 instead of Fedora35 and with a smaller image) and then people will need to wait 4.2 to try out and then report issues about it while issues could have been fixed during the RC steps.

And for pkg installer as well, we may find some bugs on the artifacts on these RC as well.

**Comment by cevich** [comment]
> We killed the static build job in CI, right?

Ya, it was too complex.  Also I don't understand the difference WRT the golang toolchain.  Otherwise I'm happy to add a static build if somebody can coach me through what's needed.

Also in case it helps:  The CI system continuously publishes binaries for everything that's successfully tested.  There's a static URL for the "latest", as well as one for each (recent) tag and release-branch.  I know at least for Fedora, there's also a COPR repo. with continuous RPM builds on it.  I have no knowledge of windows stuff, other than what we cross-compile for CI (and publish).

**Comment by benoitf** [comment]
@ashley-cui 4.3.0-RC1 has been cut yesterday

but I see no artifacts in the downloads section (except source code)
![image](https://user-images.githubusercontent.com/436777/192559248-be1f12fa-033a-4a9e-bfe7-e5d27c5a82a8.png)

https://github.com/containers/podman/releases/tag/v4.3.0-rc1

I was expecting there the Windows installer, and pkg files no ?

**Comment by ashley-cui** [comment]
The PR just ensures that the pkginstaller is now built in CI which means that anyone can pull them off any build. The artifacts are then downloaded from the CI artifact job and manually uploaded on releases (RC's and regular). I just got this PR merged (after RC1 was cut), so let me build this manually for you for this RC and upload it.

**Comment by benoitf** [comment]
ok I thought CI would upload automatically the artifacts for the pkg, Windows installer

**Comment by cevich** [comment]
Nope, that's not been implemented due to signing-requirements and the difficulty in keeping keys safe.  I opened an RFE issue to make a page w/ links to the current builds out of CI, but they will all be unsigned.

**Comment by benoitf** [comment]
I'm fine if files are unsigned on RC

**Comment by cevich** [comment]
Yep, there are many usage contexts where it's fine.  I just don't want there to be any trust-ambiguity, since those are exceptionally hard problems to "fix" after-the-fact.  Either way, I opened https://github.com/containers/podman/issues/15960 for providing the download URLs.  The URL schema isn't hard to figure out, if you need something now, before someone is able to twiddle the markdown together.

**Comment by ashley-cui** [comment]
Uploaded the msi and the pkgs!

**Comment by benoitf** [comment]
are there some plans to contribute as well the file of the new windows installer binary ? https://github.com/containers/podman/tree/main/contrib/win-installer

**Comment by ashley-cui** [comment]
I can take a look and see what I can do there
