### ISSUE TITLE
podman pull: support decrypting images

### ISSUE THREAD

**Issue by ningmingxiao** [containers/podman#15163]

**Comment by mheon** [comment]
Can you clarify what you're asking? What's the specific Skopeo command you're asking about?

**Comment by ningmingxiao** [comment]
I want podman can auto decrypt an  encrypted image,when use podman run with  an  encrypted image.

**Comment by rhatdan** [comment]
Could you show an example of what is going wrong?

**Comment by vrothberg** [comment]
Skopeo has flags for {de,en}crypting images (e.g.,--encrypt-layer).  Those are currently marked as experimental in Skopeo. @lumjjb @mtrmac what do you think on adding support for that in Podman as well?

**Comment by rhatdan** [comment]
I would think Podman should just handle it when pulling an image,  I would figure if I pull an encrypted image, I would be prompted for the decryption key, and then store the image in containers storage.

Adding a --encrypt flag to podman push, would seem to be a nice enhancement.

**Comment by vrothberg** [comment]
`containers/common/libimage` already supports that, so it would be a Podman-only change.  I do not know whether we want to limit support to the local client or if want to extend it to remote client as well.

**Comment by vrothberg** [comment]
@baude PTAL

**Comment by rhatdan** [comment]
In a perfect world, I would do both, but sending the decryption key in a protocol, might be a bit risky.

**Comment by vrothberg** [comment]
We're sending credentials over the wire as well - I think we assume the connection is secure.  If users opt-out from a secure connection, they probably know what they are doing.

**Comment by lumjjb** [comment]
I'm not sure how this plays into the architecture, but we did a [daemon based configuration](https://github.com/cri-o/cri-o/blob/main/tutorials/decryption.md#configuring-image-decryption-for-node-key-model), with a set of keys for cri-o, not sure how it would map for podman

**Comment by rhatdan** [comment]
The podman service should be able to use that configuration.

**Comment by vrothberg** [comment]
I think we can start with providing keys on the CLI via flags as done in Skopeo.  If there's a need for a permanent configuration, we can look into something similar to the CRI-O configuration.

**Comment by mtrmac** [comment]
For pull, this is just a matter of exposing the options to supply keys.

The current code does not actually allow interactively prompting for keys; software could always read the manifest to see if it contains encrypted layers, and prompt before actually starting a pull, or maybe we could build some interactive callbacks.

But I’m not immediately sold on the interactivity — AFAIK keys are typically not passphrases, so the users would be entering … paths to local files? Possibly using some algorithm prefix syntax or PKCS#11 hardware identification? I vaguely recall containers/ocicrypt is actually a protocol switch over 5 or so very different encryption mechanisms… My intuitive impression with absolutely no data is that using a decryption key would almost never be a _one-time_ operation that warrants interactivity: The key would be provisioned on the relevant computer and then used repeatedly over time. That strongly suggests “non-interactive, possibly only automated” to me.

---

I’d expect push to work just as easily — one thing to check is pushing a Docker-formatted image (because encryption would require conversion to OCI). Reading the code, I think that is supposed to work already, but it would be worth at least a smoke-test.

**Comment by mtrmac** [comment]
> In a perfect world, I would do both, but sending the decryption key in a protocol, might be a bit risky.

Read https://github.com/containers/ocicrypt/blob/main/docs/keyprovider.md#encrpytingdecrypting-examples — the key providing mechanisms are not really designed to be handed off to a different machine.

It’s an interesting thought to take advantage of that, and have the remote server actually provide a specialized “Podman client” key provider; then the remote client would start some kind of “decryption server” that allows using keys remotely, using the actual users’ configuration, and ask the remote server to connect back to the “decryption server” to perform operations. That would allow supporting arbitrary ocicrypt configurations (if that matters), _and_ the actual encryption keys could never leave the client (including possibly being hardware-protected).

But that seems like quite a lot of work for a niche feature. I’d start with just not supporting this on remote. (FWIW signing does not currently support remote either, at least simple signing runs into similar GPG configuration complexity issues, and sigstore will eventually get complex with Fulcio-required interactivity.)

**Comment by rhatdan** [comment]
@ashley-cui PTAL

**Comment by vrothberg** [comment]
I think we can close given https://github.com/containers/podman/pull/16329 added support for it.

**Comment by mtrmac** [comment]
Yes, let’s.
