### ISSUE TITLE
CI: Reevaluate use of Ubuntu

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#15337]
There's a whole swath of tests being skipped on Ubuntu:
* Five because of #15025 
* One because "BFQ scheduler not supported"
* Sixteen because Ubuntu doesn't seem to have SELinux
* Four because "checkpointing broken in Ubuntu 2004, 2104, 2110, 2204, ..."

AIUI the point of using Ubuntu in CI is testing runc + cgroups v1. The point of testing runc + cgroups v1 is because that's what RHEL8 has, and not that many of us enjoy the panic-scrambles when RHEL8 gating tests fail because we haven't actually been testing very much.

This is a place for us to discuss how to improve our coverage.

**Comment by rhatdan** [comment]
I would also add that one reason to run tests on Ubuntu, is that it is the most popular Linux distribution.

We could add RHEL8/Centos 8 Stream Tests for just system tests. The reason we have avoided them is because there could be/will be features that will not work on them that we don't want to break upstream.

**Comment by rhatdan** [comment]
BTW, Having a platform that does test the limited AppArmor support versus SELinux is also a reason to run on Ubuntu.

**Comment by edsantiago** [comment]
We abandoned ubuntu testing over two months ago.
