### ISSUE TITLE
rawhide: storage-opt is doing more permanent clobbering (uidmap)

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#15977]
Followup to #15698.
```console
# podman run --rm --uidmap 0:100:10000 quay.io/libpod/testimage:20220615 date
Wed Sep 28 14:48:41 UTC 2022

# podman --storage-opt=mount_program=/bin/false info &>/dev/null

# podman run --rm --uidmap 0:100:10000 quay.io/libpod/testimage:20220615 date
Error: open /etc in the container: no such file or directory
```
From this point on, nothing will ever work again with `--uidmap`, until `podman system reset`.

podman-4.3.0~rc1-1.fc38.x86_64 , kernel 6.0.0-0.rc7.47.fc38.x86_64 (also 6.0.0-0.rc6.20220922gitdc164f4fb00a.43.fc38.x86_64)

Discovered in [rawhide gating tests](https://artifacts.dev.testing-farm.io/52d9e577-abfc-40c3-a721-56e3e08fd549/work-tests.ymlrwB2Ro/tests-js6wzL/).

**Comment by giuseppe** [comment]
how is it different from #15698?

Setting the `mount_program` is a destructive operation since it changes the way the files are stored in the local storage.  If you are really sure you have not created any image with the `mount_program` set, you can manually reset the status by deleting the file `$GRAPHROOT/overlay/.has-mount-program`.

If we want to test `--storage-opt=mount_program=/bin/false` then we need to make sure we recreate the storage, or use a different storage root for that test.

**Comment by edsantiago** [comment]
We have fundamentally irreconcilable differences that cannot be resolved, so I yield. #15981 (merged) removes my use of `--storage-opt` from system tests. May this issue serve as a warning to other curious humans: NEVER EVER PLAY WITH PODMAN OPTIONS. They may destroy your system in unpredictable ways.
