### ISSUE TITLE
Restrict outgoing network access

### ISSUE THREAD

**Issue by Shubham-Kumar-2000** [containers/podman#16085]
/kind bug

**Description**

I am trying to block internet access from a container i.e.

- Request coming inside the container should work. ( World -> container )
- Request from container to outside world should not work. (Container -> World) ❌ 

**Steps to reproduce the issue:**

1. I tried `--disable-dns` and `--internal`

**Describe the results you received:**

- Requests to domains blocked
- Requests to IP address still working. ❌ 

**Describe the results you expected:**

- Requests to domains blocked
- Requests to IP address blocked.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
4.2.1
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Running on MacOS

**Comment by Shubham-Kumar-2000** [comment]
Even tried with `--subnet 10.1.1.0/24` still was able to ping a server

```bash
$ ping 4..2.2.2 -c 1
> PING 4.2.2.2 (4.2.2.2): 56 data bytes
```

**Comment by Shubham-Kumar-2000** [comment]
Hi I want to understand that if I use `--internal` network.
And I `EXPOSE 3000` port from `Dockerfile`.

Then will I be able to hit the container service using `http://localhost:3000`

@eriksjolund

**Comment by eriksjolund** [comment]
@Shubham-Kumar-2000 If you believe you've found a Podman bug, please provide a full reproducer with for instance a copy-paste of the shell session so that it's possible to see the exact commands that you have run. Specify which of those commands that gave a surprising result. In the new issue template there are some information fields that you've haven't filled out. 

**Output of `podman info`:**
**Package info (e.g. output of `rpm -q podman` or `apt list podman` or `brew info podman`):**

Sorry, I was drifting away from the topic of this GitHub issue myself when I brought up the technology _socket activation_ although it was not mentioned in this GitHub issue.

For question about how Podman is expected to work I think this is a good place to ask 
https://github.com/containers/podman/discussions

**Comment by rhatdan** [comment]
I think the conclusion to this was no issue, so closing.  Reopen if I am mistaken.
