### ISSUE TITLE
Mount by default other directories than the HOME folder when creating machines on macOS

### ISSUE THREAD

**Issue by benoitf** [containers/podman#16447]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

By default, `podman machine init` will mount the `$HOME` folder

I think default, should be the same than on Docker side
https://docs.docker.com/desktop/settings/mac/#file-sharing

>By default the /Users, /Volume, /private, /tmp and /var/folders directory are shared. If your project is outside this directory then it must be added to the list, otherwise you may get Mounts denied or cannot start service errors at runtime.

So for example /tmp should be added as sometimes you experiment to mount something from the tmp folder.

**Steps to reproduce the issue:**

1. podman machine init

2. podman machine -v volume:volume

3.

**Describe the results you received:**

/tmp is not available

**Describe the results you expected:**
/tmp is mounted

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
(paste your output here)
```

**Output of `podman info`:**

```
(paste your output here)
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman` or `brew info podman`):**

```
(paste your output here)
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes/No

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by ashley-cui** [comment]
Okay, I can definitely mount `/Users`, `/private`, and `/var/folders`. 
`/Volumes` fails with a `Too many levels of symbolic links`, as Volumes on Mac is just a symlink to `/` which seems like a bad idea to mount anyway.
`/tmp` fails because the Podman machine uses the `tmp` directory inside the machine and writes content to it on boot, causing the mount to fail. However, on Mac, `/tmp` is symlinked to `/private/tmp` anyway.

Let me know if it's sufficient to just support `/Users`, `/private`, and `/var/folders`.

**Comment by benoitf** [comment]
would be a nice enhancement as I think for example on macOS people start containers mounting stuff mainly from their home folder or /private/tmp

**Comment by ashley-cui** [comment]
Opened a PR that mounts `/Users`, `/private`, and `/var/folders`!

**Comment by ashley-cui** [comment]
Closed via https://github.com/containers/common/pull/1265
