### ISSUE TITLE
Quadlet kube support for HostPort overrides

### ISSUE THREAD

**Issue by alexlarsson** [containers/podman#16595]
I'm not an expert on kubernetes, but it seems like when running in the cloud you wouldn't necessary set a `HostPort=` option in your yaml. Relying rather on other stuff to wire things together. However, once you run that yaml file on a physical node using quadlet, you may very well want to specify a specific port on the host.

It feels like such host-specific changes should go in the .kube file, rather than the yaml file so that the yaml file can be reused as-is from the cloud version. Or maybe we can have two yaml files that get merged? So, one is the additional stuff needed for the host-local options. I'm not sure how this is normally done in openshift.

**Comment by vrothberg** [comment]
There's a notion of services which I think are meant for that in the K8s world.  @umohnani8 WDYT?

**Comment by ygalblum** [comment]
@vrothberg do you mean that Podman had a notion of `services`? Or are you referring to K8S services.

In K8S, you almost never expose the container port on the Host machine, let alone chose a host port for it. Moreover, the Ports list in the Pod spec are more informational than anything else since all ports are open to the Pod network (see [here](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#ports)).

What you would do is create a service that finds its endpoint by matching labels on the Pods. Such service maybe set to be only internal to the Pod network or exposed out of the host. There are different ways of exposing the service, but usually setting the Host port is bad practice since you cannot guaranty that different services will not request the same port.

But, assuming we add this argument, we will need to do some sort of matching because a single pod may have multiple ports open.

**Comment by alexlarsson** [comment]
Yeah, what we want is something that has a similar usecase as the service file. I.e. the redit yaml file itself specifies containerPort:  6379, and when using it in kubernetes you add the service file to tie that to port 6379 in the frontend container, but when used on with quadlet you add some kind of option in the .kube file to tie it to a port on the host.

It could very well be using the same option format as quadlet does for `.container` files. I.e.: `PublishPort=[[ip:]hostPort:]containerPort`.

I wonder if we also need `ExposeHostPort` to publish host port in the container?

**Comment by ygalblum** [comment]
I never use the `expose` option since it doesn't actually opens the port. Following your comment I rerun the documentation and it seems that `expose` is useful only if you use `publish-all` which will publish all `exposed` ports, but will not let you choose a different port on the host. Unless there is another useful use case that I don't know of, not sure we need to support this.

Having said that, we need to keep in mind that `podman kube play` supports a multi document YAML files. As a result, a single call might process multiple deployments or pods. As a result, such a flag will require some matching capabilities to find the correct Pod. Furthermore, different Pods might expose the same container port, so using the `ContainerPort` field might not do.

So, I was thinking about the K8S service objects. Maybe we should add support for Services in `podman kube play` and do a similar matching using labels. Such support will have to be similar to that of `ConfigMap`, i.e. cannot exists standalone. The user will provide the service as part of the same YAML file and `podman` will do the matching between the `service` and the `pod` and then will have the information about the container and host ports to match.

The only time users will not be able to reuse the same YAML file as in K8S is when multiple services expose the same port (works in K8S since each service has its own IP address)

**Comment by rhatdan** [comment]
I would like to keep the simple case and fail in the complex case. That way > 99% users of the tool will just work and then we have to deal with the < 1% case where multiple containers share the same ports.

**Comment by ygalblum** [comment]
The first step for this issue is being handled in #16880
