### ISSUE TITLE
Add actionable step to error message for networking

### ISSUE THREAD

**Issue by DaveJarvis** [containers/podman#16809]
In addition to the following error:

```
error running container: did not get container start message from parent: EOF
Error: building at STEP "RUN apk --update add --no-cache fontconfig curl": failed to read from slirp4netns sync pipe: EOF
```

it would be useful to suggest a fix to the developer. Such as:

> See the --network command-line option for information about providing network access to the container.

It wasn't immediately apparent to me that "slirp4netns sync pipe: EOF" meant that podman couldn't connect to the network.

**Comment by vrothberg** [comment]
Thanks for reaching out, @DaveJarvis!

@giuseppe @Luap99 WDYT?

**Comment by Luap99** [comment]
Please fill out the issue template as requested.

Why do you get this issue in the first place? Is slirp4netns installed, if so what version? Looks like this error comes from buildah and not podman.

We cannot link to flags/options in error messages (in the backend). There are many ways to use buildah/podman, it could be called via go code directly without the buildah/podman cli so showing options names makes no sense to them.
I Think the correct way to handle this in the code would be to wrap the error to add more context, something like this I guess:
```
Error: building at STEP "RUN apk --update add --no-cache fontconfig curl": setup network: failed to read from slirp4netns sync pipe: EOF
```

**Comment by dmdx86** [comment]
Just wanted to drop by and mentioned I banged my head for a few days on this particular error.

Adding “—net host“ to “podman build” is a workaround, but the root cause in my case was that slirp4netns was unable to access /dev/net/tun. Somehow, for unknown reasons, the permissions changed. The non-root user needs read/write access to /dev/net/tun. I did a “chmod a+rw /dev/net/tun”.

Doing an strace -FF on the buildah / podman command led me to this, if /dev/net/tun permissions doesn’t solve it then you’ll want to do the same and figure out why slirp4netns is having a bad day.

**Comment by DaveJarvis** [comment]
> Why do you get this issue in the first place? Is slirp4netns installed, if so what version? Looks like this error comes from buildah and not podman.

I had never even heard of slirp4netns until I ran podman. Asking why the issue happened in the first place is like asking the painting of Mona Lisa whether she prefers bananas over particle accelerators.

Adding "setup network:" doesn't really address the problem I raised because it's not telling the end user how to solve the problem. From my perspective, the network was already set up and working. Pointing the user to the relevant documentation, or telling them how to work around the issue, is much more user-friendly.
