### ISSUE TITLE
bug: podman system reset when CONTAINER_HOST is set

### ISSUE THREAD

**Issue by idesk2596** [containers/podman#16849]
Hi,

`podman system reset` return:
_**Error: cannot use command "podman system reset" with the remote podman client**_

When CONTAINER_HOST is being set with **unix://** which should be referenced as local directive,
same as if CONTAINER_HOST is not set, podman should know that, right?

for example:
CONTAINER_HOST="unix://${XDG_RUNTIME_DIR}/podman4/podman.sock"

podman version: 4.2.1

Thanks.

**Comment by vrothberg** [comment]
Thanks for reaching out, @idesk2596.

This is expected behavior.  The `system reset` command is not supported for remote client.

When the `CONTAINER_HOST` variable is set, `podman` will automatically use that and do REST calls.

**Comment by idesk2596** [comment]
well, this is what I mean, it's not about the CONTAINER_HOST if set or not, you want it to use REST calls (or whatever) if variables start with tcp:// not unix:// . 
starting with unix:// is not remote, so podman  assumption regarding CONTAINER_HOST is wrong.

**Comment by baude** [comment]
@idesk2596 because Podman is not docker and there is no daemon, our world is a little different.  we consider "remote" to be anything that uses the REST APIs regardless of the transport.  your point is correct for docker because they do use the unix transport by default.  we use no transport by default.  I hope that helps?
