### ISSUE TITLE
win10 podman init fail

### ISSUE THREAD

**Issue by luocunhao** [containers/podman#17263]
D:\Users\Downloads>podman machine init --image-path .\fedora-35-x86_64.tar.xz
Extracting compressed file
Importing operating system into WSL (this may take a few minutes on a new WSL install)...
正在导入，这可能需要几分钟时间。
已存在具有所提供名称的分发。
Error code: Wsl/Service/0x800700b7
Error: the WSL import of guest OS failed: exit status 0xffffffff

**Comment by luocunhao** [comment]
"wsl --unregister podman-machine-default" can sovle this problem
but podman init found next :
Extracting compressed file
Importing operating system into WSL (this may take a few minutes on a new WSL install)...
正在导入，这可能需要几分钟时间。
操作成功完成。
Processing fstab with mount -a failed.

Configuring system...
Processing fstab with mount -a failed.

grep: /etc/ssh/sshd_config: No such file or directory
sh: line 1: /etc/ssh/sshd_config: No such file or directory
Error: could not configure SSH port for guest OS: exit status 1

**Comment by rhatdan** [comment]
@n1hility PTAL

**Comment by n1hility** [comment]
Regarding the first error, did you previously install podman machine, and perhaps manually cleanup some files? This could happen if the WSL distro was left around but podman's state files were deleted. Your workaround to manually unregister is the correct action to take.

On the second error, the podman client needs a specially constructed image, it will fail on a stock fedora image. Normally you would not provide an image path unless you needed to make special modifications, or if you don't have network access and would be caching the file. If you don't need to do that you can just omit the --image-path value and it will fetch what it needs. Otherwise, if you are tyring to do specially modified images, they are located here:

https://github.com/containers/podman-wsl-fedora/releases

**Comment by luocunhao** [comment]
done!!!! thanks
I manually download  https://github.com/containers/podman-wsl-fedora/releases/latest/download/rootfs.tar.xz
and podman machine init --image-path .\rootfs.tar.xz

**Comment by n1hility** [comment]
You’re welcome!
