### ISSUE TITLE
[Bug]: OCI permission denied with rootful podman on OpenShift

### ISSUE THREAD

**Issue by Raniz85** [containers/podman#17419]
### Issue Description

When following the [guide for running Podman on Kubernetes](https://www.redhat.com/sysadmin/podman-inside-kubernetes) I run into the following error when trying to run containers:

 > Error: crun: mount `proc` to `/proc`: Permission denied: OCI permission denied

It works if I run this in a kata container via OpenShift Sandboxed Containers.

### Steps to reproduce the issue

Steps to reproduce the issue
1. Set up a new OpenShift dev cluster with CodeReady Containers
2. Deploy the _Rootful Podman without the privileged flag_ example from https://www.redhat.com/sysadmin/podman-inside-kubernetes
3. Try to run any image with Podman in the no-priv-rootful container

### Describe the results you received

Podman pulls the image but fails to run it with the following error:
> Error: crun: mount `proc` to `/proc`: Permission denied: OCI permission denied

### Describe the results you expected

The image should run

### podman info output

```yaml
host:
  arch: amd64
  buildahVersion: 1.28.0
  cgroupControllers:
  - cpuset
  - cpu
  - cpuacct
  - blkio
  - memory
  - devices
  - freezer
  - net_cls
  - perf_event
  - net_prio
  - hugetlb
  - pids
  - rdma
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: conmon-2.1.5-1.fc37.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.5, commit: '
  cpuUtilization:
    idlePercent: 84.46
    systemPercent: 4.93
    userPercent: 10.62
  cpus: 6
  distribution:
    distribution: fedora
    variant: container
    version: "37"
  eventLogger: file
  hostname: podman-no-priv-rootful
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 4.18.0-372.32.1.el8_6.x86_64
  linkmode: dynamic
  logDriver: k8s-file
  memFree: 265007104
  memTotal: 16797020160
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: crun-1.7.2-3.fc37.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.7.2
      commit: 0356bf4aff9a133d655dc13b1d9ac9424706cac4
      rundir: /run/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +LIBKRUN +WASM:wasmedge +YAJL
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_AUDIT_WRITE,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_MKNOD,CAP_NET_BIND_SERVICE,CAP_NET_RAW,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.0-8.fc37.x86_64
    version: |-
      slirp4netns version 1.2.0
      commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
      libslirp: 4.7.0
      SLIRP_CONFIG_VERSION_MAX: 4
      libseccomp: 2.5.3
  swapFree: 0
  swapTotal: 0
  uptime: 0h 42m 55.00s
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
  - quay.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.imagestore: /var/lib/shared
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-1.9-6.fc37.x86_64
      Version: |-
        fusermount3 version: 3.10.5
        fuse-overlayfs: version 1.9
        FUSE library version 3.10.5
        using FUSE kernel interface version 7.31
    overlay.mountopt: nodev,fsync=0
  graphRoot: /var/lib/containers/storage
  graphRootAllocated: 42401247232
  graphRootUsed: 26759946240
  graphStatus:
    Backing Filesystem: overlayfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 2
  runRoot: /run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 4.3.1
  Built: 1668178887
  BuiltTime: Fri Nov 11 15:01:27 2022
  GitCommit: ""
  GoVersion: go1.19.2
  Os: linux
  OsArch: linux/amd64
  Version: 4.3.1
```

### Podman in a container

Yes

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

**Comment by Raniz85** [comment]
I tried running buildah/stable with the same setup and that fails with

> error setting capabilities for process: setting capabilities: operation not permitted

I can get around that, however, by setting `default_capabilities` in _/etc/containers/containers.conf_ to:

```
[containers]
default_capabilities = [
  "CHOWN",
  "DAC_OVERRIDE",
  "FOWNER",
  "FSETID",
  "KILL",
  "NET_BIND_SERVICE",
  "SETFCAP",
  "SETGID",
  "SETPCAP",
  "SETUID",
  "SYS_CHROOT"
]
```

Doing that does nothing for Podman though.

**Comment by giuseppe** [comment]
the reason for that failure is that a `/proc` mount must be fully visible in outer container before another procfs can be done in a user namespace.

So unless you have a way to override the outer container configuration to have a fully visible `proc` mount, the only alternative you can try is to use `--isolation chroot` to the build command.

**Comment by Raniz85** [comment]
Podman doesn't support the `--isolation` parameter and _buildah/stable_ already sets `BUILDAH_ISOLATION` to _chroot_ - which I assume is why that works and not Podman.

How would I go about addressing _a /proc mount must be fully visible in outer container before another procfs can be done in a user namespace_?

**Comment by rhatdan** [comment]
podman build --help | grep isolation
      --isolation type                               type of process isolation to use. Use BUILDAH_ISOLATION environment variable to override. (default "rootless")

I don't know how you specify not to cover /proc in kubernetes.  Perhaps setup /proc:/proc as a volume.

**Comment by Raniz85** [comment]
I'm not building images - I'm trying to run containers using `podman run`.

@rhatdan You're listed as (co-)author on the blog post about running Podman in Kubernetes and apparently got this working. What distribution did you use? Not OpenShift?

**Comment by rhatdan** [comment]
Actually @umohnani8 wrote most of this, and did do it on OpenShift.

**Comment by rhatdan** [comment]
BTW are you using quay.io/podman/stable image for  your testing?

**Comment by Raniz85** [comment]
Yes, I'm using quay.io/podman/stable

I tried mounting /proc using a hostPath mount, but that didn't change anything. Here's my latest attempt:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: podman-no-priv-rootful
spec:
  containers:
    - name: podman-no-priv-rootful
      image: quay.io/podman/stable
      args:
        - sleep
        - infinity
      securityContext:
        capabilities:
          add:
            - SYS_ADMIN
            - MKNOD
            - SYS_CHROOT
            - SETFCAP
      resources:
        limits:
          github.com/fuse: 1
      volumeMounts:
        - name: hostproc
          mountPath: /proc
  volumes:
    - name: hostproc
      hostPath:
        path: /proc
        type: Directory
```

**Comment by giuseppe** [comment]
there is a knob for setting up a fully visible `/proc`, but last time I've checked it is not supported by CRI-O.

**Comment by giuseppe** [comment]
you cannot run containers unless `/proc` is fully visible, that is blocked in the kernel.

I could not find any good documentation about it, b you need to tweak `procMount` and set it to `Unmasked`: https://kubernetes.io/docs/concepts/security/pod-security-standards/#baseline

Unfortunately CRI-O doesn't support it.  @haircommander do you know if there is any plan for supporting it?

**Comment by Raniz85** [comment]
Ok, thanks for the info about that. 

@umohnani8: I guess you had to have done something different to get Podman working on OpenShift?

**Comment by haircommander** [comment]
so ProcMountType can't be specified in Openshift, as it's gated on an [alpha feature gate](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/) and openshift doesn't enable alpha feature gates

**Comment by giuseppe** [comment]
if your container doesn't need access to `/proc` you could try bind mounting an empty directory:

```
$ mkdir empty
$ podman run -v ./empty:/proc ...
```

**Comment by rhatdan** [comment]
BTW We should add ProcMountType support to Podman.

**Comment by Raniz85** [comment]
> if your container doesn't need access to `/proc` you could try bind mounting an empty directory:
> 
> ```
> $ mkdir empty
> $ podman run -v ./empty:/proc ...
> ```

That fails with
> Error: crun: mount `tmpfs` to `dev`: Permission denied: OCI permission denied
unfortunately

**Comment by giuseppe** [comment]
could be hitting a code path where the runtime needs `/proc` mounted.  Could you please show me the full command line?

**Comment by Raniz85** [comment]
Sure.  Here's the pod specification:

<details><pre>apiVersion: v1
kind: Pod
metadata:
  name: podman-no-priv-rootful
spec:
  containers:
    - name: podman-no-priv-rootful
      image: quay.io/podman/stable
      args:
        - sleep
        - infinity
      securityContext:
        capabilities:
          add:
            - SYS_ADMIN
            - SYS_CHROOT
            - SETFCAP
      resources:
        limits:
          github.com/fuse: 1
      volumeMounts:
        - name: hostproc
          mountPath: /proc
  volumes:
    - name: hostproc
      hostPath:
        path: /proc
        type: Directory</pre></details>

And here's the command:

```shell
$ oc exec -it podman-no-priv-rootful -- bash
[root@podman-no-priv-rootful /]# mkdir /tmp/empty

**Comment by giuseppe** [comment]
thanks, I am able to reproduce it.  Unfortunately I don't see a safe alternative to not require `procfs` mounted, some parts of the code could be replaced with the new mount API but I am not sure we'll be able to cover everything.

We need a fully exposed `/proc` before we can mount it in a nested container

**Comment by Raniz85** [comment]
So is there any hope of resolving this and if so, where does the solution lie? Podman or Cri-o?

**Comment by giuseppe** [comment]
The cleanest is to fix it in CRI-O and add support for ProcMountType

**Comment by Raniz85** [comment]
It looks like CRI-O has support for ProcMountType Unmasked: https://github.com/cri-o/cri-o/pull/6025

So it just seems that it doesn't work in OpenShift then?

I've tried to enable that by turning on the ProcMountType feature gate (via https://frasertweedale.github.io/blog-redhat/posts/2023-01-22-openshift-feature-gates.html) but even if my pod launches with 

```yaml
securityContext:
  procMount: Unmasked
```

/proc still contains a bunch of submounts.

<details>
<pre>[root@podman /]# findmnt -R /proc
TARGET                SOURCE               FSTYPE OPTIONS
/proc                 proc                 proc   rw,nosuid,nodev,noexec,relatime
├─/proc/bus           proc[/bus]           proc   ro,nosuid,nodev,noexec,relatime
├─/proc/fs            proc[/fs]            proc   ro,nosuid,nodev,noexec,relatime
├─/proc/irq           proc[/irq]           proc   ro,nosuid,nodev,noexec,relatime
├─/proc/sys           proc[/sys]           proc   ro,nosuid,nodev,noexec,relatime
├─/proc/sysrq-trigger proc[/sysrq-trigger] proc   ro,nosuid,nodev,noexec,relatime
├─/proc/acpi          tmpfs                tmpfs  ro,relatime,context="system_u:object_r:container_file_t:s0:c2,c28"
├─/proc/kcore         tmpfs[/null]         tmpfs  rw,nosuid,context="system_u:object_r:container_file_t:s0:c2,c28",size=65536k,mode=755
├─/proc/keys          tmpfs[/null]         tmpfs  rw,nosuid,context="system_u:object_r:container_file_t:s0:c2,c28",size=65536k,mode=755
├─/proc/timer_list    tmpfs[/null]         tmpfs  rw,nosuid,context="system_u:object_r:container_file_t:s0:c2,c28",size=65536k,mode=755
├─/proc/sched_debug   tmpfs[/null]         tmpfs  rw,nosuid,context="system_u:object_r:container_file_t:s0:c2,c28",size=65536k,mode=755
└─/proc/scsi          tmpfs                tmpfs  ro,relatime,context="system_u:object_r:container_file_t:s0:c2,c28"
</pre>
</details>

**Comment by haircommander** [comment]
so openshift doesn't allow alpha features I believe and ProcMountType is still in alpha https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/

**Comment by patchon** [comment]
Hi, 

And thanks for the great work with Podman, and for filing this issue. 

I wanted to fill in with my findings, as well as some general questions and reasoning around the area "Podman in OpenShift", please advise me to proper discussion forum if this is off-topic, or better discussed elsewhere. 

Background story is that we have a requirement from the developers to be able to **build** and **run** (important) container images in our OpenShift environment. This turned out to be easier said than done, but after fiddlinng around we got it to work according to our needs. 

This sum up is based on a "clean install" of OpenShift 4.12, no manual changes has been done before this. 

So, from what I understand you definitely want to use **/dev/fuse** for the overlay fs for performance. So the first requirement is to get that working. This has been well covered in this issue https://github.com/openshift/enhancements/issues/362#issuecomment-1040664446. And works out of the box according to the instructions from @jacobshivers. Do the following additional steps, 

- Replace the sample pod spec (create a deployment instead), with the following, 

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podman
spec:
  replicas: 1
  selector:
    matchLabels:
      app: podman
  template:
    metadata:
      annotations:
        io.kubernetes.cri-o.Devices: "/dev/fuse"
      labels:
        app: podman
    spec:
      serviceAccountName: podman
      runtimeClassName: fuse
      containers:
        - image: quay.io/podman/stable
          args:
            - sleep
            - "1000000"
          imagePullPolicy: IfNotPresent
          name: podman
          securityContext:
            runAsUser: 1000
```

- Create a service account for podman
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: podman
```

- Create a rolebinding that allows the podman service account to use the anyuid-scc 
```
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: scc-anyuid-podman
rules:
  - apiGroups:
      - security.openshift.io
    resourceNames:
      - anyuid
    resources:
      - securitycontextconstraints
    verbs:
      - use
```

**Issues** 
`Error: crun: mount tmpfs to dev: Permission denied: OCI permission denied`
`Error: crun: mount devpts to dev/pts: Permission denied: OCI permission denied`

```
$ > oc exec $(oc get pods -l app=podman               \
              --field-selector=status.phase==Running  \
              -o custom-columns=POD:.metadata.name    \
              --no-headers) -- bash -c                \
              "mkdir -pv /tmp/proc                   &&  
               podman run -v /tmp/proc:/proc hello-world"

> Resolved "hello-world" as an alias (/etc/containers/registries.conf.d/000-shortnames.conf)
> Trying to pull quay.io/podman/hello:latest...
> Getting image source signatures
> Copying blob 245acfe18b55 done
> Copying config b57184b084 done
> Writing manifest to image destination
> Storing signatures
> Error: crun: mount tmpfs | devpts to dev | dev/pts: Permission denied: OCI permission denied 
```
This is actually SELinux on the worker node stopping us from doing this. As the [blog post](https://www.redhat.com/sysadmin/podman-inside-kubernetes) says, one has to disable SELinux to allow podman to mount needed devices inside the pod "*Disable SELinux: SELinux does not allow containerized processes to mount all of the file systems required to run inside a container. So we need to disable SELinux on the host that is running the Kubernetes cluster.*" 

This seems like unwanted advice, and I'm a little bit surprised to see @rhatdan's name in that article since I once heard a rumour that he fells a tear everytime somebody disables SELinux 🙈. 

Nontheless, we can both verify this and make a policy that would allow it, 

```
$ worker-node > grep denied /var/log/audit/audit.log 
> node=localhost type=AVC msg=audit(1681661964.596:14582): avc:  denied  { mount } for  pid=2037049 comm="3" name="/" dev="tmpfs" ino=15586070 scontext=system_u:system_r:container_t:s0:c2,c28 tcontext=system_u:object_r:tmpfs_t:s0 tclass=filesystem permissive=0
> node=localhost type=AVC msg=audit(1681662148.583:14611): avc:  denied  { mount } for  pid=2040786 comm="3" name="/" dev="devpts" ino=1 scontext=system_u:system_r:container_t:s0:c2,c28 tcontext=system_u:object_r:devpts_t:s0 tclass=filesystem permissive=0
```
- Create SELinux policy and insert it (this should be done via a machineconfig, but for testing lets do it directly)
```
$ worker-node > cat <<EOF >> /tmp/podman.te
module podman 1.0;

require {
	type container_t;
	type devpts_t;
	type tmpfs_t;
	class filesystem mount;
}

#============= container_t ==============

#!!!! This avc is allowed in the current policy
allow container_t tmpfs_t:filesystem mount;
allow container_t devpts_t:filesystem mount;
EOF

$ worker-node > checkmodule -M -m -o /tmp/podman.mod /tmp/podman.te && 
    semodule_package -o /tmp/podman.pp -m /tmp/podman.mod           && 
    semodule -i /tmp/podman.pp
```

- Verify that we can run podman inside the pod, 
```
$ > oc exec $(oc get pods -l app=podman               \
              --field-selector=status.phase==Running  \
              -o custom-columns=POD:.metadata.name    \
              --no-headers) -- bash -c                \
              "mkdir -pv /tmp/proc                   && 
               capsh --print; podman run -v /tmp/proc:/proc hello-world"
> 
> Current: cap_chown,cap_dac_override,cap_fowner,cap_fsetid,cap_kill,cap_setgid,cap_setuid,cap_setpcap,cap_net_bind_service=i
> Bounding set =cap_chown,cap_dac_override,cap_fowner,cap_fsetid,cap_kill,cap_setgid,cap_setuid,cap_setpcap,cap_net_bind_service
> Ambient set =
> Current IAB: cap_chown,cap_dac_override,!cap_dac_read_search,cap_fowner,cap_fsetid,cap_kill,cap_setgid,cap_setuid,cap_setpcap,!cap_linux_immutable,cap_net_bind_service,!cap_net_broadcast,!cap_net_admin,!cap_net_raw,!cap_ipc_lock,!cap_ipc_owner,!cap_sys_module,!cap_sys_rawio,!cap_sys_chroot,!cap_sys_ptrace,!cap_sys_pacct,!cap_sys_admin,!cap_sys_boot,!cap_sys_nice,!cap_sys_resource,!cap_sys_time,!cap_sys_tty_config,!cap_mknod,!cap_lease,!cap_audit_write,!cap_audit_control,!cap_setfcap,!cap_mac_override,!cap_mac_admin,!cap_syslog,!cap_wake_alarm,!cap_block_suspend,!cap_audit_read,!cap_perfmon,!cap_bpf,!cap_checkpoint_restore
> Securebits: 00/0x0/1'b0 (no-new-privs=0)
> secure-noroot: no (unlocked)
> secure-no-suid-fixup: no (unlocked)
> secure-keep-caps: no (unlocked)
> secure-no-ambient-raise: no (unlocked)
> uid=1000(podman) euid=1000(podman)
> gid=1000(podman)
> groups=1000(podman)
> Guessed mode: UNCERTAIN (0)
> 
> !... Hello Podman World ...!
>
>        .--"--.
>       / -     - \
>      / (O)   (O) \
>   ~~~| -=(,Y,)=- |
>    .---. /`  \   |~~
> ~/  o  o \~~~~.----. ~~
>  | =(X)= |~  / (O (O) \
>   ~~~~~~~  ~| =(Y_)=-  |
>  ~~~~    ~~~|   U      |~~
>
> Project:   https://github.com/containers/podman
> Website:   https://podman.io
> Documents: https://docs.podman.io
> Twitter:   @Podman_io

```
**Note**
- Yes, we are using the **anyuid** SCC. 
- Yes, that is a higher privilege than a "normal user".
- Yes, we have a SELinux policy that allows containers which has certain CAPS that allows mounting of **tmpfs** and **pts**.   
- **No**, we are not running the container **as privileged**. 

**Questions**
- Is this approach considers "safe enough" ? I understand that this is up to the organisation to decide, but I just wanted to hear the "general oppinion" about having this specific SELinux policy (and maybe its impact?). If I understand it correctly, you would still need cerrtain CAPS to be allowed to mount these devices into the container. Which in my world would mean that, if you do not have access to use the SCC "anyuid", the SELinux policy wouldn't do anything for you anyway (which is good), since the CAPS won't allow you to even make those necessary syscalls. 

- However, if the above where true, that you would need certain CAPS to do the mounting of the devices that **podman** requires, how come the anyuid SCC in OpenShift doesn't have CAPS specified. This part is a bit confusing to me, since you can clearly see from the output above that I have the caps **cap_setgid**, **cap_setuid** among others. 
```
> oc get scc anyuid
NAME     PRIV    CAPS         SELINUX     RUNASUSER   FSGROUP    SUPGROUP   PRIORITY   READONLYROOTFS   VOLUMES
anyuid   false   <no value>   MustRunAs   RunAsAny    RunAsAny   RunAsAny   10         false            ["configMap","downwardAPI","emptyDir","persistentVolumeClaim","projected","secret"]
```

- Last but not least, I tried to get the pod working without the anyuid SCC, but then got stuck on the 
```
Error: copying system image from manifest list: writing blob: adding layer with blob "sha256:245acfe18b55af92043342552833df42827c0449360e14733fde702121a03583": processing tar file(creating mount namespace before pivot: function not implemented): exit status 1
```
anyone have an input on why that might be, and what specific CAPS that I would need to get by that one. 

I guess the general goal here is to provide a safe way for our developers to **build** and **run** podman containers, in the most secure way possible. And I **think** I'm quite fine with the above approach, but if even possible, I would like to use a specific SCC that only has the *exact* required CAPS (but again, maybe those are the ones we get from the anyuid SCC). 

Thanks again for the great work and support @rhatdan @giuseppe ⭐  
Sorry for the long post, but hopefully we can get some tips, ideas and possible help someone else 🤖 🚀

**Comment by Raniz85** [comment]
@patchon We seem to be in about the same boat.

We've reached about the same conclusion, though we plan on using the Security Profile Operator to create custom SELinux policies for our pods.

Until we get that set up we're running our pods with the spc_t label.

**Comment by patchon** [comment]
> We've reached about the same conclusion, though we plan on using the Security Profile Operator to create custom SELinux policies for our pods.

Oh, didn't know about that one, thanks. 

> Until we get that set up we're running our pods with the spc_t label.

How do you define that the container should use the spc_t label, cant really find it anywhere ? 
I noticed that there was this option in the SCC spec, 
```
seLinuxContext:
  seLinuxOptions:
    type: xx
```
which would allow us to set a specific label on the container which is run under that SCC. 
Thats great because it means that we can create SELinux rules specific to our specific container label, and that should be fine I think. 

Still not sure about why the anyuid-SCC is allowed to execute "podman run" inside the container, but without it I get the `Error: copying system image from manifest list: writing blob: adding layer with blob "sha256:245acfe18b55af92043342552833df42827c0449360e14733fde702121a03583": processing tar file(creating mount namespace before pivot: function not implemented): exit status 1` error. 

Nontheless, this is great progress I think.

**Comment by Raniz85** [comment]
Sorry for the late answer, but you can set the type in the [seLinuxOptions](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.27/#selinuxoptions-v1-core) field in the container's security context:


```yaml
---
apiVersion: v1
kind: Pod
metadata:
  name: podman
spec:
  containers:
    - name: podman
      image: quay.io/podman/stable
      imagePullPolicy: Always
      command: ["sleep", "infinity"]
      securityContext:
        capabilities:
          drop:
            - ALL
          add:
            - SYS_CHROOT
            - SETFCAP
            - SETUID
            - SETGID
        seLinuxOptions:
          type: spc_t
```
