### ISSUE TITLE
[Quadlet] Failed to enable unit: Unit xyz is transient or generated.

### ISSUE THREAD

**Issue by MartinX3** [containers/podman#17567]
### Issue Description

I can't enable the service of my .kube file.

### Steps to reproduce the issue

Steps to reproduce the issue
1. `cp dyndns-https-ip-pod.kube ~/.config/containers/systemd/`
2. `systemctl --user daemon-reload`
3. `systemctl --user enable --now dyndns-https-ip-pod.service`

### Describe the results you received

```
$ systemctl --user enable --now dyndns-https-ip-pod.service
Failed to enable unit: Unit /run/user/1000/systemd/generator/dyndns-https-ip-pod.service is transient or generated.
```

### Describe the results you expected

A working service

### podman info output

```yaml
host:
  arch: amd64
  buildahVersion: 1.29.0
  cgroupControllers:
  - cpuset
  - cpu
  - io
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: /usr/bin/conmon ist in conmon 1:2.1.6-1 enthalten
    path: /usr/bin/conmon
    version: 'conmon version 2.1.6, commit: 158b5421dbac6bda96b1457955cf2e3c34af29bc'
  cpuUtilization:
    idlePercent: 99.7
    systemPercent: 0.12
    userPercent: 0.18
  cpus: 8
  distribution:
    distribution: arch
    version: unknown
  eventLogger: journald
  hostname: backupserver
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.15.94-1-lts
  linkmode: dynamic
  logDriver: journald
  memFree: 31288766464
  memTotal: 33437519872
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: /usr/bin/crun ist in crun 1.8-1 enthalten
    path: /usr/bin/crun
    version: |-
      crun version 1.8
      commit: 0356bf4aff9a133d655dc13b1d9ac9424706cac4
      rundir: /run/user/1000/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /etc/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: /usr/bin/slirp4netns ist in slirp4netns 1.2.0-1 enthalten
    version: |-
      slirp4netns version 1.2.0
      commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
      libslirp: 4.7.0
      SLIRP_CONFIG_VERSION_MAX: 4
      libseccomp: 2.5.4
  swapFree: 67644399616
  swapTotal: 67645722624
  uptime: 4h 32m 14.00s (Approximately 0.17 days)
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries: {}
store:
  configFile: /home/backupserver/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: btrfs
  graphOptions: {}
  graphRoot: /home/backupserver/.local/share/containers/storage
  graphRootAllocated: 1965484457984
  graphRootUsed: 469814861824
  graphStatus:
    Build Version: Btrfs v6.1.3
    Library Version: "102"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 11
  runRoot: /run/user/1000/containers
  transientStore: false
  volumePath: /home/backupserver/.local/share/containers/storage/volumes
version:
  APIVersion: 4.4.1
  Built: 1676117906
  BuiltTime: Sat Feb 11 13:18:26 2023
  GitCommit: 34e8f3933242f2e566bbbbf343cf69b7d506c1cf-dirty
  GoVersion: go1.20
  Os: linux
  OsArch: linux/amd64
  Version: 4.4.1
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

### Additional environment details

Arch Linux on bare metal

### Additional information

```
# ~/.config/containers/systemd/dyndns-https-ip-pod.kube

[Install]
WantedBy=default.target

[Kube]
Yaml=/opt/podman/ServerContainerTemplate/container/services/dynds-https-ip/dyndns-https-ip-pod.yaml

[Unit]
After=network-online.target
Description=HTTPS & DynDNS support
Wants=network-online.target
```

**Comment by rhatdan** [comment]
@ygalblum PTAL

**Comment by MartinX3** [comment]
Ah I think I misunderstood the meaning of this error.
So if I understand it correctly it's enough to just `start` the service and the `[Install]` section will start it on the system boot?

Then probably the podman quadlet manual needs a hint / update?

**Comment by ygalblum** [comment]
From the added section to the first answer in this issue: https://unix.stackexchange.com/questions/354681/init-service-failing-to-enable-once-a-systemd-service-file-is-generated I understand that generated unit files are not meant to be enabled on their own but instead be enabled using a target in the `Install` section. If my understanding is correct, this aligns with @MartinX3's comment.
@alexlarsson is our understanding correct?

**Comment by MartinX3** [comment]
Oh, according to your link even generated systemD services should be able to get enabled if they have an install section.

**Comment by alexlarsson** [comment]
It is not possible to enable a generated service yes, because they are in general not persistent identifiers. In the case of quadlet, the generator itself handles enabling though, so if the `*.container` file has an [Install] section, the correct links will be generated to automatically start the service.

In other words, it is like the enable is run automatically.

**Comment by alexlarsson** [comment]
So, in the example above, which has an Install section in the .kube file, you need only install the file and start it. It will be automatically enabled and started next boot.

**Comment by MartinX3** [comment]
Thank you very much.
I think the man page should get extended to contain a hint.

**Comment by ygalblum** [comment]
This means that the user must link the service to another service or target, right? What would be the best practice here?

**Comment by alexlarsson** [comment]
@ygalblum What do you mean?

**Comment by ygalblum** [comment]
@rhatdan 
IIUC:
1. In order for Quadlet to "enable" the service, the `.kube` file must include an `Install` section. 
2. Enabling a service does not start it until reboot. So, if you want to start it without rebooting, you need to explicitly call `syatemctl start`. So, if you reboot immediately, you don't need to start it manually.
@alexlarsson 
My question was about how we would document it. Since the user cannot enable the service by calling `systemctl enable` she will have to set the `Install` section. This means that the service will be attached to the start sequence of a different service or target, but never on its own. Am I correct? Is there a way to make it standalone (i.e. add a dummy service that will be set as WantedBy in the Quadlet one)?

**Comment by alexlarsson** [comment]
@rhatdan Sort of. If you reboot you need only 1, but if you also want to run the service before rebooting you also need 2-3.

**Comment by rhatdan** [comment]
Ok so the docs should be stated that moving the unit file into the appropriate directory is equivalent of an enable service.
IE If the machine reboots after the file was moved in place, the service will be started.

If you want to start the service without reboot, then  you need to do

systemctl daemon-reload
systemctl start $NAME.service

**Comment by alexlarsson** [comment]
> My question was about how we would document it. Since the user cannot enable the service by calling systemctl enable she will have to set the Install section. This means that the service will be attached to the start sequence of a different service or target, but never on its own. Am I correct? Is there a way to make it standalone (i.e. add a dummy service that will be set as WantedBy in the Quadlet one)?

Lets take a step back. For a normal unit, if there is a section in the foo.service file like:
```
[Install]
WantedBy=default.target
```
Then nothing happens initially, and the unit only starts if you manually start it, or some other service depends on it.

However, when you run `systemctl enable foo.service` on the unit, systemd reads the `Install` section and applies it. In this case it will create a symlink `.../default.target.wants/foo.service` -> `.../foo.service`.

This means that on startup, the service will be started (because default.target is part of a normal boot). This is just how systemd works, nothing specific to quadlet. 

However, `systemctl enable` doesn't work for a generated file, so you can't run `systemctl enable` on the service generated by quadlet. For this reason, the quadlet generator does the equivalent of `systemctl enable`at boot. I.e. creates the required symlinks.

So, yes, this means that the quadlet unit needs to `be attached to the start sequence of a different service or target`, but that is true for any unit file, quadlet or not. And they way this is fixed is to use the standard targets like "default.target" or "graphical.target", etc.

**Comment by ygalblum** [comment]
Thanks for the explanation. I did not how the `Install` part works.

Now, I'm trying to think about different use cases. 

Let's assume I have a service that I want to distribute without enabling it by default. But, I want to allow the user to be able to enable it whenever they want to. How will I, as the writer and distributor or the `.container` file, do that?
Not include an `Install` section? If so, then I need to explain the user that they need to add the section themselves in order to enable it. Is that right?
Alternatively, should the unit file have a key for auto-enable? It will still require the user to edit the file in order to have Quadlet enable the service, but one that is easier to explain.

WDYT?

**Comment by alexlarsson** [comment]
Yeah, shipping a non-enabled file currently means no install section.
We could have an option to disable the automatic apply of the install section, but then nothing can read it (because systemctl enable on the generated file doesn't work), so as you say, users would have to edit the file to enable it. Alternatively we could maybe have a `.d` style support in the generator where we can add the install snippet in a separate file (which you can chose to install or not).

**Comment by alexlarsson** [comment]
Another option would be to have a `podman quadlet enable foo.container` thing that parses the otherwise disabled Install section and creates the right symlinks. That might work.

**Comment by ygalblum** [comment]
I think we should combine the discussions between #17662 and #17567. So, I opened a new discussion #17744

**Comment by ygalblum** [comment]
We're waiting for a response from the systemd team. In any case, this issue is now being tracked in #17744 and therefore, I'm closing this one
