### ISSUE TITLE
Downloading VM image console lines are censored to chars followed by ellipsis

### ISSUE THREAD

**Issue by ssbarnea** [containers/podman#17718]
### Issue Description

Maybe someone can explain the reasoning behind what looks like an anti-feature logging feature where podman cuts every character after 60th and appends ellipsis ('...'):

```
Downloading VM image: fedora-coreos-37.20230303.2.0-qemu.x8…
Downloading VM image: fedora-coreos-37.20230303.2.0-qemu.x8…
Downloading VM image: fedora-coreos-37.20230303.2.0-qemu.x8…
Downloading VM image: fedora-coreos-37.20230303.2.0-qemu.x8…
Downloading VM image: fedora-coreos-37.20230303.2.0-qemu.x8…
```

### Steps to reproduce the issue

See https://github.com/ansible/vscode-ansible/actions/runs/4366041564/jobs/7635510663#step:9:34

### Describe the results you received

Describe the results you received

### Describe the results you expected

No censoring

### podman info output

```yaml
podman 4.4.2
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by viplifes** [comment]
I have same problem.

I need detect progress in my nodejs app.

Podman set default Width=60
https://github.com/containers/podman/blob/060c125b783f1f6202e1646426f718469cb2720d/pkg/machine/pull.go#L170

mbp detect terminal width here
https://github.com/vbauerster/mpb/blob/60781358ad4ecc6acbc48a7a709e482d25e2ce19/cwriter/writer_posix.go#L37

When i spawned command **podman machine init**, mbp cannot detect width, because nodejs not set tty for detect width
