### ISSUE TITLE
Running "podman images" and "podman images -a" is very slow

### ISSUE THREAD

**Issue by 125priyank** [containers/podman#17828]
### Issue Description

Running the `podman images` and `podman images -a` command takes a very long time.

### Steps to reproduce the issue

Steps to reproduce the issue
1. Build some images
2. Run `time sudo podman images -a` or `time sudo podman images`
3. Notice that it takes a very long time.

### Describe the results you received

On a machine with many images, it takes 27 seconds.
```
time sudo podman images
docker.io/library/artools-ishwar.naik.replayprotarfa.0-x86_64_el7                              30921136    237fa8736bf5  9 days ago     1.45 GB
docker.io/library/artools-snalagatla.sfeabuild.0-x86_64_el7                                    30921088    c49b1a3864ee  9 days ago     1.45 GB
docker.io/library/artools-saibhargav.addhwrouting.1-x86_64_el7                                 30918479    ae8302872fcd  9 days ago     1.45 GB
…(I have truncated the output, all 546 images are similar to above)
real    0m26.945s
user    0m53.624s
sys     0m5.651s
```

sudo podman images -a was too bad, it took 10 minutes
```sudo podman images -a
real    10m1.009s
user    21m42.792s
sys     0m51.298s
```

### Describe the results you expected

Something that is a lot faster. Definitely less than or around a second.

### podman info output

```yaml
sudo podman info --debug
host:
  arch: amd64
  buildahVersion: 1.29.0
  cgroupControllers:
  - cpuset
  - cpu
  - io
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.2-2.el9_0.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.2, commit: e0466536503076007df1019612603730e4fcecf4'
  cpuUtilization:
    idlePercent: 88.15
    systemPercent: 1.69
    userPercent: 10.16
  cpus: 24
  distribution:
    distribution: '"almalinux"'
    version: "9.0"
  eventLogger: journald
  hostname: mock109.sjc.aristanetworks.com
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.10.62-30605143.AroraKernel510.el7.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 172953657344
  memTotal: 270364069888
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: crun-1.4.5-2.el9_0.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.4.5
      commit: c381048530aa750495cf502ddb7181f2ded5b400
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_NET_RAW,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /bin/slirp4netns
    package: slirp4netns-1.2.0-2.el9_0.x86_64
    version: |-
      slirp4netns version 1.2.0
      commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.2
  swapFree: 0
  swapTotal: 0
  uptime: 152h 3m 53.00s (Approximately 6.33 days)
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - registry.access.redhat.com
  - registry.redhat.io
  - docker.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphRootAllocated: 5330653462528
  graphRootUsed: 132277952512
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 10310
  runRoot: /run/containers/storage
  transientStore: false
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 4.4.0
  Built: 1675439377
  BuiltTime: Fri Feb  3 07:49:37 2023
  GitCommit: ""
  GoVersion: go1.19.4
  Os: linux
  OsArch: linux/amd64
  Version: 4.4.0
```
```


### Podman in a container

No

### Privileged Or Rootless

Privileged

### Upstream Latest Release

Yes

### Additional environment details

_No response_

### Additional information

The command `sudo podman images` takes so much time when the number of images is high, for a small number of images it is okay.

**Comment by Luap99** [comment]
@vrothberg @mtrmac Ideas?

I remember issues like that in the past, something related to calculating the image size which is displayed.
@125priyank Can you run `podman --cpu-profile images.pprof images` and upload the `images.pprof` profile here. This should show us where most of the time is spend.

**Comment by 125priyank** [comment]
[images.zip](https://github.com/containers/podman/files/11002273/images.zip)
It contains two files - 
1) images - `podman --cpu-profile images.pprof images`
2) images(-a) - `podman --cpu-profile images.pprof images -a`

**Comment by mtrmac** [comment]
> ```
>   imageStore:
>    number: 10310
> ```

That’s _quite a bunch_ of “some images”, though, of course, a quite legitimate thing to do.

I wouldn’t at all be surprised to find some O(N^2) algorithm, or worse, in there; sadly Go’s profiles don’t show call counts.

---

The profile shows things like `github.com/containers/podman/vendor/github.com/containers/storage.(*layerStore).ReloadIfChanged`, which is no longer present in 4.4.0.

So I would very strongly suggest updating to at least 4.4.0, and measuring that; the backing storage implementation has changed quite significantly, possibly in relevant ways, and if we are going to make performance improvements, it’s most likely to happen on the current development version, not an older one.

---

One fairly clearly O(N^2) hotspot is https://github.com/containers/podman/blob/f1bcd0d78176d4e23cedbef2fd2a26c8b601a828/pkg/domain/infra/abi/images_list.go#L33 and https://github.com/containers/podman/blob/f1bcd0d78176d4e23cedbef2fd2a26c8b601a828/pkg/domain/infra/abi/images_list.go#L70 : this builds a `layerTree` (which is _at least_ O(layers + images)) on each call. Building a layer tree once, and using it for all parent lookups, should make a lot of difference.

The building of `layerTree` is > 87% of the total time in `images -a`.

---

(In the extreme, a single `layerTree` should be used for _all_ operations while listing images; including the filtering that happens without `-a`, and the parent/child lookups. That would require a fairly extensive refactoring.)

---

(It might also be interesting to build an `imageTree` with all parent/child relationships at once. There are several places that query the same parent/child relationship about an image, and computing+recording them all might be possible to do more efficiently, by _somehow_being smart about a bunch of images with related top layers and splitting them in relevant sets/relationships instead of testing most pairs with `areParentAndChild`. Whether this is worth it very much depends on the shape of the layer/image tree.)

---

A fairly significant hotspot (but not nearly as important as the `Parent` call) is `libimage.Image.ToOCI`, which calls `storageReference.NewImage()`, and and 69% of _that_ is spent computing the image size which the caller doesn’t care about.

So that `.NewImage()` call (and maybe various other calls throughout the Podman codebase) can be replaced by
```go
src := ref.NewImageSource(…)
defer src.Close()
img := image.FromSource(…, src)
```
That should be a fairly easy (linear) win.

---

It turns out we unmarshal the same image manifest _three_ times when fetching it from storage:
- For `GuessMIMEType`
- For validating that the manifest is not ambiguous / an attack
- To actually extract the data.

That might be eventually fixable, but it would be quite invasive. The `GuessMIMEType` part, at least, could probably be entirely eliminated by storing a MIME type in c/storage metadata.

**Comment by rhatdan** [comment]
@nalind @vrothberg FYI

**Comment by vrothberg** [comment]
> this builds a layerTree (which is at least O(layers + images)) on each call. Building a layer tree once, and using it for all parent lookups, should make a lot of difference.

That is very likely the bottleneck.  Building the layer tree is really expensive.

**Comment by 125priyank** [comment]
Tried podman 4.4.0 as you mentioned
```
sudo podman version
Client:       Podman Engine
Version:      4.4.0
API Version:  4.4.0
Go Version:   go1.19.4
Built:        Fri Feb  3 07:49:37 2023
OS/Arch:      linux/amd64
```

The time has worsened though the number of images remained same
```
time sudo podman images

real    0m27.181s
user    0m53.942s
sys     0m5.774s
```

Output of `sudo podman --cpu-profile images.pprof images`
[images (1).pprof.zip](https://github.com/containers/podman/files/11015483/images.1.pprof.zip)

**Comment by vrothberg** [comment]
@mtrmac @rhatdan I opened https://github.com/containers/common/pull/1372 as an RFC to address the issue.  I prefered caching over exposing the `layerTree`.
