### ISSUE TITLE
reading manifest latest in docker.io/ubi8/php-80: requested access to the resource is denied

### ISSUE THREAD

**Issue by ryannix123** [containers/podman#17926]
### Issue Description

I'm trying to pull an image from my macOS based system, but I get following error:

Run: `podman pull ubi8/php-80`

Error:
Resolving "ubi8/php-80" using unqualified-search registries (/etc/containers/registries.conf.d/999-podman-machine.conf)
Trying to pull docker.io/ubi8/php-80:latest...
Error: initializing source docker://ubi8/php-80:latest: reading manifest latest in docker.io/ubi8/php-80: requested access to the resource is denied

### Steps to reproduce the issue

Steps to reproduce the issue
1. On a macOS based system running Podman 4.4.2, run `podman pull ubi8/php-80`
2. I get a message: `Resolving "ubi8/php-80" using unqualified-search registries (/etc/containers/registries.conf.d/999-podman-machine.conf)`
3. I'm logged into Quay, Registry.redhat.com, Docker Hub, and Github

### Describe the results you received

```
podman pull ubi8/php-80
Resolving "ubi8/php-80" using unqualified-search registries (/etc/containers/registries.conf.d/999-podman-machine.conf)
Trying to pull docker.io/ubi8/php-80:latest...
Error: initializing source docker://ubi8/php-80:latest: reading manifest latest in docker.io/ubi8/php-80: requested access to the resource is denied
```

### Describe the results you expected

Should be able to pull down image, especially if I'm logged into each Docker registry.

### podman info output

```yaml
If you are unable to run podman info for any reason, please provide the podman version, operating system and its version and the architecture you are running.
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by vrothberg** [comment]
Thanks for reaching out, @ryannix123!

The correct reference is `registry.access.redhat.com/ubi8/php-80:latest`.  The issue is that you are pulling the image by short name (i.e., without a registry).  That means that Podman has to "guess" where the image lives.  For `podman machine` (i.e., Podman on Windows and Mac), the default registry is `docker.io`.  That's why you get the error: Podman tries to pull the image from `docker.io` but it does not exist there. Docker would also fail to pull the image.

Hence, to resolve your issue, you need to use the fully qualified image reference mentioned above.

> Should be able to pull down image, especially if I'm logged into each Docker registry.

Being logged into a registry relates to authentication, such that your saved credentials are automatically used by Podman when communicating with the registry.  It does not affect how short names are resolved.
