### ISSUE TITLE
idmapped mounts constantly break

### ISSUE THREAD

**Issue by namazso** [containers/podman#18102]
It is the second time in a month my containers break due to breaking changes to how idmapped mounts work between two minor versions. First was when the order was swapped for the idmap parameter, and I haven't yet found what's the new one (edit: it's a swap again 🤦‍♂️).

Is podman supposed to be only a developer tool, not usable for any sort of production-like workload? Or are some options not covered by some stability guarantee?

**Comment by rhatdan** [comment]
No but idmapping just showed up in the kernel, and is highly experimental at this point. Does not work in rootless mode and does not work on some platforms.  Perhaps mistakes were made while attempting to implement it.
@giuseppe PTAL

**Comment by giuseppe** [comment]
the issue was caused by a breaking change in crun: https://github.com/containers/crun/pull/1147

It really depended on a disagreement since it was not clearly specified in the OCI specs and crun implemented it first.  After a discussion with the runc developers we decided to flip the way crun was doing it since it simplifies the implementation for the container engine: now Podman can specify the same mappings for the user namespace and the idmapped mounts without having to worry to switch them.
