### ISSUE TITLE
Quadlet support depending on health conditions for container

### ISSUE THREAD

**Issue by Lunarequest** [containers/podman#18189]
### Feature request description

Docker compose has a detective `depends_on` which can be used to depend on containers in a compose stack and wait to start containers that use this until the health check passes, if they don't the service is not started. An example would be

```yaml
depends_on:
      db:
        condition: service_healthy
```

Any container in the compose file with this directive will not start until a container named db starts and has a healthy condition, this is useful for things like postgres which take a bit to start up at which point other services that depend on it may fali as postgres hasn't started up.

### Suggest potential solution

I would like a directive under `[Container]` that mirrors the depends_on field maybe
```ini
[Container]
DependsOn=name.container@healthy
```
where `@healthy` refers to the condition

### Have you considered any alternatives?

I have considered add bash to my container and writing a shell script to wait for the db to come up but I would rather not as my container currently is extremely small and has no shell nor coreutils.

**Comment by rhatdan** [comment]
Wouldn't the systemd way of doing this be just to define a depend relationship between the containers and have the "depended On" container as a notify socket, and wait to notify that the is ready.

**Comment by vrothberg** [comment]
Cc: @ygalblum @alexlarsson

**Comment by ygalblum** [comment]
In the Quadlet demo, I set the dependency between the WP application `.kube` and the service created for the mysql `.container` file in the `.kube` file: https://github.com/ygalblum/quadlet-demo/blob/main/quadlet-files/quadlet-demo.kube#L5. So, users should be able to set this dependency on their own without needing Quadlet to translate.

Having said that, this means that the naming pattern of the `.service` files must be guaranteed and cannot be changed in later versions as it will break such dependency

**Comment by Lunarequest** [comment]
still important

**Comment by rhatdan** [comment]
@Lunarequest you never responded to @ygalblum comment.

**Comment by Lunarequest** [comment]
ah my bad I didn't know i needed to respond. I wanted some way to do a health check specifically as some services eg postgres on init can take  a very long time to fully start up which can lead to other services which depend on this service to crash despite it to podman looking like the service has started

**Comment by ygalblum** [comment]
@Lunarequest thanks for the added info. I understand the requirement, but I'm not sure that Quadlet is the answer here.

At the end of the day, Quadlet is a systemd generator that links between podman commands (run, kube play) and systemd and does not have a life of its own. So, in order to add such dependency management, we need to understand how it can be achieved by using only systemd and podman.

Systemd can (and should) be used for dependency management making sure that before starting the dependent service  the service on which it depends is running. Now comes the question of what does it mean that the service is running.
If it's the mere start of the container, then it's simple (and shown in my demo). But, if we want to make sure that the service has reached a certain state we will need podman to hold off notifying systemd that the service is in fact running until health-startup is successful.
Having said that, assuming I read the code correctly, it seems that podman [emits the notification](https://github.com/containers/podman/blob/main/libpod/container_internal.go#L1235) before [scheduling the startup health check](https://github.com/containers/podman/blob/main/libpod/container_internal.go#L1255).

@rhatdan, @vrothberg WDYT?

**Comment by ygalblum** [comment]
@vrothberg I see that you've just commented on #6160. Isn't this exactly what we are talking about here?

**Comment by vrothberg** [comment]
@ygalblum, yes, I think so.  We need to get https://github.com/containers/podman/issues/13627 done to make a `podman wait --condition=healthy` work.  This would allow this request and for implementing the `--sdnotify=healthy` one.

**Comment by ygalblum** [comment]
@vrothberg since #13627 is done, can we start looking at `--sdnotify=healthy`?

**Comment by rcasta74** [comment]
This request looks similar to what I need, so I'm asking here before to open a potential duplicated issue.

I have initially created a pod manually and I have attached several containers to it; with `run`/`create` commands I was able to use `--requires` option to define dependencies between containers.
When I have later redefined my containers in a yaml file to be used in a `.kube` systemd unit, I missed this feature.
Could this feature request apply to my use case as well?

**Comment by rhatdan** [comment]
Does kube yaml have this type of functionality?  Init containers?

**Comment by rcasta74** [comment]
As per my understanding, init containers work differently, so that standard containers won't start until init containers are done.
What I need is to be able to start a container after that another one is already started.

For example when I have created my containers manually, I have created a pod X, than I have created a container A with `--pod=X` and container B with `--pod=X --requires=A`. When starting pod X, container B was always started after container A.

My question is whether it is possible to make `podman kube play` to create containers with option `--requires` in the same way I can do when I create them manually.

**Comment by rcasta74** [comment]
Just found out that a new feature for init containers have been recently released on kubernetes side ([Sidecars containers](https://github.com/kubernetes/enhancements/blob/0a6d6c888298c4381d3bedd2134a2e8ec098cab3/keps/sig-node/753-sidecar-containers/README.md)).
Is there a plan to support it on podman as well?

**Comment by rhatdan** [comment]
@ygalblum @umohnani8 PTAL

**Comment by nogweii** [comment]
I think everything exists in Podman now except for the glue to expose this as a capability inside a `.container` unit. Looking [at the code](https://github.com/containers/podman/blob/b44d372b1b86f765c3aec0593ed826fc7d0f0e44/pkg/systemd/quadlet/quadlet.go#L491), quadlet currently treats the `Notify=` option as a boolean.

I'd like to see it be expanded to a trinary value:

* `true`/`false` - keeps their current meaning
* `healthy` - sets `--sdnotify=health` which means other systemd units that depend on this one would be blocked until the healthchecks pass

**Comment by rhatdan** [comment]
Could you open a PR to make that change?

**Comment by deuill** [comment]
Gave this a go in #20714 since I'm using Quadlet with `--sdnotify=healthy` quite extensively on [my side](https://github.com/deuill/coreos-home-server).
