### ISSUE TITLE
[SLURM, rootless] Is it possible to build/load an image on a login node and run it on a compute node?

### ISSUE THREAD

**Issue by MaximilienLC** [containers/podman#18223]
I've been unable to run (on the compute node) images loaded/built on the login node. Running `podman image ls` throws out an `Error: error creating tmpdir: mkdir /run/user/3067323: permission denied` (which does not happen if the image folder is wiped clean). I've tried moving the image folder (graphroot through storage.conf) from `~` to `/scratch` but the error sticks.

Thanks!

**Comment by Luap99** [comment]
Do you copy the full graphroot to a different system? This is not going to work because podman caches paths in its boltdb database. You should use podman save/local to transfer images or just use a registry. If you 100% know that you only copy images you could try to delete the boltdb at `~/.local/share/containers/storage/libpod/bolt_state.db`.

**Comment by MaximilienLC** [comment]
I don't copy anything, I just tried changing its location through `storage.conf` in a naive attempt to solve my problem. Forgetting this change for a second: with default settings, what do you think is the problem I'm facing?

**Comment by Luap99** [comment]
do you change your uid by any chance? podman stores the full paths so you cannot change the uid. Also do you have a proper systemd login session? Systemd should create `/run/user$UID` for us.
Also see https://github.com/containers/podman/blob/main/troubleshooting.md#31-podman-run-fails-with-erro0000-xdg_runtime_dir-directory-runuser0-is-not-owned-by-the-current-user-or-error-creating-tmpdir-mkdir-runuser1000-permission-denied

**Comment by MaximilienLC** [comment]
I'm not sure as I didn't setup the SLURM system myself, but what if it does? Is there any way to still make it work?

**Comment by afbjorklund** [comment]
There are some hacks, using the "vfs" driver, documented at: https://slurm.schedmd.com/containers.html

> It is strongly suggested that sites consider using inter-node shared filesystems to store Podman's containers. While it is possible to have a scrun.lua script to push and pull images for each deployment, there can be a massive performance penalty. Using a shared filesystem will avoid moving these files around

**Comment by MaximilienLC** [comment]
> There are some hacks, using the "vfs" driver, documented at: https://slurm.schedmd.com/containers.html
> 
> > It is strongly suggested that sites consider using inter-node shared filesystems to store Podman's containers. While it is possible to have a scrun.lua script to push and pull images for each deployment, there can be a massive performance penalty. Using a shared filesystem will avoid moving these files around

Giving this a try

**Comment by MaximilienLC** [comment]
`podman pull ubuntu:22.04` gives

```
Error: writing blob: adding layer with blob  "sha256:2ab09b027e7f3a0c2e8bb1944ac46de38cebab7145f0bd6effebfe5492c818b6": ApplyLayer exit status 1 stdout:  stderr: Error setting up pivot dir: mkdir  /scratch/mleclei/graphroot/vfs/dir/b93c1bd012ab8fda60f5b4f5906bf244586e0e3292d84571d3abb56472248466/.pivot_root2137079740: permission denied
```

storage.conf:

```
[storage]
  driver = "vfs"
  runroot = "/scratch/mleclei/runroot"
  graphRoot = "/scratch/mleclei/graphroot"
```

Not changing runroot nor graphroot gives the same error (`mkdir /home/mleclei/.local/share/containers/storage/vfs/dir/b93c1bd012ab8fda60f5b4f5906bf244586e0e3292d84571d3abb56472248466/.pivot_root197865408: permission denied`), same for appending `--storage-driver`

**Comment by afbjorklund** [comment]
The SLURM documentation only mentions the Docker version, not the Podman version. Did it work better in 3.x ?

**Comment by MaximilienLC** [comment]
mmh indeed my Slurm is 22.05.8

**Comment by afbjorklund** [comment]
As I mentioned in the other discussion*, I think the native Podman way would be to set up a registry server in the cluster.

Then the login node would push to the registry after build, and the compute node would pull from the registry before run.

It is possible that the network to this web server is slower, than using the shared file system for saving and loading it...

If the archive needs to be expanded to local storage before it can be run (instead of mounted), that also adds overhead

\* https://github.com/containers/podman/discussions/18007

Also not mentioned here was that the image size is 15 GiB - but it would still be a difference, even with a 1 GiB image.

For small images and Low Performance Computing, it doesn't matter as much if they are being  packed and unpacked.

**Comment by afbjorklund** [comment]
This is a good introduction about "login node" and "compute node", as used in HPC:

https://training.pages.sigma2.no/tutorials/hpc-intro/episodes/12-cluster.html#nodes

* https://training.pages.sigma2.no/tutorials/hpc-intro/_images/connect-to-remote-login-node.svg

* https://training.pages.sigma2.no/tutorials/hpc-intro/_images/shared-file-system.svg

**Comment by MaximilienLC** [comment]
fixed by `rm ~/.local/share/containers/storage/libpod/bolt_state.db` and adding `--tmpdir /tmp/` on all successive commands
