### ISSUE TITLE
Make it possible to use --infra-name name feature in kube yaml

### ISSUE THREAD

**Issue by Sani7** [containers/podman#18312]
### Feature request description

Currently, there is no real way to use the --infra-name feature in the Kubernetes yaml.
It would be nice to have this for the same reason as initial the feature.
This was being able to update the pod and not having to change the infra name in the systemd service.
#10794

**Comment by rhatdan** [comment]
The best way to handle this would be Add an annotation to the kubernetes.yaml and then have podman use that annotation to setup the infra container name.

**Comment by Sani7** [comment]
Maybe it would be more convenient if the default infra name should be podName-infra unless specified otherwise in the kube.yaml or --infra-name

**Comment by rhatdan** [comment]
That works for me.  Interested in opening a PR?

**Comment by Sani7** [comment]
Sorry I'm not a go programmer ...

**Comment by rhatdan** [comment]
@umohnani8 PTAL

**Comment by rhatdan** [comment]
@ygalblum @umohnani8 @haircommander WDYT?

**Comment by umohnani8** [comment]
Currently the infra name is `podID-infra`, changing the default to be `podName-infra` could be a breaking change I believe. 
Adding a new `--infra-name` flag to podman kube play sounds good to me, we can use that when it is set as the name for the infra container and default to the current `podID-infra` name when it is not set.

For the kube generate part, we could add an annotation with the infra-name when `--infra-name` is set during pod creation. The annotation can be used during kube play if set in the yaml.

For kube play, order would be:
1. if --infra-name is set use that
2. otherwise check for annotation, if set use that
3. finally if neither of the 2 are set use the default `podID-infra` name

@rhatdan @vrothberg WDYT?

**Comment by rhatdan** [comment]
I am not sure it is a breaking change, but SGTM

**Comment by vrothberg** [comment]
> I am not sure it is a breaking change, but SGTM

Podman CI would break.  I'd be surprised if users would heavily rely on the deterministic name but we can only guess.

Adding a `--infra-name` SGTM

**Comment by ygalblum** [comment]
> For kube play, order would be:
> 
> 1. if --infra-name is set use that
> 2. otherwise check for annotation, if set use that
> 3. finally if neither of the 2 are set use the default `podID-infra` name

SGTM
