### ISSUE TITLE
podman create with non-existing --authfile should error on pull

### ISSUE THREAD

**Issue by vrothberg** [containers/podman#18938]
`podman create` seems to ignore (or not use?) the non-existing authfile while `podman pull` fails immediately.

```
podman (lint) $ podman images
REPOSITORY  TAG         IMAGE ID    CREATED     SIZE
podman (lint) $ podman create --authfile /tmp/idonotexist busybox
Resolved "busybox" as an alias (/etc/containers/registries.conf.d/000-shortnames.conf)
Trying to pull docker.io/library/busybox:latest...
Getting image source signatures
Copying blob 71d064a1ac7d done  
Copying config b539af69bc done  
Writing manifest to image destination
Storing signatures
67b48cd18eee3c9c0b2715ebb1b5acc36636fcce4aa07225c8faf44dea5dcb9e
podman (lint) $ podman pull --authfile /tmp/idonotexist busybox
Error: stat /tmp/idonotexist: no such file or directory
```

Detected in https://github.com/containers/podman/pull/18931#discussion_r1234071947 where the test must be fixed as well.

**Comment by Luap99** [comment]
That is pretty much the same discussion as in https://github.com/containers/podman/pull/18413.

If c/image silently ignores a non existing path then I agree we should error out in podman. However I still believe the correct thing is to only error out at the place were the file is actually used, otherwise we will always face TOCTOU bugs, but if c/image never does that then it is unavoidable I guess. 

And I really do not get why c/image would behave in such a way, AFAICT it does so since the beginning: https://github.com/containers/image/commit/f28367e1a
Is it really a sane behaviour of a library to silently ignore the given authfile just because it does not exists? This leads to hard to debug errors because I would assume the following pull/push would fail if you typo the path instead of clear error that your path is invalid.

Fixing this in the podman cli seems wrong as it duplicates the checks for each individual command. And then how does this compare to skopeo, buildah and cri-o? Do they also make sure to check for that?!

cc @mtrmac

**Comment by vrothberg** [comment]
I do not feel strongly unless we risk breaking existing workloads / users.  Once we've settled on how we want things to behave, we can make sure --authfile works consistently across the various commands.

**Comment by rhatdan** [comment]
Can we check if the caller is using a default value, if yes then don't complain on NOEXIST, else complain?

**Comment by mtrmac** [comment]
We can’t tell by the _value_. We would need a new field in `SystemContext` (either `AuthFilePathExplicitlySpecified string`, or  `AuthFilePathWasExplicitlySpecified bool`, and keeping the current behavior of silently ignoring missing files for existing callers). And then callers would opt in, either Podman directly or in c/image/pkg/cli/environment.

**Comment by vrothberg** [comment]
> I believe @vrothberg is working on this one.

It's very low on my priority list so I unassigned to make space if others want to tackle it.

**Comment by rhatdan** [comment]
Ok I think if the client specifies a path, then the path should be verified.
