### ISSUE TITLE
RFE: podman run -d --wait-for

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#18952]
possibly garbled middle-of-the-night idea. Possibly useless or impractical.
```console
$ podman run -d --wait-for=output:READY ... sh -c "do something; echo READY; do more stuff"
[hangs until the READY]
```
```console
$ podman run -d --wait-for=file:/foo ... sh -c "do prep work; touch /foo; spin doing something else"
```
```console
$ podman run -d --wait-for=port:12345 ...
```

Reason: too many nasty broken homegrown solutions to the problem of "podman run -d" then trying to use that container.

**Comment by Luap99** [comment]
As much as I understand where this is coming from I really don't want to support something like that.
While implementing this may not even be that difficult I don't think this a good general use case. I would argue this is a anti pattern. As a general user you should not rely on that and build the application fail safe so that it keeps retrying instead. And if you really want to wait for the application to be ready that this is a solved problem with sd_notify sockets. With that the application in the container can just send you when it is ready.

**Comment by rhatdan** [comment]
Yes we could do this now with sd-notify sockets, and just have the service write to the socket that it is ready.

**Comment by Luap99** [comment]
I am going to close this as I am very sceptical about the maintainability and complexity of such feature
