### ISSUE TITLE
Add support for `VolumeName` and `NetworkName` options in Quadlet

### ISSUE THREAD

**Issue by deuill** [containers/podman#19003]
### Feature request description

Currently, Podman volumes and networks created by Quadlet/`podman-systemd` units are automatically named based on the unit name, with a `systemd-$NAME` convention, similar to container units. However, unlike container units (which allow for overriding this name via the `ContainerName` directive), volume and network units do not allow for this sort of name override.

Having such directives (e.g. `VolumeName` and `NetworkName` for `.volume` and `.network` units, respectively) would help with transitioning existing systems to Quadlet without wrangling with naming conventions, an especially tricky issue with volumes (which cannot be used and migrated between simultaneously in any reasonable manner).

### Suggest potential solution

Quadlet should be extended with support for `VolumeName` directives for `.volume` units. and `NetworkName` for `.network` units, which will set the `name` parameter for the underlying `podman volume/network create ...` (or internal API equivalent) calls.

### Have you considered any alternatives?

The only reasonable alternative is preparing production environments for migrating between volumes and networks with different names, which may not be feasible in larger deployments, and impedes clean migration to Quadlet.

**Comment by rhatdan** [comment]
Interested in opening a PR to make the change?

**Comment by deuill** [comment]
> Interested in opening a PR to make the change?

Sure thing, I've tried my hand at closing this in #19006

**Comment by ygalblum** [comment]
I've also written in the PR:
This is very problematic. The reason is that Quadlet relies on these names in order to create the dependency between the units created for the `.container` or `.kube` files and ones created for the `.network` or `.volume` files

**Comment by deuill** [comment]
I'll have to dig into the implementation here, but I assume you mean how Quadlet will add `Wants=` dependencies for `Volume=foo.volume:/mnt` directives? My impression was that these would target the unit name, not the (implied) volume/network name, though I understand this would require filesystem traversal rather than a simple `volume/network exists` call.

Assuming the feature request itself is desirable, is there a direction you'd like to see me go here? Alternatively, I can dig in and see what sort of implementation might work -- including perhaps parsing `.network` and `.volume` dependencies in order to find possible `NetworkName`/`VolumeName` directives before using the implied names.

**Comment by ygalblum** [comment]
I'll explain for `.volume`, but the same applies for `.network`.

First, sorry, my comment was incorrect. I referred to the systemd dependency (which is not really affected) when in fact the actual issue is with the translation between the value of the `Volume` key and real name of the volume.

In the current implementation, for a `$NAME.volume` file, Quadlet creates a systemd unit file called `$NAME-volume.service` which creates a podman volume named `systemd-$NAME`.

In order to use said volume, the `.container` file should state `Volume=$NAME.volume`. Quadlet will then replace the name of the volume passed to the `podman run` command to `systemd-$NAME` and add a systemd dependency with `Requires=$NAME-volume.service` and `After=$NAME-volume.service`.

You can see the implementation here: https://github.com/containers/podman/blob/main/pkg/systemd/quadlet/quadlet.go#L1206.

You change breaks this consistency. 

In order to indicate to Quadlet that the volume is in fact a Quadlet based volume, the user will still need to pass `$NAME.volume` as the source. Quadlet will then need to look for this `$NAME.volume` and parse it to see if its name was set. Currently, each file is processes separately. Your suggestion will require transferring knowledge between units.

I'm not sure I understand the use case of the problem you are solving here. Can you please provide an example?

**Comment by deuill** [comment]
> I'll explain for `.volume`, but the same applies for `.network`.
> 
> First, sorry, my comment was incorrect. I referred to the systemd dependency (which is not really affected) when in fact the actual issue is with the translation between the value of the `Volume` key and real name of the volume.
> 
> In the current implementation, for a `$NAME.volume` file, Quadlet creates a systemd unit file called `$NAME-volume.service` which creates a podman volume named `systemd-$NAME`.
> 
> In order to use said volume, the `.container` file should state `Volume=$NAME.volume`. Quadlet will then replace the name of the volume passed to the `podman run` command to `systemd-$NAME` and add a systemd dependency with `Requires=$NAME-volume.service` and `After=$NAME-volume.service`.
> 
> You can see the implementation here: https://github.com/containers/podman/blob/main/pkg/systemd/quadlet/quadlet.go#L1206.
> 
> You change breaks this consistency.
> 
> In order to indicate to Quadlet that the volume is in fact a Quadlet based volume, the user will still need to pass `$NAME.volume` as the source. Quadlet will then need to look for this `$NAME.volume` and parse it to see if its name was set. Currently, each file is processes separately. Your suggestion will require transferring knowledge between units.

Indeed, yeah, though this doesn't seem an insurmountable hurdle -- not sure if there's any precedent though.

> I'm not sure I understand the use case of the problem you are solving here. Can you please provide an example?

Simply enough, I want to move to managing existing volumes and networks in Quadlet rather than with a [home-grown](https://github.com/deuill/coreos-home-server/blob/trunk/host/base/systemd/container-volume%40.service) [kludge](https://github.com/deuill/coreos-home-server/blob/trunk/host/base/systemd/container-network%40.service), but doing so requires that I:

  1. Have all relevant containers join both existing and new (Quadlet-based) networks, via duplicate `Network=example` and `Network=example.network` definitions in the `Container` unit, then probably phase out the existing uses.
  2. Somehow migrate data between existing and new volumes, and move `Container` units to `Volume=example.volume` definitions rather than `Volume=example` definitions.

AFAICT there's no reason that Quadlet networks and volumes can't be used to manage existing resources, assuming options used aren't incompatible. This would then allow for capturing and improvements to these units, as well as the obvious benefits of automatic dependency chains.

**Comment by ygalblum** [comment]
If I understand correctly, the resources already exist in the system, right?

I'm asking because, the `.volume` and `.network` units only handle the creation of the volume/network. You can see that they only have `ExexStart`, but no `ExecStop`. 

So, if these resources already exist in the system, why would you need Quadlet units for them?

**Comment by deuill** [comment]
The resources (volumes and networks) that I'm looking to cover do already exist in the host system, correct -- however, they would not exist on new host systems that utilize the same common `coreos-home-server`configuration, which would force me to either leave these resources out of configuration due‎ to "legacy" considerations, or to somehow migrate existing systems over to Quadlet, an issue that is harder to solve in the absence of consistent naming.In addition, automatic dependency definitions between container and volume/network units ‎is an incredibly useful feature, and only possible via Quadlet-managed resources.

**Comment by ygalblum** [comment]
OK. So, let's think what we need to do in order to support this change. 

In the [process method](https://github.com/containers/podman/blob/main/cmd/quadlet/main.go#L317), Quadlet first gets the entire list of units from all of its input directories and then processes each file separately according  to whichever order the list got filled.
 
But, in order to support non-calculated names for Networks and Volumes, Quadlet will have to first process the corresponding files (`.volume` and `.network`) and maintain a map between each file and the name of the resource it created (given or calculated).
Once done with these files, it will process the `.container` and `.kube` files. This time when processing the source volume or network, instead of assuming the name was calculated, the process will look for the name in the map created in the step before.

One question is how to handle a case in which the file was not found in the map. Should Quadlet fail or assume auto-calculation? On one hand failing sounds reasonable because the service will be pointing to an non-existing service and resource. But, this will be a behavior change.

WDYT?

**Comment by deuill** [comment]
Hi, apologies for the late reply here. The approach looks feasible, yeah, I just need to clarify a few details before I dive in: 

  - At which point do we want to try to determine the `NetworkName`/`VolumeName` values? I suppose this might happen in `process()`, after `loadUnitsFromDir()` is found to have completed successfully, but before the units themselves are parsed.
  - How do we want to pass state down to `ConvertContainer()` and `ConvertKube()` (and then `addNetworks()` and `handleStorageSource()`? I suppose the only reasonable way is adding a parameter in each function for a `map[string]string` or similar, or perhaps extending the `parser.UnitFile` with some additional field.

The implementation here might be slightly more idiomatic if the various `Convert` functions were placed under a common type representing the Quadlet parser state, say:

```go
package quadlet

type Quadlet struct {
    Units map[string]*parser.UnitFile
}
```

And then at least avoid the pain of passing state around explicitly, though I suppose this might be too much refactor?

**Comment by ygalblum** [comment]
Not sure how you'd use your suggested type. If you pass the entire map of units, you will need to also pass the name of the unit the `convert` method should target.
Also, currently, a `parser.UnitFile` object represents a systemd unit file without additional fields. I'm not sure that adding fields that are not meant to be part of a systemd unit file will make it more readable.
Having said that, I agree that passing around another map is not that pretty either.

My suggestion is:

- Maintain the unit name to resource name in `process`
- Add a return field to `ConvertVolume` and `ConvertNetwork` which is the name of the resource and update the map accordingly.
- Pass the map to `ConvertContainer` and `ConvertKube`. 
- These methods can pass the map along to `addNetworks` and `handleStorageSource`
- Since the unit names are unique (due to their extension), you can maintain a single map

WDYT?

**Comment by deuill** [comment]
Sounds good -- the idea behind having state in a receiver would be that we could, having the target volume/network unit name, derive the `VolumeName`/`NetworkName` values (if any) by direct calls to `Lookup()`, though I agree that we'd still need to then either have `addNetworks` and `handleStorageSource` be under the receiver, or pass the concrete name down somehow.

That said, your approach is better -- I'll go with that. Thanks for the considerate feedback!

**Comment by deuill** [comment]
Just force-pushed some changes -- I'm having trouble running E2E tests on local so I'm hoping I've caught everything, but might need to push some additional changes depending on test results:

https://github.com/containers/podman/compare/14d89f4d1a10de89906b4e84f685ef9fdee360e2..cbe51ef20d43cb50d840839dbab6970acd5fd878

Some of the function signatures are getting a bit unwieldy, but I guess this might all get swooped under some future refactor (as always happens). Feel free to drop in your comments!
