### ISSUE TITLE
Use terminal colors for output

### ISSUE THREAD

**Issue by sedrubal** [containers/podman#19110]
### Feature request description

Podman output would be easier to read if it used terminal colors / true colors / ansi colors. This is the current situation:

```
# podman image ls
REPOSITORY                                     TAG         IMAGE ID      CREATED      SIZE
docker.elastic.co/elasticsearch/kibana         8.8.2       e2f9d35de731  7 days ago   934 MB
docker.elastic.co/elasticsearch/elasticsearch  8.8.2       673e6376a286  8 days ago   1.34 GB
docker.elastic.co/elasticsearch/logstash       8.8.2       98494fd39ccb  12 days ago  779 MB
``` 

### Suggest potential solution

The example from above could look like this:

![Screenshot_20230704_091025](https://github.com/containers/podman/assets/5571650/9243fd64-53af-42d9-8fcf-752a7ca082bb)

(I guess UX designer can do a better job...)

### Have you considered any alternatives?

I could use a custom Go template by using `--format`.

**Comment by vrothberg** [comment]
Thanks for reaching out, @sedrubal.

I am not a designer but a "visual" person, so I sympathize with your idea.  But it's hard to get the colors right, especially with the vast amount of different terminal color schemes.  So my fear is that it's causing a lot of continuous work.

@containers/podman-maintainers what do you think?

**Comment by Luap99** [comment]
I agree, it is not clear what looks good or how this integrates with the rest of your local color scheme. And more importantly this means we need two branches for every output because if no tty is attached we will always need a version without colors.
Without the amount of commands we have this would cause way to much work IMO, considering that the benefit is only marginal.

**Comment by sedrubal** [comment]
> vast amount of different terminal color schemes

Every terminal color scheme defines colors for the [ANSI codes](https://talyian.github.io/ansicolors/) for black, red, green, yellow, blue, magenta, cyan, white, which look good in the specific color scheme. As long as podman does not use truecolors (which I used in the example), podman doesn't have to worry about that.

> this means we need two branches for every output

I'd say it depends on how it gets implemented. Usually, I use the python library [termcolors](). There you just have to format the colored output and the library will care about coloring the output if the terminal/output stream supports colors. Otherwise the output looks similar as before.

Please think about it as productivity can be boosted by using colors. Even basic traditional commands like `ip` support termcolors nowadays.

**Comment by Luap99** [comment]
I agree with you, colors are indeed useful. I am just not so convinced that it can be implemented in an easy way so that a) the colors make sense and b) this does not add a lot of workload for us.

If you have some example go application which does that I am happy to take a look on how complex the code actually looks. But keep in mind we have over 200 subcommands in podman so adding something like this is not trivial, sure not all of the commands print tabular output but many do.

**Comment by vrothberg** [comment]
I am going to close the issue for the reasons mentioned above.  It would be nice to have but the cost/benefit ration is out of balance.
