### ISSUE TITLE
podman image exists for transports other than containers-storage

### ISSUE THREAD

**Issue by tarun360** [containers/podman#19192]
### Feature request description

As of now `podman image exists` command only works for containers-storage. For other transports it returns an error. Example:

```
$ podman image exists docker://some-remote-image-url
Error: unsupported transport "docker" for looking up local images

$ podman image exists oci-archive:/path/to/image
Error: unsupported transport "oci-archive" for looking up local images
```

It would be useful if `podman image exists` for all transports. 

Since this is a very basic and common operation, it would be useful if this is supported by podman itself. Installing a separate tool just for doing image inspect is slightly inconvenient.

### Suggest potential solution

We can first check if the image name is of correct format or not using this [ParseImageName](https://github.com/containers/image/blob/44a5d077283af2490c8237bcc634c035345e1fc4/transports/alltransports/alltransports.go#L26) function.

After that, we can call [NewImageSource](https://github.com/containers/image/blob/44a5d077283af2490c8237bcc634c035345e1fc4/types/types.go#L85) function to check existence of an image. For example, in case of docker transport, the implementation of this function can be seen [here](https://github.com/containers/image/blob/44a5d077283af2490c8237bcc634c035345e1fc4/docker/docker_transport.go#L143).

If the above access fails, we can infer that image does not exists. Otherwise, the image exists.

### Have you considered any alternatives?

`skopeo image inspect` returns low level information about image. This works for all transports. This could be used as a proxy to check whether the image actually exists or not.

### Additional context

I would like to volunteer to implement it, if the podman maintainers believe this feature should indeed be added to podman.

**Comment by flouthoc** [comment]
I have a mixed feeling about this, `podman` is a container manager tool all its commands are majorly w.r.t to the images stored on local storage and containers on the current host while `skopeo` is specifically designed to work with retrieving information about images and deals specifically with images.

So while this makes sense for `skopeo` since it can do multiple operations while taking remote image directly into consideration i cant think why `podman` should have this, since `podman` can do nothing other than `pulling` the image.

If anybody wants to analyze image I am just thinking he should directly use `skopeo` for this.

This is just my opinion and I could be wrong so tagging :) @containers/podman-maintainers @containers/image-maintainers

**Comment by vrothberg** [comment]
Thanks for reaching out, @tarun360 !

> If anybody wants to analyze image I am just thinking he should directly use skopeo for this.

I concur with @flouthoc.  Skopeo is right tool choice for this task.

**Comment by mtrmac** [comment]
> If the above access fails, we can infer that image does not exists. Otherwise, the image exists.

`NewImageSource` is not documented to make that kind of a promise. At least in two transports, `NewImageSource` is a purely in-process-memory metadata operation that checks nothing about the external environment.

(And then there are varying levels of pedantry one could go to… if a manifest exists in the destination, but a layer does not, does the image “exist“ or not? If all components of the image exist, but there is a bit error and it can’t be pulled because a digest does not match, does the image “exist”? Ultimately, that leads to the next question:)

---

>  Since this is a very basic and common operation

It — AFAICS — just… isn’t a common operation?!

What are you using the `podman image exists` check for? It seems to me that it is never an end to itself. So, why?
- Do you want to ensure that the image is pulled so that future container creations don’t pull it? Use `podman pull`, perhaps with some option; don’t ask to ask.
- Do you want to ensure that the image has been removed locally? Use `podman rm`, perhaps with some option. An extra presence check is not any faster.
- Something else, I guess?

What are you actually trying to do?

---

WRT the Podman vs. Skopeo question, I’m generally not much in favor of heuristic string parsing. If `podman image exists busybox:latest` is already supported, adding `podman image exists `_transport_`:`… makes the input ambiguous:

Consider `podman image exists dir:latest`: does that mean `docker://docker.io/busybox/dir:latest`, or `dir:./latest`??

Now, that’s certainly not a new problem for the Podman CLI, but that’s not automatically a reason to add more ambiguities like that.

So if `skopeo inspect` can work for this purpose (can it? let’s talk about the use case first), I don’t think adding ambiguity to Podman is very attractive.

**Comment by tarun360** [comment]
Thanks @mtrmac for such a detailed response.

This is what I am actually trying to do:

- I have a script `run.py` which does time-consuming operations and then towards the end pulls a container from remote registry and runs it.
- Since `run.py` is a time-consuming script (which does time-consuming operations before pulling the remote image), I have a `pre_run.py` script which does some checks to check whether `run.py `would be successful or not. In `pre_run.py` I wish to check if the image which `run.py` would be pulling actually exists or not. Since the image could be quite large, I don't want to actually pull the image in `pre_run.py` itself to check if it actually exists. 
    - Since `pre_run.py` and `run.py` could run in different machines, so I cannot pull image in `pre_run.py` (to check if image actually exists) and then assume that pull operation of `run.py` will be a no-op.
    - Since `pre_run.py` is supposed to be a relatively quick and cheap test, I do not wish to pull the entire image to check image's existence at a remote registry.

**Comment by mtrmac** [comment]
Thanks. An eventually-consistent registry really is a good reason to do an existence check.

I suppose, ideally the registry should expose a “wait until 100% propagated” primitive, but that’s not always an option.

---

Using `skopeo inspect` seems natural to me, in this situation.

I wouldn’t object to this being built-in to Podman, maybe something like `podman image exists --on-registry` (unambiguous, and without committing to support of all transports). I don’t see much value in that, but I’ll fully defer to Podman maintainers in that decision.

**Comment by rhatdan** [comment]
I think this is a job for skopeo inspect not for podman.
