### ISSUE TITLE
New quadlet "wait" is flaky

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#19296]
#19284 is causing flakes:
```
[08:05:18.437893287] # [...]/bin/podman logs test_pod-ctr
[08:05:18.780471277] Error: no container with name or ID "test_pod-ctr" found: no such container
```
Root cause: probably a race where `wait_for_output` runs before container has started

**Comment by edsantiago** [comment]
>runs before container has started

Nope. Next guess: quadlet runs with `--rm`, so container disappears before `podman logs` can get its logs. @ygalblum can you confirm if quadlet does this? If so, we need a different fix.

**Comment by ygalblum** [comment]
AFAIK 'kube play` is the one forcing the `--rm` behavior. But, since this test tests the exit propagation, the containers must exit. To make sure the test can find the container start logs, I've forced `log-driver=journald`.

This should handle this issue and the original one (the fact that it assumed that the default driver is in fact journald)
