### ISSUE TITLE
github.com/opencontainers/runc not being updated

### ISSUE THREAD

**Issue by mtrmac** [containers/podman#19795]
Currently `go.mod` contains
```
replace github.com/opencontainers/runc => github.com/opencontainers/runc v1.1.1-0.20220617142545-8b9452f75cbc
```
This is from the main branch, while releases come from a divergent `release-1.1` branch.

And the commit reference in `replace` hasn’t changed since 2022-06-13 .

I think that’s risky; compare https://github.com/containers/podman/pull/18110 fixing security vulnerabilities (luckily, AFAICS, not impacting the Podman codebase right now, but that can change by using one more subpackage, without us noticing.)

I think either we should revert back to using released versions (maybe that’s possible after https://github.com/containers/podman/pull/19101 ?), or Podman needs some process to keep updating the runc `replace` directive to keep up with upstream fixes. I don’t know nearly enough about runc to suggest which one is preferable.

**Comment by mheon** [comment]
The commit that added the replace was https://github.com/containers/podman/commit/2792e598c7ce1198ec8464a3119504123ae8397c which, AFAIK, did so to expose functionality that had not yet landed in a release (cgroups package changes). I think we should be safe to remove the override given this. If things continue to build afterwards, all should be well.

**Comment by rhatdan** [comment]
I agree, remove this if possible.

**Comment by giuseppe** [comment]
it builds fine, opened a PR: https://github.com/containers/podman/pull/19817

**Comment by tempoz** [comment]
This is still an issue; I see in #19817 that `runc` had unwanted bloat, but the current `runc` version being used by `podman` has 5 fixable security vulnerabilities:
CVE-2023-27561
CVE-2024-21626
CVE-2022-29162
CVE-2023-28642
CVE-2023-25809

Which means so does `podman`.

Can this be revisited? I'd personally be happiest with updating to a newer `runc` version (though I know little enough about this project that my opinion on this is not particularly valuable), but even just maintaining a fork with backported fixes might be something to explore.

**Comment by mheon** [comment]
We don't use the code in 4 of those CVEs (Podman only vendors runc for cgroup management code), and we last bumped runc on main [this February](https://github.com/containers/podman/pull/21472), so I am quite certain [CVE-2023-25809](https://github.com/advisories/GHSA-m8cg-xc2p-r3fc) does not affect us. The latest runc drags in an eBPF library we don't want or need and increases binary size of Podman by over a megabyte, so we've very reluctant to vendor it.

(I would investigate whether you're getting sane results about what CVEs affect us, because we're pinned to a commit, not a version, and that makes go.mod's contents unreliable; it says we're on v1.1.1-<somehash> but we're actually on main to avoid the eBPF bloat).

**Comment by rhatdan** [comment]
@AkihiroSuda @kolyshkin Anyway runc could be redesigned for us to avoid the bloat?

**Comment by mheon** [comment]
Runc main doesn't have the problem, so I assume runc v1.2.0 will not either; we're basically just waiting for a 1.2.0 final release.
