### ISSUE TITLE
containerized: failed to connect to syslog: Initialization

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#19809]
podman-in-container on [f38](https://api.cirrus-ci.com/v1/artifact/task/4969105690722304/html/int-podman-fedora-38-root-container-boltdb.log.html) pseudorandomly (i.e. flakily) emits the following warning:
```
failed to connect to syslog: Initialization
```
I do not see it on [containerized f37](https://api.cirrus-ci.com/v1/artifact/task/6095005597564928/html/int-podman-fedora-37-root-container-boltdb.log.html)

This is blocking #19802

**Comment by vrothberg** [comment]
@flouthoc can you take a look at this one?

I suspect the log to come from aadvark-dns: https://github.com/containers/aardvark-dns/blob/c9cbf7d5146c34e51c00b2bc190f41a011d5e3ea/src/main.rs#L63

**Comment by flouthoc** [comment]
Error is coming from the `syslog` crate itself when it tries to connect to local syslog using unix socket, let me try reproducing this, maybe we need a retry logic here. I'll check this.

**Comment by vrothberg** [comment]
@flouthoc did you find time to look into it?

**Comment by vrothberg** [comment]
Friendly ping.  Something for bug week next week?

**Comment by Luap99** [comment]
The question is what should we do instead? Of course it is easy to just not log this error at all but loosing all logs on systems without syslog seems undesirable to me.
Unfortunately we cannot keep logging to stderr because aardvark-dns lifetime can be much longer then the command which spawned it meaning if you close your terminal aardvark-dns would die because of SIGPIPE.
But we already have this problem right now so I guess we ignore that for now and maybe only log this error when debug logs are requested like we do in podman
https://github.com/containers/podman/blob/a1982c043dc77f76d013ff24509110ef93f4233e/cmd/podman/syslog_common.go#L19-L21

**Comment by Luap99** [comment]
I created https://github.com/containers/aardvark-dns/pull/402 to remove this line
