### ISSUE TITLE
adding a symbolic link to the container through --volume, the real file should be accessed 

### ISSUE THREAD

**Issue by I-Want-ToBelieve** [containers/podman#19925]
### Feature request description

When adding a symbolic link to the container through --volume, the real file cannot be accessed.

Unless the path pointed to by the symbolic link is also added, but sometimes this cannot be done, it would be great if you could directly follow the symbolic link to obtain the real file and copy the file into container.

**Comment by wnm3** [comment]
@I-Want-ToBelieve why was this closed? This is a bug as far as I'm concerned because docker does allow volume references to symbolic links and podman will not. 

Our use case was having mounted a disk off root to add space to a machine, we want to mount /store/pipeline (where /store is the mounted disk). This works fine with podman/docker. However, to simulate this environment on MacOS we can not create a directory off root, only a symbolic link via the /etc/synthetic.conf file. We can not mount the resulting /store/pipeline where /store -> ~/store. This works fine with docker though.

We want to use the same script to launch a container with the volume mount point to be /store/pipeline regardless of the environment (direct or symlinked /store).

**Comment by rhatdan** [comment]
@wnm3 Please open a new issue and include all of the `podman info`

**Comment by wnm3** [comment]
Done: https://github.com/containers/podman/issues/20350
