### ISSUE TITLE
podman machine init should default to stable image

### ISSUE THREAD

**Issue by rgov** [containers/podman#20182]
`podman machine init` defaults `--image-path=testing` instead of `stable`.

The default should probably be `stable` so that most users are not surprised by experimental changes that have not been fully QA tested and can cause regressions. In #20179 I describe how a change to the `testing` image broke my ability to run containers from the Docker CLI.

**Comment by baude** [comment]
hello @rgov thanks for the issue report and taking the time to write it up.  Right now, I think? we are benefiting from testing over stable largely because of how fast things are moving for us.  that said, this is something maybe we should consider.  the downside, is I can see the complaints rolling in that stable is too ancient.  but on the other hand, this is something that can be overridden.

perhaps this is something we should consider for podman5? I would for sure want to wait until the gvforwarder content for the hyerpv fcos image is in stable (maybe another 2-4 weeks).  then the debate would be largely around the development around applehv.

it seems like a reasonable request.  it can be worked around by changing the stream in containers.conf

What do others think?

**Comment by rhatdan** [comment]
If we move to an OCI Image update scheme then this is a no brainer.

**Comment by Luap99** [comment]
We now have our own custom images so this should no longer effect us
