### ISSUE TITLE
Support `--uidmap` in Quadlet

### ISSUE THREAD

**Issue by Bai-Chiang** [containers/podman#20619]
### Feature request description

I start linuxserver.io containers with command like this:
```
podman run \
    --rm \
    --replace \
    --uidmap 1000:0:1 \
    --uidmap 0:1:1000 \
    --uidmap 1001:1001:64536 \
    --name=syncthing \
    --env PUID=1000 \
    --env PGID=1000 \
    -v /path/to/config:/config \
    -v /path/to/data1:/data1 \
    --publish 8384:8384 \
    lscr.io/linuxserver/syncthing:latest
```

It would be nice to have `uidmap` option support in Quadlet.

### Suggest potential solution

Add `uidmap` option in Quadlet configuration file, or an option that could pass any podman args.

### Have you considered any alternatives?

I tried `--userns keep-id:uid=1000,gid=1000` but this does not work with linuxserver.io containers.

**Comment by ygalblum** [comment]
Quadlet has a deprecated support for setting `--uidmap` by adding:
```
RemapUsers=manual
RemapUid=1000:0:1
RemapUid=0:1:1000
RemapUid=1001:1001:64536
```
However, as I wrote, this was deprecated when the `UserNS` key was introduced.

@rhatdan @xduugu @vrothberg do you remember why was the old implementation deprecated (instead of just having `UserNS` take precedence)? How do you suggest we should address this request?

**Comment by vrothberg** [comment]
The `Remap*` keys were deprecated with commit https://github.com/containers/podman/commit/f6a50311c56d motivated by https://github.com/containers/podman/issues/17984.

I do not see a direct counterpart for `--uidmap` in the Quadlet docs but the code seems to support a "manual" mode which in turn isn't documented in podman-create.  All very confusing!  It seems though that the "auto" mode allows for specifying custom gid and uid mappings.

@giuseppe may be able to help my confusion.

**Comment by giuseppe** [comment]
`--userns` is not a replacement for the other options.  It made sense to have only `--userns` in the perspective of `play kube` doing what is possible to do in Kubernetes, where it is not possible to configure the mappings but only have the equivalent of `--userns=auto`.

If we need the equivalent of `--uidmap` and `--gidmap` then we need to expose them.  I suggest a direct mapping to the podman flags instead of something like `RemapUidSize` and `RemapUsers` since these two conflict as they both map to `--userns`

**Comment by rhatdan** [comment]
For now @Bai-Chiang can just use PodmanArgs: --uidmap 1000:0:1 \
    --uidmap 0:1:1000 \
    --uidmap 1001:1001:64536 \

**Comment by ygalblum** [comment]
I'm thinking how should this be implemented in terms of overrides verification, and deprecation. 

First, there's the deprecation of all the "Remap" keys. So, if any of `UserNS`, `UIDMap` or `GIDMap` are set, Quadlet will disregard any `Remap` keys.

Second, `UserNS` conflicts with `UIDMap` and `GIDMap` and therefore they should not be set together. Generally speaking, Quadlet does not do such validations and allows the creation of faulty commands. As I see it, there are three options:

1. No validation at all. Add all arguments and let Podman fail
2. Validate that either `UserNS` is set or  `UIDMap` and `GIDMap`, but the combination of them
3. Give precedence to one over the other (I guess `UserNS` over  `UIDMap` and `GIDMap`)

Lastly, since they also conflict with these arguments, should Quadlet also support `SubUIDMap` and `SubGIDMap`?

WDYT?

**Comment by rhatdan** [comment]
I just think we go with the precedence of letting Podman handle it.
