### ISSUE TITLE
Rolling back transaction to validate database: sql: transaction has already been committed or rolled back"          # Error: database graph driver "" does not match our graph driver "overlay": database configuration mismatch

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#20731]
Scary new flake seen in Debian CI:
```
# podman pod rm -t 0 --all --force --ignore
time="2023-11-20T22:34:49Z" level=error
      msg="Rolling back transaction to validate database: 
         sql: transaction has already been committed or rolled back"
         Error: database graph driver "" does not match our graph driver "overlay":
         database configuration mismatch
```
Happened even before the first test. Once it happened, nothing else worked, system was completely hosed. (Possibly fixed by system reset? No way to know).

https://api.cirrus-ci.com/v1/artifact/task/5989609746726912/html/sys-podman-debian-13-root-host-sqlite.log.html#t--00001

**Comment by mheon** [comment]
Looks like a combination of issues: somehow we're not getting the right default graph driver ("" should probably resolve to "overlay") and the sqlite DB is throwing scary error messages that it really does not need to after discovering this mismatch.

**Comment by Luap99** [comment]
There is at least one logic issue in the function:
https://github.com/containers/podman/blob/8387d2dfaae5a0e1cf24412cefaadc8a3f08b223/libpod/sqlite_state.go#L348-L386

Once tx.Commit() is called it is impossible to rollback on an error. So the commit call must be moved to the end of the function. Of course that only explains the sql error message.

As @mheon mentioned that does not explain the root cause. My guess is that for some reason podman was run with an empty graph driver before we changed the storage.conf file in the testing infra to say `overlayfs`
https://github.com/containers/podman/blob/8387d2dfaae5a0e1cf24412cefaadc8a3f08b223/contrib/cirrus/setup_environment.sh#L196-L205

**Comment by Luap99** [comment]
@edsantiago still seeing this?

**Comment by edsantiago** [comment]
Interesting timing: I actually saw this again yesterday, [rawhide rootless](https://api.cirrus-ci.com/v1/artifact/task/6461881513148416/html/int-podman-rawhide-rootless-host-sqlite.log.html#t--Podman-init-podman-init-all-three-containers--one-running--1):
```
$ podman [options] stop --all -t 0
time="2024-04-02T18:21:15-05:00" \
    level=error msg="Rolling back transaction to save container xxx state: \
        sql: transaction has already been committed or rolled back"
Error: saving container xxx state before stopping: saving container xxx state: \
     committing container xxx state: disk I/O error: resource temporarily unavailable
                                     ^^^^^^^^^^^^^^
```
The "disk I/O error" makes me suspect a hardware flake. I looked in the journal but was unable to find anything else interesting. I'm OK with closing.
