### ISSUE TITLE
MacOS Local Port Mapping

### ISSUE THREAD

**Issue by coval3nte** [containers/podman#21679]
### Issue Description

exposing container **privileged** ports to **local ip** doesn't work as expected.

### Steps to reproduce the issue

`podman run -p127.0.0.1:1023:80 IMAGE`

### Describe the results you received

Error: preparing container *id* for attach: something went wrong with the request: "listen tcp 127.0.0.1:1023: bind: permission denied\n"

### Describe the results you expected

.

### podman info output

```yaml
.
```

### Podman in a container

No

### Privileged Or Rootless

Privileged

### Upstream Latest Release

Yes

**Comment by Luap99** [comment]
We run unprivileged on the mac so we cannot bind ports < 1024 unless the OS allows that, for some reason macos allows you to bind 0.0.0.0 on such port but not to bind a specific ip on these ports https://developer.apple.com/forums/thread/674179 so I would call this a apple bug and not something we can fix.

**Comment by jorgemoralespou** [comment]
Hi @Luap99, I just saw your reply, and while I understand that by default podman runs unprivileged on macOS, to be used as a replacement for Docker, which runs privileged and allows bind those ports (<1024) there should be a potential alternative to allow podman to be run rootful. Is that possible?

**Comment by Luap99** [comment]
Running `podman machine `as root is not supported by us. You can run `podman machine init --rootful` but this will only run podman as root inside the VM (which will be needed to bind privs port in the VM as well).
If you want to bind these ports use you have to use 0.0.0.0 on the mac side or bind a higher port then use firewall rules to redirect traffic or well ask apple why they restrict this in the first place but allow 0.0.0.0. Because this really makes no sense at all.
