### ISSUE TITLE
No documentation for installation

### ISSUE THREAD

**Issue by b9Joker108** [containers/podman#21831]
### Issue Description

I want to install Podman in Termux. I downloaded and extracted: tar -xvzf podman-release-arm64.tar.gz. At the location I secured the tarball, it says the archive includes configuration and documentation. I can find no documentation, so am unsure how to proceed with installation. 

### Steps to reproduce the issue

Steps to reproduce the issue
1. I downloaded. 
2. Created Podman directory. 
3. Moved tarball into Podman directory. 
4. I executed: `tar -xvzf podman-release-arm64.tar.gz`
5. Tarball extracted. 
6. I searched throughout, and found no documentation, which is contrary to what was written at the point of securing tarball. 

### Describe the results you received

I expected documentation to be in the extract, as was stated, but it was not. 

### Describe the results you expected

I expected documentation to be in the extract, as was stated, but it was not.

### podman info output

```sh
uname -a
Linux localhost 5.15.94-android13-8-27940245-abX910XXU1BWL1 #1 SMP PREEMPT Mon Dec 4 10:05:43 UTC 2023 aarch64 Android
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by baude** [comment]
can you point specifically where you got the podman-release-tar.gz ?

**Comment by b9Joker108** [comment]
It's not that there were no man pages, there was no documentation proper. There was no README.md or comparable, no installation instructions, and no installation script, that I could discern.

**Comment by b9Joker108** [comment]
Why did baude change the issue title to something that doesn't even represent the issue?

**Comment by baude** [comment]
the title is too generic, but i crossed it up with another issue; should be better now.

**Comment by 392781** [comment]
Yes, in the docs it says that installers are provided but that is clearly not the case in the releases page.  In addition, the Linux installations via package managers all use outdated versions of podman (and podman-docker).

**Comment by 392781** [comment]
@ashley-cui @mheon Can either of you provide insight to how latest releases are meant to be installed on Linux (@'ing since both of you seem to manage the GitHub releases for Mac/Linux/Win)?

**Comment by rhatdan** [comment]
Using native packages.
yum install podman
dnf install podman
apt get podman

We do not ship podman for any distributions.  It is up to the distributions to do the install.  If you go to podman.io you will see information on how to install podman.

**Comment by rhatdan** [comment]
http://podman.io/docs/installation

**Comment by mheon** [comment]
@rhatdan is correct, we don't do binaries for Linux deliberately - the large number of required dependencies (Conmon, Netavark, Slirp4netns/Pasta, and various config files) make it impractical to ship bare binaries on Linux.

**Comment by 392781** [comment]
@rhatdan I'm well aware of the install instructions page, the issue is that theres a wide discrepency between what the current stable release is and what the various package repos seem to have. The website makes it seem that getting the latest release doesn't require jumping through hoops but so far thats not the case.

Is the only option to run the latest stable version _really_ building from source on your own?

**Comment by rhatdan** [comment]
Sure and the upstream does not have the contributors to deal with every distribution and all of the podman dependencies to update on each release.

Certain distributions like Fedora, Debian, SUSE and others keep up fairly well. Ubuntu and others no so much.
If you want to volunteer to maintain upstream packages for your favorite distribution, then you are welcome to it.

**Comment by 392781** [comment]
This seems like a pretty big issue if certain distributions are a major version behind while others are also struggling to keep up. Docker seems to have no problem with this... Unfortunately Docker has some pretty big issues that makes it not viable for our org.

You mentioned that there's a lack of contributors... does it truly come down maintaining a distributions packages to get the latest version out?  Why not provide common installers such as .deb/.rpm as an in-between solution (.exe and .pkg are provided for Windows and Mac...)?

I'm curious because this seems like a significant hurdle especially when a distro as big as Ubuntu is 1 major version behind (fortunately the distro of choice for our org, Almalinux, is only 3 minor versions behind... I did try getting Ubuntu to work but version 3 simply does not support some of the features).

These may seem like dumb questions but at least in my experience, I've seen other software tools provide such work arounds when the distro repos were a few versions behind... Then again, I also do not know how podman is packaged exactly or what goes into that process so perhaps it is untenable. This is all to say, I am trying to figure out the landscape that podman is operating in.

**Comment by rhatdan** [comment]
Podman is not generating revenue as a private company, it is an open source project relying on community. Red Hat funds a lot of the development and has up2date packages available for the distros it cares about.  Red Hat does not fund developers to work on other distros other then Windows and Mac. We work with contributors in SUSE, Debian and FreeBSD. No one from Ubuntu has stepped up to maintain and upstream repo for the many versions of Podman that are out there.
