### ISSUE TITLE
clear cache of old podman machines initial images

### ISSUE THREAD

**Issue by benoitf** [containers/podman#21958]
### Feature request description

When doing `podman machine init` command on macOS, it's fetching images from `quay.io/baude/stage-podman-machine-image`

but if I do that like every day or when there is an update of the image, I have in the folder `~/.local/share/containers/podman/machine/applehv/cache` several `.raw.zst` files

As each 'machine' file is around 800MB file, it would be nice if these files are automatically cleaned-up

### Suggest potential solution

Clear old cache file when a new one is fetched.

**Comment by baude** [comment]
yes, i was frankly waiting for all the thrashing regarding naming, images, compression, etc to settle down long enough to develop a strategy to do this.  i *think* it will be safe to delete everything in cache before pulling the next image.

**Comment by baude** [comment]
i removed the mac label; this is for all providers except WSL rn

**Comment by afbjorklund** [comment]
>  was frankly waiting for all the thrashing regarding naming, images, compression, etc to settle down

I got three copies of the _same_ image, in different directories and with different names/compression :-)

**Comment by baude** [comment]
@afbjorklund that's called redundancy! its on the list for 5.1

**Comment by afbjorklund** [comment]
I thought it had the same cache "problem" with 4.9 as well

**Comment by afbjorklund** [comment]
Why are these images stored under `~/.local/share`, instead of under `~/.cache`, in the first place?

I'm pretty sure the question was asked before, just don't remember the answer. Also, they got bigger.

676M	fedora-coreos-39.20240225.2.0-qemu.x86_64.qcow2.xz
915M	1aba1f312b7b837db4b653676b88d6d3012d87e76caf2712292189da5cab20db.qcow2.zst

New compression added a few pounds, even if it does run quicker.

Not as fast as not having to decompress at all, but at least faster.

**Comment by Luap99** [comment]
This was fixed in https://github.com/containers/podman/pull/22507 AFAICT
