### ISSUE TITLE
composefs helper not found

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#22417]
Seen in [OpenQA](https://openqa.fedoraproject.org/tests/2577532#step/podman/13):
```
Error: composefs helper program not found: exec: "mkcomposefs": executable etc etc
```
Lots of these.

The string "mkcomposefs" appears only in vendor/github.com/containers/storage/drivers/overlay/composefs.go

Looks like `5.0.1-1.fc41`

**Comment by martinpitt** [comment]
It also started in podman PRs, e.g. #22415 [log](https://artifacts.dev.testing-farm.io/506ad3e5-a0b4-4e30-ace5-27563116e255/) or #22404 [log](https://artifacts.dev.testing-farm.io/c7c75b7f-92b9-42fb-88a1-31987e5edcca/). 

Pretty much the first podman-y thing that the test does:
```
+ podman rmi --all
Error: composefs helper program not found: exec: "mkcomposefs": executable file not found in $PATH
```

**Comment by martinpitt** [comment]
It's not just rawhide, it also fails in F39 (and presumably 40) in the podman-next COPR, see https://github.com/cockpit-project/cockpit-podman/issues/1670

**Comment by jelly** [comment]
A different but related issue:
```
Trying to pull ghcr.io/cockpit-project/tasks:2024-04-08...
Getting image source signatures
Copying blob sha256:4f4fb700ef54461cfa02571ae0db9a0dc1e0cdb5577484a6d75e68dc38e8acc1
Copying blob sha256:353b74d8db1cf655e87c780b9ac49f52ed72dfaa3ecc4bb0e9245e72c98a45b5
Copying blob sha256:d13d6ac68f15e1928fc96266ab7168c57888ef903e1471e51ea7a58a532c5873
Copying blob sha256:c7a97adcf92728297450ac6c91790f8f4553152d7ecec15f2f2cef26da66a443
Copying blob sha256:83b00b1559ec2e7e9e6057a4d75e6671a8849bd305e32e22e4e8037854935e2e
Copying config sha256:a58addb85c54f33d50d83f4f867b9f194ee77a25c61f6a25b42e35dfa353316e
Writing manifest to image destination
mkcomposefs: Invalid integer 628

Error: committing the finished image: failed to put layer using a partial pull: failed to convert json to erofs: exit status 1
```

https://artifacts.dev.testing-farm.io/0bad3a03-5154-429d-ac2a-27ee21b35d37/work-misc4koi6yrp/plans/all/misc/execute/data/guest/default-0/test/browser/other-1/output.txt

**Comment by edsantiago** [comment]
https://src.fedoraproject.org/rpms/containers-common/pull-request/10 submitted to revert breakage.

**Comment by rhatdan** [comment]
We only need to add composefs as a Recommends in the containers-common.spec file.

**Comment by rhatdan** [comment]
https://koji.fedoraproject.org/koji/taskinfo?taskID=116550083

**Comment by edsantiago** [comment]
This change seems to have taken a lot of people by surprise. I would like to suggest that huge breaking changes like this be reviewed by a large portion of the team before being pushed out.  "It compiles, ship it" is not a viable development strategy.

**Comment by Luap99** [comment]
> We only need to add composefs as a Recommends in the containers-common.spec file.

Well no see the error from above
```
mkcomposefs: Invalid integer 628

Error: committing the finished image: failed to put layer using a partial pull: failed to convert json to erofs: exit status 1
```

This a) clearly shows a bug as now the image is just unusable for whatever reason so this results in a major regression for the cockpit tests and b) as I wrote the storage.conf docs clearly suggests that convert_images should not be turned on by default because it is to expensive. So why did you enable that, is the documentation wrong?

And lastly AFAIK this change went never through our own upstream CI so who knowns what other problems we uncover there.

**Comment by rhatdan** [comment]
We need to test out composefs and other features to move forward on getting stuff into RHEL 9.5 and RHIVOS in the fall and this turned on in Fedora.  The best way to find issues and get the most different use cases is to try it out in Rawhide.  I have it turned on on my machine and Would ask all of you to turn it on.  This stuff never moves forward because people are too timid to turn it on.  If we have to live in a world where we can not experiment with features early in the release cycle of Rawhide, then we will never move forward for fear of breaking something.

We turned on cgroups V2 first in Rawhide, We broke and fixed stuff.  Now I am trying the same with composefs.  RHIVOS requires composefs to work and needs to be used in the world. We say Podman has support but no one has ever used it.  Similarly We need images that are written in zstd:chunked or are converted.  So we need to turn this on to actually use composefs. If it is slow then this will light a fire to fix the slowness.  We need to move Fedora forward on shipping zstd:chunked images.  Forcing people to convert images might give people incentive to use them in the first place.

zstd:chunked has somewhat supported for 4 years and no one uses,  ComposeFS has been supported in Podman 5 and no one uses it.  convert_images is supported in Podman 5 and no one uses it.  I aim to force these to be used because otherwise we will see things like RHEL being the first place this is ever tried and we will fail our customers and the greater open source community.

**Comment by rhatdan** [comment]
Release Early Release often needs to be our mantra.

**Comment by rhatdan** [comment]
@alexlarsson @giuseppe PTAL

**Comment by Luap99** [comment]
I have nothing against releasing but it must pass CI first. Pushing breaking changes without communicating them and bypassing all CI tests is not ok. If we can catch bugs already in CI then they should fixed fist before pushing them needlessly to users.

**Comment by edsantiago** [comment]
@rhatdan what I'm hearing you say is that "composefs" is something you've been aware of for a long time and wanting to get tested and out. However, from my perspective, this is the first I've ever heard of it. I think we share a common goal, in getting new functionality out as needed, but we have a serious communication disconnect.

First, we need to agree on one basic fact: **composefs has not been tested in CI**. Can we agree on that? If we can't agree on that there is no purpose in further conversation, so I'll assume we agree. Another basic fact: **things broke**. This caused panics and firefighting and emergency bandaids. This is unkind. This is a waste of time and stress for everybody.

THE CORRECT WAY: bring up the topic early. In scrum, in email, whatever. Give everyone a heads up: "this is new functionality. We need to enable it soon for X-Y-Z reasons. We need to plan dedicated focus time to hammer away at this, find problems, and get it into production."

Can we please do this from now on?

**Comment by rhatdan** [comment]
Fine.  The feature being not tested should be remedied.  Composefs has been talked about for over a year as a requirement for RHIVOS, and has had @giuseppe working on it.  Why it is not tested in CI/CD, I don't know.  Giuseppe asked me to revert the convert_image flag, and I am pushing a new version with this turned off.  Although it needs to be fixed and turned on as soon as possible.  zstd:chunked is critical to Bootc Containers.  It has been turned on for a month now in Rawhide and no one has noticed. Immutable OS is critical to the future of bootable containers as well, and that requires composefs.  ComposeFS does nothing with old fashioned images without convert_image=true.  Which means we are really not testing composefs out until we have zstd:chunked images in the wild or we convert gtar images to composefs format. 

This might have caused people a headache over night, but at least we found what is a bug with covert_image, and with the composefs package.  The package issue is fixed.  And I hope we fix convert_image in Podman ASAP.

**Comment by rhatdan** [comment]
containers-common-0.58.0-16.fc41.src.rpm has been built with convert_image=false.

**Comment by lsm5** [comment]
Action item to self (I think I have it already somewhere, need to bump it) : containers-common package should follow the same workflow for downstream builds as podman and the rest, and get built on podman-next copr with every commit to upstream main branch. The current containers-common build on podman-next is just a rebuild of the rawhide source

**Comment by giuseppe** [comment]
> containers-common-0.58.0-16.fc41.src.rpm has been built with convert_image=false.

we also need to drop `use_composefs = "true"`

**Comment by rhatdan** [comment]
Why?

**Comment by giuseppe** [comment]
because it is a breaking change.

The layout of the stored layers is different, so we can't just turn it on and off, users will also need to `system reset` their storage.

It is useful for RHIVOS and we need to enable composefs there, but we don't need to do it by default on Rawhide.  Even for the long term I am not sure yet if it is the correct default or if it should be opt-in.

**Comment by rhatdan** [comment]
If we do not turn it on in Rawhide, I have no confidence in this become supportable, we need to move as much of the world to composefs as possible.

We need to know that if a user turns on use_composefs after a storage is setup, then it hould continue to not use it but put out a warning.  So that it is not a breaking change.

**Comment by rhatdan** [comment]
This is needed for bootable container images as well RHIVOS.  We need it tested in the wild.

**Comment by giuseppe** [comment]
I am still not sure this must be enabled for anyone, or must be an opt-in for users that want the features composefs offers.  It is a trade-off, and until it is not clear the advantages are more than the disadvantages, I don't see why we should change the default for anyone on Fedora.

And we are still looking to enable zstd:chunked by default, if we enable composefs as well, we will have to deal with issues from both features and make it harder to complete the first step.

**Comment by AdamWill** [comment]
So for my part, I have now configured openQA to run the podman tests on updates that are in `critical-path-compose`, which includes podman and all its deps (inc. containers-common). Once that's been happening for a month or so, I will enable gating on that test for updates in c-p-compose, which will mean they cannot go stable if the podman test fails (including on Rawhide). That should prevent a repeat of this.

**Comment by rhatdan** [comment]
Great.
