### ISSUE TITLE
Ability to mount a volume without stopping container

### ISSUE THREAD

**Issue by vikas-goel** [containers/podman#22459]
### Feature request description

Veritas data protection appliance hosts containerized backup applications with persistent storage to keep backup images. Appliance users extends allocated storage at runtime depending on the storage utilization. Increasing storage size can result in adding new volumes. The backup application requires significant time to warm up as it is memory intensive. It loads info from disk to memory.

In order to avoid downtime, it is desired to mount new volumes without stopping containers.

### Suggest potential solution

A podman CLI to volume to a running container.

### Have you considered any alternatives?

Use of nsenter does not work.

**Comment by mheon** [comment]
This would involve a nonstandard extension to the OCI runtime, and I really do not think it is a good idea as such. You may want to open a Red Hat support case about the nsenter issue, though, it may be possible to help there (our support folks are rather familiar with it from debugging).

**Comment by vikas-goel** [comment]
Could you elaborate on “and I really do not think it is a good idea as such”?

**Comment by mheon** [comment]
Sure.

First, this isn't really a Podman ask, it's an OCI runtime ask. Podman does not create containers; we ask the OCI runtime to do so. Some of our runtimes do this in unique ways (most notably, virtual machines). Because of this, Podman tries its best to stay out of the runtime's way - we don't like directly interacting with the inside of a container after it's launched. Things that do that, like `podman exec`, are OCI runtime primitives.

There are two existing OCI runtime primitives that update existing containers - exec and update. Exec only runs commands, so it's definitely not suited for this. Update changes aspects of a created container, so it would be the correct place to put this, but right now it's deliberately limited to only altering resource limits, which can be done without entering the container. To add mounts is much more invasive - the runtime will have to safely enter a running container's namespaces and insert an additional bit of the host's filesystem. This is a large change, and runs against the intent of OCI containers (cattle, not pets), so I don't think it has much chance of being accepted upstream, which adds to the risks of implementing it.

**Comment by rhatdan** [comment]
Currect this would either need to be done with an modifications to the OCI Runtime Specification. Either add a new command or change the behaviour of the update mechanism. Because update seems to be tied to updating container resource constraints, it is not likely these changes would be accepted.

```
$ runc --help  | grep update
   update      update container resource constraints
$ crun --help  | grep update
	update      - update container resource constraints
```

The other mechanism would be to use a tool external to OCI Runtimes to modify a running container, which would need to be developed outside of Podman. Which is why we originally suggested doing this with nsenter. This is the most likely way forward with this.

Other alternatives is to volume mount a parent directory and then have volumes added as subdirs to said volume mount on the host.  These mount points will show up within the container when they are mounted.

```
# podman run -d -v /mnt:/mnt IMAGE:rslave COMMAND
# mkdir /mnt/mount1
# mount /dev/abc /mnt/mount1
```

**Comment by vikas-goel** [comment]
I understand the concerns about OCI primitives. The directory based option as mentioned in the meeting is not viable.

Use of an independent tool is fine but with the considerations that the lifecycle aspects of the volume from podman point of view are complied. For example, when a volume is mounted inside container at start, podman tracks the volume usage count. There could be many other aspects the community will know better. It can change over a period of time.

Please share a set of steps to achieve this outside the podman CLI and yet meet the lifecycle aspects.

**Comment by mheon** [comment]
Regarding lifecycle tracking - `podman volume mount` and `podman volume unmount` should allow manual management of volume lifecycle outside of Podman - mount the volume at start of use, unmount at end of use

**Comment by vikas-goel** [comment]
> Regarding lifecycle tracking - `podman volume mount` and `podman volume unmount` should allow manual management of volume lifecycle outside of Podman - mount the volume at start of use, unmount at end of use

Will `podman inspect <container>` output show the new mount point in the `Mounts` section?

**Comment by vikas-goel** [comment]
I tried mounting from host to container directly using the namespace.

1. Find container mount namespace path, say /var/lib/containers/storage/overlay/c7b9dc790ebfcd55f853bb25824194ea5155e9a9637c582f66711a134be0884c/diff
2. Create mount path, say `mkdir /var/lib/containers/storage/overlay/c7b9dc790ebfcd55f853bb25824194ea5155e9a9637c582f66711a134be0884c/diff/mnt/newvol`
3. Mount from host inside container, say `mount -o bind /mnt/newvol /var/lib/containers/storage/overlay/c7b9dc790ebfcd55f853bb25824194ea5155e9a9637c582f66711a134be0884c/diff/mnt/newvol`

1. Will this create any issue?
2. The `podman inspect`, of course, won't show this newvol as the path is mounted it's knowledge. What can be done to update the inspect output?

**Comment by vikas-goel** [comment]
@mheon , @rhatdan ,
Any thoughts on the previous comment?

**Comment by giuseppe** [comment]
> * Will this create any issue?

yes that won't work.  You are creating the mount in the wrong namespace.

You need first to open the mount on the host, then join the container mount namespace and perform the attach there.

I don't think you can achieve it with a shell script, you need a custom tool to do that.

As an easier alternative, you could create a parent mount with "shared" propagation, so each mount happening under the parent mount will be propagated inside the container:

```
# mkdir /tmp/parent
# mount --make-shared --bind /tmp/parent /tmp/parent
# podman run --rm -ti -v /tmp/parent:/mounts:shared fedora bash
# findmnt -R /mounts
TARGET  SOURCE         FSTYPE OPTIONS
/mounts tmpfs[/parent] tmpfs  rw,nosuid,nodev,seclabel,size=16240872k,nr_inodes=1048576,inode64
```

Now from the host, you can create a new mount:

```
# mkdir /tmp/parent/sub
# mount -t tmpfs tmpfs /tmp/parent/sub
```

and from inside the container:

```
# findmnt -R /mounts
TARGET        SOURCE         FSTYPE OPTIONS
/mounts       tmpfs[/parent] tmpfs  rw,nosuid,nodev,seclabel,size=16240872k,nr_inodes=1048576,i
└─/mounts/sub tmpfs          tmpfs  rw,relatime,seclabel,inode64
```

**Comment by Luap99** [comment]
This is not something we are going to provide in podman, if this is something the container runtimes should be able to do natively then it should be proposed to crun/runc, etc... as this level of mounting is not what podman deals with
