### ISSUE TITLE
race: podman auto-update barfs when containers disappear

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#23279]
In terminal 1:
```console
$ while :;do podman run --rm quay.io/libpod/testimage:20240123 date;done
```
In terminal 2:
```console
$ while :;do bin/podman auto-update;done
Error: container 2815a2a15731c266cc447d5e61becbbdc1aee31580e2c915ef8162ea1ded0617 does not exist in database: no such container
Error: container 92bb729f47f1f7400fb8f90511a6406e19ee67c637905d63bb892036d4b86987 does not exist in database: no such container
Error: container 5a58708f367a36f2f323dcc9e1fb45ef8d83a892a9ef4d819408ee36d1af93cd does not exist in database: no such container
Error: container 8aa0908c890a67d55d1a0984ac47e5eef92683af56ef010a8f4e4bb17b861891 does not exist in database: no such container
...etc etc etc
```
Expected: no output from `auto-update` command, ever.

**Comment by edsantiago** [comment]
Same with `podman system df`

**Comment by mcv21** [comment]
This issue is causing us issues in our production environment - Ceph periodically creates some short-lived containers (e.g. checking the state of OSDs on a node), and we've observed podman-auto-update losing this race and erroring out (which our alerting system picks up as a failure) - for an example syslog paste see https://phabricator.wikimedia.org/P66707

**Comment by Luap99** [comment]
I take care of it, that should be trivial to fix.
