### ISSUE TITLE
Quadlet incorrecly identifies Quadlet based Pod as non-Quadlet based

### ISSUE THREAD

**Issue by AlexNPavel** [containers/podman#23381]
### Issue Description

When trying to create a Container with the Pod field set to the `systemd-podname`, where `podname` is the name of a pod defined by a `podname.pod` file, podman-system-generator throws the following error:
 ```
converting "mycontainer.container": pod podname is not Quadlet based
```

To solve this, I need to set the name of the pod to `podname.pod` in the Pod definition. I believe the code used to identify Quadlet based pods is incorrect: https://github.com/containers/podman/blob/2015137eee33353bf9eec3c4c01f5614878c39fd/pkg/systemd/quadlet/quadlet.go#L2079-L2081

### Steps to reproduce the issue

Steps to reproduce the issue
1. Create a podfile called `mypod.pod` in `~/.config/containers/systemd`.
2. Create container file called `mycontainer.container` in `~/.config/containers/systemd` with the field `Pod=systemd-mypod` set under [Container]
3. Run `/usr/lib/systemd/system-generators/podman-system-generator --user --dryrun` to see error

If `PodName` is set to `mypod.pod` in the pod file and `Pod` is set to `mypod.pod` in the container file, it works as expected.

### Describe the results you received

An error generating the service file.

### Describe the results you expected

A service for my container that connects to the pod defined in the pod file

### podman info output

```yaml
$ podman version
Client:       Podman Engine
Version:      5.1.1
API Version:  5.1.1
Go Version:   go1.22.3
Built:        Mon Jun  3 17:00:00 2024
OS/Arch:      linux/amd64

$ rpm -q podman
podman-5.1.1-1.fc40.x86_64
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

No

### Additional environment details

OS is Aurora-DX from the Universal Blue project.

**Comment by ygalblum** [comment]
Hi @AlexNPavel,

Currently, Quadlet supports the `Pod` keyword only for Quadlet based pods. The reason is to be able to connect between the generated systemd service unit files (with keywords such as `BindsTo`, `After`, etc.). This is also states in the man page: https://docs.podman.io/en/latest/markdown/podman-systemd.unit.5.html#pod

In general, in order to link between different Qualdet units, the value should be that of the Quadlet file (in your case `mypod.pod`) and not the name of the resources generated by it (in your case `systemd-mypod`). The same goes for connecting with `.network`, `.volume`, etc. The reason is that the name you provide does not guaranty that in fact such a Quadlet file exists, even if the name matches its default name pattern. Keep in mind that the user can change the default behavior by setting `PodName`.

So, the behavior you are describing is in fact the desired one.
