### ISSUE TITLE
remote: start --attach: can only attach to created or running containers: container state improper

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#23757]
Looks like one of those long-time flakes that is no longer masked by ginkgo retry:
```
# podman something-something mycontainer
...
# podman start -a mycontainer
..."Error attaching to container xxx: can only attach to created or running containers: container state improper"
```
(Suggestion: instrument that error message to display what the container state actually is)

* debian-13 : int remote debian-13 root host sqlite [remote]
  * PR #23679
    * [08-21 22:11](https://api.cirrus-ci.com/v1/artifact/task/4655418843070464/html/int-remote-debian-13-root-host-sqlite.log.html#t--Podman-run-podman-run-limits-test--1) in Podman run podman run limits test
* fedora-40 : int remote fedora-40 root host sqlite [remote]
    * [08-19 08:01](https://api.cirrus-ci.com/v1/artifact/task/5415255935811584/html/int-remote-fedora-40-root-host-sqlite.log.html#t--Podman-run-podman-run-limits-test--1) in Podman run podman run limits test
* rawhide : int remote rawhide root host sqlite [remote]
  * PR #23751
    * [08-26 08:57](https://api.cirrus-ci.com/v1/artifact/task/5611875310764032/html/int-remote-rawhide-root-host-sqlite.log.html#t--Podman-privileged-container-tests-podman-privileged-should-restart-after-host-devices-change--1) in Podman privileged container tests podman privileged should restart after host devices change

| x | x | x | x | x | x |
| ---: | ---: | ---: | ---: | ---: | ---: |
| int(3) | remote(3) | fedora-40(1) | root(3) | host(3) | sqlite(3) |
|  |  | debian-13(1) |  |  |  |
|  |  | rawhide(1) |  |  |  |

**Comment by Luap99** [comment]
I think I fixed such races for the local client recently: https://github.com/containers/podman/commit/3280da0500e9f78901e86575ba2bdffd83fd1b66

It would be interesting to know what state we are actually in when this fails.  Looking at the server API endpoint (AttachContainer()) I see bunch of races around our state handling, unlock state checks, that are used to decide if we have to init or not, we are unlocked after ctr.Init() meaning it can get cleaned up again... The libpod internal attach code need a container in the right state so it errors out.

So my assumption here is podman-remote start -a  or (podman run) exits quickly and it will not wait for cleanup. Cleanup will only happen with the podman container cleanup process. However because we are so fast it can be that the second start -a is already past the ctr.Init() on the server and only then the cleanup process gets the lock and cleans up again cause us to be in the wrong state. Overall I think this must be moved all under on single look in the endpoint in order to work.
