### ISSUE TITLE
podman pull zstd:chunked-image, with vfs: not supported

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#24308]
WHEW! It's vfs:
```console
# bin/podman --storage-driver vfs pull quay.io/libpod/testimage:20241010   <<< this was pushed to quay with zstd:chunked
Trying to pull quay.io/libpod/testimage:20241010...
Getting image source signatures
Copying blob a3ed95caeb02 done   | 
Error: copying system image from manifest list: reading blob sha256:d005489f1e59bed02315c1c34bb95b3f46a970a5fd20cdc73c93c6e279689dde: not supported
```
This is a highly hacked podman with all of @mtrmac's changes to c-s c-i c-c c.  Full patch history available on request, but I suspect it will not be needed so I'm saving myself that time.

**Comment by mtrmac** [comment]
@edsantiago Thanks for tracking this down! A detailed reproducer is indeed unnecessary.


After https://github.com/containers/storage/pull/2118 , we now default to _not_ falling back if a chunked pull fails.

Here, `c/storage/pkg/chunked.GetDiffer` finds a valid chunked input, and returns a success, _regardless of the current graph driver_.
Afterwards, c/image calls `PrepareStagedLayer`; that fails with the VFS driver with `ErrNotSupported` because it does not implement `DriverWithDiffer`. And because `ErrNotSupported` is not `ErrFallbackToOrdinaryLayerDownload`, this is a hard failure.

One way to handle this would be to return `ErrFallbackToOrdinaryLayerDownload` from `GetDiffer` if the graph driver does not support chunked pulls.

@giuseppe How will the planned options to always enforce composefs affect this? Would we just fail in `GetDiffer`? Or, maybe, should `storage.GetStore` immediately fail with an invalid composefs + graph driver combination?

**Comment by mtrmac** [comment]
https://github.com/containers/image/pull/2607 should improve the error message, but it does not actually allow things to work.

**Comment by mtrmac** [comment]
Confirmed by manual testing that this is indeed the code path from https://github.com/containers/image/pull/2607 .

**Comment by mtrmac** [comment]
RFC fix, at least to start the conversation: https://github.com/containers/storage/pull/2140 .

**Comment by mtrmac** [comment]
Confirmed that this works as expected with `main` as of 07683280c8dd48f4b620a95be9fba3b26ca455c2 👍 

With partial pulls enabled, debug log says
```
Failed to retrieve partial blob: graph driver vfs does not support partial pull
```
and we fall back.

With partial pulls + `convert_images`:
```
partial pull of blob sha256:…: graph driver vfs does not support partial pull but convert_images requires that
```
