### ISSUE TITLE
consistent behaviour between docker and podman-docker when using --user with root image

### ISSUE THREAD

**Issue by fekir** [containers/podman#24481]
### Feature request description

If I have a docker image with only the root user, currently, when executing something like

~~~~
docker --user "$UID" "$HOME:/home" -ti --rm <container name> touch /home/a;
cat "$HOME/a";
rm "$HOME/a";
~~~~

the file created by touch can be deleted from the current user

with podman (version 5.2.5), the file cannot be deleted, unless I also use `--userns=keep-id`, or remove `--user "$UID"` (because in that case the user in the image is root)

~~~~
docker --user "$UID" --userns=keep-id "$HOME:/home" -ti --rm <container name> touch /home/a;
cat "$HOME/a";
rm "$HOME/a";
~~~~

So far, so good; but the different behavior is problematic when installing `podman-docker`.

Because at that point, underlying tools calling `docker` should (somehow) query if docker is really docker or not, and add or remove flags.

### Suggest potential solution

I would like

~~~~
docker --user "$UID" "$HOME:/home" -ti --rm <container name> touch /home/a;
cat "$HOME/a";
rm "$HOME/a";
~~~~

to work both with `docker` and `podman-docker`.

I guess that the most fool-proof approach would be to attach `--userns=keep-id` automatically if 

 * the parameter `--user` is provided

As a possible additional condition, do that only if `podman` has been called through the wrapper script `docker`

### Have you considered any alternatives?

Some workarounds for my workflows:
  
 * explicitly verify if podman is available, and use it instead of docker
 * query through `docker --version` if docker is podman or not, and adjust the parameter accordingly
 * modify the wrapper shell script `docker` provided by `podman-docker` and add `--userns=keep-id` if `--user` has been passed as parameter
 * provide my own wrapper shell script `docker` instead of installing `podman-docker` that verifies if podman is available and adds `--userns=keep-id` if `--user` has been passed as parameter

**Comment by Luap99** [comment]
That doesn't really make sense. The reason for the difference is that podman run rootless while docker runs as root. If you run sudo podman ... it will behave the same and you do no need --userns-keep-id

Adding any of the --userns/--user options automatically will just break other things and cause even more confusion for users of the docker wrapper when it will behave differently compare to direct podman calls.

I would say if you need this use your own script to handle it.

**Comment by fekir** [comment]
> That doesn't really make sense. 

If you consider `docker` and `podman` in isolation, it does not.

But for `podman-docker`, as proxy for `docker`, I think it does.


> Adding any of the --userns/--user options automatically will just break other things 

Do you have a hint of what other things can break?

**Comment by Luap99** [comment]
Adding --userns=keep-id already implicitly  adds --user $UID:$GID and if the image is not set up to run under that uid it will not work.
And if --user is already set to your uid then using userns=keep-id might be what you want if you have to share files but it also makes it somewhat less secure because the container runs as the same id as your user so there is less privilege separation. One should avoid running under the same uid as the host, of course if the container use uid 0 by default then the default mapping would also allow this.

Another thing with user namespace is how they interact with capabilities: https://blog.podman.io/2023/12/interaction-between-user-namespaces-and-capabilities/ so silently adding --userns will change the behavior when the namespaces are shared.

It would also not work for pods as the user namespace must be given for the pod not container but I guess if you have a script using docker you don't care about pods. 


In general comparing rootful docker against rootless podman is not fair, you see the same thing if you run dockerd rootless AFAIK.

**Comment by fekir** [comment]
> One should avoid running under the same uid as the host, of course if the container use uid 0 by default then the default mapping would also allow this.

Which, sorry for doublechecking, means that using `--user` for a container that uses "uid 0 by default " does not make it less secure, correct?

> [...] if you have a script using docker you don't care about pods.

Yes, exactly.

This why I said it makes sense for `podman-docker`, not `podman`.

I agree it is not nice that `podman`behaves differently when invoked as `docker`, but it is a standard practice for some tools, and it would make transitioning from one tool to another (hopefully) less error-prone.
But it seems that because of capabilities, this will not be possible.

AFAIK there is no `--userns=keep-id` that acts only on the mounted volumes, so it seems there is no way to write data to a mounted volume from `docker` and `podman-docker` in a consistent way; is that correct?
