### ISSUE TITLE
podman is stuck at version 3.4.4 in ubuntu 22.04

### ISSUE THREAD

**Issue by thebigbone** [containers/podman#24824]
The podman package hasn't been updated in a while on ubuntu 22.04. It's a broken version. I think it would be fair to specify it in the docs.

**Comment by antonkulaga** [comment]
This is a massive blocker for wider podman adoption as most of the servers are still on 22.04 and admins refuse to upgrade (for obvious reasons). Is it because you are funded by Fedora and you want to push people away from Ubuntu?

**Comment by rhatdan** [comment]
Most of the engineers are funded by Red Hat and also work on Fedora.  We really do not care about the underlying Distribution. We are fine with users running any Linux Distribution. Or Mac or Windows.

**Comment by antonkulaga** [comment]
I am developing and [easy-to-run opensource-chat](https://github.com/antonkulaga/just-chat) with LLM-agents and I really want to make it one-click runnable. So far, I really want to make it mostly podman-based so with simple podman-compose they can run it in no time. I also try to avoid Docker due to it being security hazzard. However, most of the users get stuck with podman 3.x problem as Ubuntu-based distros are still first choice for home users and are not ready to spend 2-3 hours of building from source or upgrading to latest distro. Is there any advised way for them to get podman running quicker? I saw you have flatpak for podman desktop, but it does not contain podman itself. I also tried binary from github but from what I understood you only published the client.

**Comment by rhatdan** [comment]
Strange, I am building [RamaLama](https://github.com/containers/ramalama) which sounds somewhat similar to what you are building. Contributors in the past have made an apt store to provide newer packages for Ubuntu, but am not sure of its status.

**Comment by winternewt** [comment]
@rhatdan these backports are no longer maintained it seems, at least not when somewhat new version is needed, specifically I ran into this [problem](https://github.com/containers/podman/issues/21419) when doing `podman pull` from docker's registry.

After some trial and error I managed to get 4.9.3 (version from 24LTS) working on 22.04 after building from source, process is mostly covered by podman's docs, except for an existing golang backport, which saves quite a lot of time and effort.
Couldn't get v.5 to work from the get go because there's no passt for 22 and building passt / netavark with deps is no trivial task.

So a quick'n'dirty solution that turned out sufficient so far for my setup at least:
```bash
sudo add-apt-repository ppa:longsleep/golang-backports
sudo apt update
sudo sysctl kernel.unprivileged_userns_clone=1
sudo apt install git build-essential btrfs-progs gcc git golang-go go-md2man iptables libassuan-dev libbtrfs-dev libc6-dev libdevmapper-dev libglib2.0-dev libgpgme-dev libgpg-error-dev libprotobuf-dev libprotobuf-c-dev libseccomp-dev libselinux1-dev libsystemd-dev make containernetworking-plugins pkg-config uidmap runc
git clone https://github.com/containers/podman.git
cd podman/
git checkout v4.9.3
make
sudo make install
podman --version
```
