### ISSUE TITLE
podman cp, with volumes + tarfile + exact name match, is a NOP

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#3550]
Looks like an obscrure corner case of #3059 
```
# podman volume create v
v
# vdir=$(podman volume inspect -f '{{.MountPoint}}' v)
# ls -la $vdir
total 8
drwxr-xr-x. 2 root root 4096 Jul 10 17:55 .
drwx------. 3 root root 4096 Jul 10 17:55 ..
```
Now create a tarball:
```
# mkdir mysubdir
# echo this is a file >mysubdir/myfile
# tar cf mysubdir.tar mysubdir
```
Then create a container, mounting the volume _using the same name as the subdirectory in the tarball_. `podman cp` of the tarball into the container will silently fail:
```
# podman create --name foo -v v:/mysubdir alpine
70f1ad4ac78d5933fd2e0ebefdeb46435c38da382c06b77de00073e63f18984b
# podman cp - foo:/ < mysubdir.tar
# ls -la $vdir/
total 8
drwxr-xr-x. 2 root root 4096 Jul 10 18:02 .
drwx------. 3 root root 4096 Jul 10 17:55 ..
```
`cp` into the volume subdirectory works:
```
# podman cp - foo:/mysubdir < mysubdir.tar
# ls -l $vdir/
total 4
drwxr-xr-x. 2 root root 4096 Jul 10 17:57 mysubdir
# ls -l $vdir/mysubdir/
total 4
-rw-r--r--. 1 root root   15 Jul 10 17:57 myfile
```
podman-1.4.4-3.fc30

**Comment by rhatdan** [comment]
@QiWang19 PTAL

**Comment by QiWang19** [comment]
the issue is after extracting the tar archive, if it returns a folder has the same name with the volume, podman copies it to the containerMountpoint/volumename not the volumePath. Is it possible to fix this?

**Comment by mheon** [comment]
We may want to look into having `podman cp` join the mount namespace of the container - it would solve all these pathing gotchas...

**Comment by QiWang19** [comment]
how to let `podman cp` join the mount namespace?

**Comment by rhatdan** [comment]
@QiWang19 @jwhonce I think we talked about this a while ago, but we still have not pursued it, correct?

**Comment by mheon** [comment]
I think we may want to close this one and open a tracker for a rewrite of `cp`

**Comment by mheon** [comment]
I'll leave it open until that happens, though. Better than losing it.

**Comment by jwhonce** [comment]
I thought we had a card for the rewrite but I cannot find it now.  @mheon did it get deleted?

**Comment by vrothberg** [comment]
Friendly ping.

**Comment by rhatdan** [comment]
@QiWang19 Any chance you can look at this?

**Comment by QiWang19** [comment]
I had a PR to fix this by mounting the volumes but hasn't been merged for security reasons. 
We have a card for rewriting the `podman cp`, may be this should be fixed after a new version of podman cp.https://issues.redhat.com/browse/RUN-531

**Comment by rhatdan** [comment]
@QiWang19 Could you talk to @nalind on this to see if his work on COPY can be used to fix this.

**Comment by rhatdan** [comment]
@nalind @QiWang19 Any progress?

**Comment by rhatdan** [comment]
@jwhonce I think this one is needed to bubble up?

**Comment by vrothberg** [comment]
As much as I had hoped this would be fixed with the latest copy work, it is not.

Note that there are differences between a running and a created container, as nothing's yet mounted on the latter.

Current observation using https://github.com/containers/podman/pull/8747:
* A) Copying  the tar file to `ctr:/` succeeds but nothing's copied.  Even for a running container.
* B) Copying the tar file to `ctr:/mysubdir` works as expected as can determine the volume _before_ extracting the tar file.

I think that there are two issues ton unpack in A):

1. When the container is _running_, I would expect the contents to be copied over to the volume mount.  I suspect that /mysubdir being mounted volume creates some issues in `buildah/copier`.  Maybe it's trying to remove the directory and silently fails? (just guessing)
2. `buildah/copier` has no knowledge of any mounts or volumes in the container.  Currently, Podman is doing all the magic to map a container path to a volume or mount to eventually resolve the path on the host.

@nalind, I need your input for both 1. and 2.  What would be pretty dope is to give `buildah/copier` a `map[string]string` that allows for translating a path in the container (i.e., relative to the specified root) to a path on the host (i.e., outside the specified root).  It would be nice for a caller to just iterate over a container's mounts, throw the source/destination pairs into a map and not having to worry any further.  _But_ I imagine the need to work in and outside the potential chroot to be a tricky challenge.

**Comment by rhatdan** [comment]
This still exists.

**Comment by vrothberg** [comment]
Need some massaging in `buildah/copier` to get that to work.

**Comment by vrothberg** [comment]
I just went back to the issue and it's working now. @edsantiago can you confirm?

**Comment by edsantiago** [comment]
@vrothberg I'm confused. I just copy/pasted the exact reproducer in the original comment (changing 's/P/p/' in mountpoint), and the problem still persists with podman @ e81457dc8e6632f4e9c7a4d240c9a73e8d509bb3. Root and rootless. In what setup did you make it work?

**Comment by vrothberg** [comment]
@edsantiago, I also used the reproducer and ran rootless.  I didn't copy though, so maybe I had a typo.  It was almost too good to be true, so I wanted a double check.

**Comment by nalind** [comment]
I think the difference in your experience is going to come down to whether or not extracting the archive into a location outside of a volume attempts to put content below the directory where the volume is mounted in the container, e.g. an archive containing "tmp/foo" being extracted into "/", where "/tmp" is a mount point.

**Comment by vrothberg** [comment]
@nalind, iterating on https://github.com/containers/podman/issues/3550#issuecomment-748003131: What's your take on passing a map to translate paths to the copier?

Note: copying to running containers works. The data is also copied up to the volume once a created container starts.

**Comment by nalind** [comment]
`Rename` maps are an option that the API provides, but volume are located outside of the rootfs on the host, so `Put` chrooting into the rootfs to write things is going to thwart efforts to solve this with that.

You could try starting `Put` multiple times, once per volume, with each invocation reading from a pipe, and examine each item in the stream that `Get` creates as it goes.  You could then adjust `Name`s and `Linkname`s in headers read from `Get`, factoring in where they should end up, and feed the headers and their corresponding file contents into right `Put` pipe.

Hard links will complicate that, though, since it's possible that hard links would refer across rootfs/volume boundaries, and `Put` can't create a hard link to a file that it can't access.

**Comment by rhatdan** [comment]
@edsantiago @vrothberg @nalind What is the latest on this one?

**Comment by edsantiago** [comment]
Issue still present in main @ fe0bb28e68fc8b0870301956482ac7e93ac49fda

**Comment by rhatdan** [comment]
@mheon Could you look at this one?

**Comment by edsantiago** [comment]
Still present in main @ a866a2f159f94976277d8a3a9459724af0b0f62f

**Comment by rhatdan** [comment]
@flouthoc any chance to look at this?

**Comment by edsantiago** [comment]
Abandoning. This will never get fixed.
