### ISSUE TITLE
RFE: Support network aliases

### ISSUE THREAD

**Issue by larsks** [containers/podman#4530]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

In addition to DNS-based container discovery using the container name, Docker permits an operator to assign aliases to the container. This can be tremendously useful if you've got a container name that looks something like "postgres-12-postgis", and you would like to be able to simply refer to it as "database":

    docker run --network=mynetwork --network-alias=database ...
    
The `podman-run` man page currently documents the `--network-alias` option, but lists it as "Not implemented".
    
**Additional environment details (AWS, VirtualBox, physical, etc.):**

Implementing this would permit `podman-compose` to support `docker-compose.yml` files that include [aliases](https://docs.docker.com/compose/compose-file/#aliases).

**Comment by mheon** [comment]
I imagine the code for dnsname to support this won't be particularly bad,
but it could be a real pain to plumb it through to CNI

**Comment by baude** [comment]
I like the idea as well; it would break current dnsname api (i imagine passing a []string of names instead of a string).  i double checked the behavior with docker and like us, they require a new network to be made so that name resolution works.  I guess --network-alias becomes a throw-away otherwise?

**Comment by larsks** [comment]
> and like us, they require a new network to be made so that name resolution works.

Well, sort of. They don't support name resolution on the default bridge network because they are preserving legacy behavior (such as the support for `--link`, which is otherwise much less useful than DNS).

I don't see any reason to follow that model. I would say that `--network-alias` should work for any network on which the `dnsname` plugin is enabled, which may include the default network on `cni-podman0` if someone has made the appropriate change to the configuration.

**Comment by rhatdan** [comment]
Any movement on this?

**Comment by baude** [comment]
We discussed this today and how to apply it to Podman.  We believe that while this RFE has merit, any implemented would undercut that same merit with performance hits.  Using Docker as an example of implementing this shines light on at least one (maybe more) use issues:

In Docker, suppose you add a container named `foo`. You now have a container named `foo` and a dns entry for `foo`.  If you add another container named `foo-db` with --network-alias `foo`, dns will not point at the new `foo-db` container.  We think that should never happen.  The reverse is also true I believe.

Preventing the first case is reasonable easy but is a perf hit to Podman.  If a new container with a network-alias of `foo` is created, we could check for any containers named `foo` and and network aliases called `foo`.  The perf hit is fenced off and only impacts those using network-aliases.  However, it is the reverse case that is troublesome.  In the event that a container exists with an alias of `foo` but the user creates a new container named `foo`, there would not be a perf hit to container creation to hit that.

In our discussion, that is where the benefit/cost begins to erode.  We will keep this issue open however.

**Comment by rhatdan** [comment]
@baude Still want this issue opened?

**Comment by disaster123** [comment]
I would like to run jitsi through podman but i'm unable todo so because the docker-compose heavily uses network aliases:
https://github.com/jitsi/docker-jitsi-meet/blob/master/docker-compose.yml

currently i've no idea on how to run this with podman.

**Comment by baude** [comment]
@disaster123 I've outlined how we could do it and the up/downsides of it.  Do you have a better way to implement this or better yet, care to contribute?

**Comment by rj-gp** [comment]
I also make use of network aliases when creating containers with a network. And I also have no idea how to workaround this with podman. I thought I could do the following:
1. create containers (podman create)
2. podman cp containers:/etc/hosts to someplace
3. edit these container /etc/hosts files with appropriate aliases, then copy them back into the containers, and then start the containers

However this leads to another issue. The (not running) container:/etc/hosts files do NOT contain a line for the container host name.

For (not running) containers, created with docker create, the container:/etc/hosts contains this line. In order to properly edit the /etc/hosts files we need the actual ip addresses that podman has assigned them.

For podman containers the container:/etc/hosts file only contains the hostname when actually running. eg
podman exec container cat /etc/hosts

The missing --network-aliases is a currently a showstopper for me.

**Comment by mheon** [comment]
The copy workflow isn't really supported with Podman (it looks like Docker does not handle that file as a bind mount, while we do - so the file in the container when it's not running will be mounted over even if changed). I think that launching the container once and editing `/etc/hosts` within the container would work, though - would that be sufficient?

**Comment by mheon** [comment]
Ahhh, nevermind - it looks like we recreate `/etc/hosts` for each run of the container, to account for changing internal IPs. Hmm.

**Comment by rj-gp** [comment]
Being a podman newby I thought I was most likely missing out on something obvious on a better way to handle a network alias. But then I discovered this RFE and after reading the comments I am apparently not missing out.

**Comment by mheon** [comment]
We could potentially do this as part of the more-general aliases code I want to add, but that could be a way off, given our current focus on the new HTTP API

**Comment by niklas88** [comment]
Just wanted to add my two cents in saying that I too think this feature is really important and worthwhile. For me it is the one major `podman` difference that drives me to use `docker` instead, even though I really prefer `podman`s simplicity and daemon less design. Over at my friends `gantry` project this is also the one thing stopping `podman` support
https://github.com/ad-freiburg/gantry/issues/46

As for @baude 's concerns, while I do get the naming clashing problem I'm really not convinced this is anything but theoretical and/or user error. If the user configures name clashes that's really their own fault and resolving clashing names to either entity in whatever preference sounds like perfectly okay behavior in that situation and nothing `podman` should spent CPU time on preventing. Especially since it will not be that hard to debug and even on manual setups shouldn't easily happen by accident.

This is especially true since I feel like in 99% of cases the aliases and container names will be created by a tool like `podman-compose` or `gantry` that creates them from a configuration that it can easily check for such name clashes without any noticeable performance overhead.  To me `podman` really focuses on local/small setup use and that benefits so immensely from compose style tools that making them possible should IMHO be a priority.

**Comment by disaster123** [comment]
+1

**Comment by rj-gp** [comment]
I agree with @niklas88 in that any name clash issues are the users issue/fault.
This shouldn't be podman's job to "coddle" us users.

**Comment by rhatdan** [comment]
I think PRs would help to move this along.  Hint, Hint.

**Comment by rhatdan** [comment]
@baude @niklas88 Where are we on this one?

**Comment by rj-gp** [comment]
I don't know about @baude and @niklas88 but I am still needing this before I can actually use podman.

**Comment by rhatdan** [comment]
@baude @mheon I think we should bring this one back to the foreground.

**Comment by mheon** [comment]
@rhatdan Only so much time in the day :smile:

**Comment by rhatdan** [comment]
Understood.

**Comment by rj-gp** [comment]
> @baude @mheon I think we should bring this one back to the foreground.

Yes, Yes, Yes!!...

**Comment by mhmr** [comment]
I understand this might still open issue, but is there anyway to go around this, any currently existing feature that we can use to go around it?

**Comment by trusch** [comment]
@mhmr I think the only (really hacky) way of doing this right now is to exec into the rootless-cni-infa container and update the `/run/containers/cni/dnsname/default/addnhosts` file after you started (not only created) all of your containers. You can then look in that file for your container name and just append all the aliases that you want (like `sed -i 's/alpine1/alpine1 alpine_one/' /run/containers/cni/dnsname/default/addnhosts`)

**Comment by mheon** [comment]
This is actively being worked on and will probably make it into Podman 2.2

**Comment by rj-gp** [comment]
> This is actively being worked on and will probably make it into Podman 2.2

Fantastic!

**Comment by baude** [comment]
merged today upstream.
