### ISSUE TITLE
podman-pod-create --network slirp4netns is unsupported for root containers

### ISSUE THREAD

**Issue by zem** [containers/podman#6097]
I am not sure why that switch is simply missing, it is supported when you create an unpriviledged pod so why not be able to do slirp4netns as root? 

Reasons:
- I cant access a port from another container that is published on the host, I probably just dont get it yet  how to resolve the IP address other pods elegantly out of the box. 
- Published ports on bridged networking do not bind on ipv6 slirp4netns does and translates.

**Comment by mheon** [comment]
We originally only implemented a small subset of `--network` for pods (because of the way creating the infra container is handled, parsing needs to be very different for both, and rewriting the complicated parsing for `--network` was put off to later). This definitely sounds doable, though, it would just need some additions to the existing parsing logic.

**Comment by rhatdan** [comment]
@mheon Any update on this issue?

**Comment by mheon** [comment]
No. Should be fairly simple to implement, but I've never found time.

**Comment by rhatdan** [comment]
@ashley-cui PTAL

**Comment by ashley-cui** [comment]
Any container that joins the a slirp pod would also has slirp as the network mode, correct?

**Comment by mheon** [comment]
The containers except the infra container should not be different - the containers, except the infra, will still join the infra container's network namespace.
