### ISSUE TITLE
Document that in rootless mode, uidmap is in terms of the default mapping, not host uids

### ISSUE THREAD

**Issue by rkjnsn** [containers/podman#6123]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

I have a container that accesses a device as a non-root user (in the container) that I'm trying to run as a non-root user (outside of the container). To have access to the device, I need that user in the container, not root, to be mapped to my user ID, but I still need the containers entry point to be started as uid 0 (in the container).

It seemed this should be doable with --uidmap, which is documented as mapping container uids to host uids, so I kept trying variants of `--uidmap=0:1065536:1000 --uidmap=1000:1000:1 --uidmap=1001:1066536:64536` to no avail. (My user's subuid entry is 1065536:65536).)

After, a lot of poking, prodding, reading random bugs, and playing with `--userns=keep-id` (which I can't use in this case, since I still need the entry point started as container uid 0, and which wouldn't work in the general case anyway, since my host uid and the relevant container uid aren't guaranteed to match), I eventually discovered that, when running rootless, the provided uidmap is actually applied *after* the default uidmap has already been applied, so what I actually needed to specify was `--uidmap=0:1:1000 --uidmap=1000:0:1 --uidmap=1001:1001:64536` to get the mapping I wanted, which is not at all what I would expect from reading the documentation.

If this is, in fact, the intended behavior, the podman-run man page should be updated to explain how uidmap works in rootless mode. If this is not the intended behavior, I guess consider this a bug report for uidmap rather than a documentation bug. :slightly_smiling_face: 

**Additional information you deem important (e.g. issue happens only occasionally):**
If it's relevant, I'm using cgroups v2.

**Output of `podman version`:**

```
Version:            1.9.0
RemoteAPI Version:  1
Go Version:         go1.13.10
Built:              Tue May  5 17:23:34 2020
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  gitCommit: ""
  goVersion: go1.13.10
  podmanVersion: 1.9.0
host:
  arch: amd64
  buildahVersion: 1.14.8
  cgroupVersion: v2
  conmon:
    package: Unknown
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.15, commit: 1bddbf7051a973f4a4fecf06faa0c48e82f1e9e1'
  cpus: 8
  distribution:
    distribution: gentoo
    version: unknown
  eventLogger: journald
  hostname: rkjnsn-laptop-linux
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 1065536
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 1065536
      size: 65536
  kernel: 5.4.28-gentoo
  memFree: 4033044480
  memTotal: 16663584768
  ociRuntime:
    name: crun
    package: Unknown
    path: /usr/bin/crun
    version: |-
      crun version 0.10.6
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  rootless: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: Unknown
    version: |-
      slirp4netns version 1.0.1
      commit: 6a7b16babc95b6a3056b33fb45b74a6f62262dd4
      libslirp: 4.3.0
  swapFree: 17042067456
  swapTotal: 17179693056
  uptime: 113h 30m 26.53s (Approximately 4.71 days)
registries:
  search:
  - docker.io
  - quay.io
  - registry.fedoraproject.org
store:
  configFile: /home/rkjnsn/.config/containers/storage.conf
  containerStore:
    number: 2
    paused: 0
    running: 0
    stopped: 2
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: Unknown
      Version: |-
        fusermount3 version: 3.9.1
        fuse-overlayfs: version 1.0.0
        FUSE library version 3.9.1
        using FUSE kernel interface version 7.31
  graphRoot: /home/rkjnsn/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: btrfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 2
  runRoot: /run/user/1000/containers
  volumePath: /home/rkjnsn/.local/share/containers/storage/volumes
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Physical Gentoo machine

**Comment by mheon** [comment]
I think this sounds like how things should work, so this is just a matter of documentation.

**Comment by mheon** [comment]
@giuseppe Mind taking a crack at this?

**Comment by giuseppe** [comment]
@mheon yes sure.

@rkjnsn it would take me a while before I get to work on this issue, would you like to improve the documentation with your findings and submit a PR?  I'll be happy to review it

**Comment by rhatdan** [comment]
I am wondeing in rootless mode if we are doing this incorrectly.

I believe it would be a lot easier to understand if everything was relative to the current user namespace.

Example if I am in rootless mode

podman unshare cat /proc/self/uid_map
         0       3267          1
         1     100000      65536

Then if I run a container
podman run --uidmap 0:10000:1000

Then this would setup a container with user map of 
0 10001 1000

I would think this is a lot easier to underand and comes closer to what users would expect.  Rather then failing always.

**Comment by rhatdan** [comment]
@giuseppe Any change you had time to play with this?

**Comment by akvadrako** [comment]
It would also be useful to keep **uidmap** relative to the default uidmap because you can specify the "current user" in a uidmap. For example, to run a container as user 100 and mapping it to the current user, you could do:

    podman run --user=100 --uidmap=100:0:1

**Comment by rhatdan** [comment]
@giuseppe PTAL

**Comment by anishp55** [comment]
any update on this?  i am trying to do something similar but can't figure out the syntax.  

```podman run --user=1001 --uidmap=1001:0:1  -d  --name postgres-test -e POSTGRESQL_PASSWORD=password  bitnami/postgresql:11 &&  podman logs --follow  postgres-test```  results in

```Error: error creating container storage: error creating an ID-mapped copy of layer "d9a25cd3d30c9563fb645b2d239f40ac99f43eb954b62e8165a7dc4f8e03f52f": exit status 1: error during chown: error mapping container ID pair idtools.IDPair{UID:0, GID:0} for "bin/chgrp" to host: Container ID 0 cannot be mapped to a host ID```

**Comment by rhatdan** [comment]
@giuseppe I think we need to figure a better UI for people attempting to do stuff like this for rootless containers.

**Comment by merusso** [comment]
@anishp55 , I've been trying something similar and also getting an error I couldn't figure out. I read through the new docs for `--uidmap` several times but couldn't quite follow it, and I didn't see any explanation for this behavior.

Podman version: 3.0.1

/etc/subuid:
`ubuntu:100000:65536`

Error:
```
$ podman run --user 1001 --uidmap=1001:0:1 docker.io/library/ubuntu:focal
Error: OCI runtime error: User namespaces enabled, but no user mapping found.
```

I realized after re-reading the OP that "--uidmap=0:1:*" was essential, in addition to the desired UID you want to map. Here's an example command that works successfully:

```
$ # Map container user 1001 to the current host user, and map container user 0 to 1
$ podman run --user 1001 --uidmap=1001:0:1 --uidmap=0:1:1 docker.io/library/ubuntu:focal
1001@e779037627d5:/$ id
uid=1001(1001) gid=0(root) groups=0(root)
1001@e779037627d5:/$ exit
```

Here's the result of podman top:
```
$ podman top $container user huser
USER   HUSER
1001   1000
```

**Comment by marinmo** [comment]
I'm having a semi-similar issue.

My local user is uid 1000 gid 1000.

Mariadb container runs with two users, root and mysql (uid 100 gid 101). The container run script chowns the files in the mounted volume to the mysql user/group at startup. This maps to 100099:100100 on the host. I'd want to the mysql user and group in the container to my own user on the host, that is, making all users in the container map to my own user.

This is a problem because permissions on the files in the volume means I cannot back them up without running the backup program as root, meaning solving one problem (running containers rootless) introduces another issue (necessitating running backups as root).

I've been trying to fiddle with uid and gidmap to no avail, leading me to believe there's no real solution to this particular use case. Is this correct?

**Comment by rhatdan** [comment]
Can you run your back up program as 
podman unshare backup...

**Comment by marinmo** [comment]
That could probably work, but I'm running borgmatic backing up more than just containers. That solution would require a separate config and set up just for the few containers where this is an issue, which seems ... I'm just someone doing containers for fun, but it seems a bit excessive even for me :)
Either way there should probably be a way in podman to mangle all container UIDs to one host UID, similar to --userns=keep-id without the changes that introduce within the container itself as per the original bug report, since keep-id breaks containers that depend on root access within the container. I guess you could argue that it's a problem with those containers not running and supporting truly rootless deployment, but they're a thousand to one including ones from major vendors (Mariadb being a good example, see for example https://github.com/MariaDB/mariadb-docker/blob/master/10.6/docker-entrypoint.sh).
I'm far from an expert, but I don't see what negative security implications that would have? UID and GID mapping is honestly really opaque, even with all the documentation that exists around it (again, this bug is a good example). Not meant as a critique per se, more of a hopefully helpful observation.

Please note that I'm very happy with podman in general and I really appreciate you taking your time to reply to a closed bug. Sorry for any inconvenience.
