### ISSUE TITLE
Can't start wayland compositor on separate tty

### ISSUE THREAD

**Issue by bam80** [containers/podman#6140]
Cross-posted https://github.com/containers/toolbox/issues/428

I tried weston and sway.
For example, weston gives following:
```
⬢[bam@toolbox bam]$ weston
Date: 2020-04-29 MSK
[18:02:14.249] weston 8.0.0
               https://wayland.freedesktop.org
               Bug reports to: https://gitlab.freedesktop.org/wayland/weston/issues/
               Build: 8.0.0
[18:02:14.249] Command line: weston
[18:02:14.250] OS: Linux, 5.5.17-200.fc31.x86_64, #1 SMP Mon Apr 13 15:29:42 UTC 2020, x86_64
[18:02:14.251] Starting with no config file.
[18:02:14.251] Output repaint window is 7 ms maximum.
[18:02:14.251] Loading module '/usr/lib64/libweston-8/drm-backend.so'
[18:02:14.257] initializing drm backend
[18:02:14.259] logind: not running in a systemd session
[18:02:14.259] logind: cannot setup systemd-logind helper (-61), using legacy fallback
[18:02:14.259] fatal: drm backend should be run using weston-launch binary, or your system should provide the logind D-Bus API.
[18:02:14.259] fatal: failed to create compositor backend
Internal warning: debug scope 'drm-backend' has not been destroyed.
```
Seems the problem is always related with logind session.
Is there something we can do with it?

The problem doesn't happen if run outside the container.

**Comment by mheon** [comment]
It seems to be angry that `systemd` is not available inside the container. Systemd-in-a-container is a supported configuration with Podman, so you could try running in a container with systemd set as PID 1?

**Comment by bam80** [comment]
Thanks @mheon for the quick reply!
In the container, I run the script to pass-through hosts' systestemd instance: https://gitlab.gnome.org/fmuellner/silverblue-stuff/-/blob/master/sb-gnome-shell-setup.sh
`systemctl` seems work at least. Isn't it enough?

**Comment by mheon** [comment]
According to that Wayland binary, it can't find/access logind - so I suspect it's not?

**Comment by bam80** [comment]
Then, can we somehow passthrough logind also? I would rather use host's instance instead.

**Comment by bam80** [comment]
BTW, logind seems also work?
```
⬢[bam@toolbox bam]$ loginctl 
SESSION  UID USER SEAT  TTY 
     11 1001 bam  seat0 tty4
      4 1001 bam  seat0 tty4

2 sessions listed.

**Comment by mheon** [comment]
I'm honestly not sure. You might want to ask the toolbox folks; they're a lot more familiar with this than I am.

**Comment by bam80** [comment]
Maybe. Just less responsive. Thanks! :)

**Comment by rhatdan** [comment]
Mostlikely you need to share /run or /run/systemd into the container and not run with systemd in the container.  You might get some issues though where systemd does not trust processes inside of containers.

**Comment by rhatdan** [comment]
Usually when people are trying to run Desktop apps in containers, we want them to look at Flatpack, which might be better for your use case.

**Comment by bam80** [comment]
> Mostlikely you need to share /run or /run/systemd into the container and not run with systemd in the container. You might get some issues though where systemd does not trust processes inside of containers.

IIRC, the script does exactly this: https://gitlab.gnome.org/fmuellner/silverblue-stuff/-/blob/master/sb-gnome-shell-setup.sh#L15
```
rm -rf /run/systemd/{seats,sessions,system,users}
ln -s /run/host/run/systemd/{seats,sessions,system,users} /run/systemd
```
Toolbox seems also take care of sharing /run/user/<uid> and /run/dbus with the host.
About trusting, I don't see any systemd complains in journal during weston run.

> Usually when people are trying to run Desktop apps in containers, we want them to look at Flatpack, which might be better for your use case.

I doubt it would be easy to run and develop the _whole_ Desktop in Flatpak ;)
https://blogs.gnome.org/fmuellner/2020/03/02/shell-hacking-on-silverblue/

**Comment by rhatdan** [comment]
Anyways I would think @debarshiray would be better at helping on this then most of us.

**Comment by bam80** [comment]
@debarshiray I would be very appreciated for your input

**Comment by halfline** [comment]
This error message means that weston can't identify which logind session it belongs to.  It does this using a `sd_pid_get_session` call. I don't think `sd_pid_get_session` is going to work inside the container because the pid namespace is different.  Furthermore, logind only allows one "session controller" per session to have access to the drm device. if outside the container is already the controller, it won't work inside the container, for sure.

**Comment by bam80** [comment]
Thanks @halfline I've filed the issue against weston: https://gitlab.freedesktop.org/wayland/weston/-/issues/401

**Comment by halfline** [comment]
hmm @debarshiray pointed out on IRC that toolbox doesn't use a separate pid namespace.  Still, it's `sd_pid_get_session` failing, so I think my proposed fix should help.

**Comment by halfline** [comment]
just one more follow up.  The reason `sd_pid_get_session` is failing is because podman isn't running under the user's session, but it's own scope attached to the user on the side:

```
╎❯ systemctl --user status 
● toolbox
...
   CGroup: /user.slice/user-4153.slice/user@4153.service
...
           ├─user.slice 
           │ └─podman-190348.scope 
           │   ├─190348 podman exec --interactive --tty --user rstrode --workdir /home/rstrode --env=DBUS_SESSION_BUS>
           │   ├─190369 /usr/libexec/crio/conmon --api-version 1 -c a8d6c7855c1857b6e2c4b41ba6116612efd6ecae8514291db>
           │   ├─190373 /bin/bash -l
...
```

(and it's not in `loginctl session-status` output)
So weston needs code similar to the mutter code I pasted for an analogous reason: it's getting run outside of a logind session.

**Comment by bam80** [comment]
> The reason sd_pid_get_session is failing is because podman isn't running under the user's session

Thanks @halfline, I wonder if it's the right way to behave for toolbox/podman? @debarshiray 
By the way, Sway compositor has the same problem..

**Comment by agners** [comment]
@halfline 

I guess by "weston needs code similar to the mutter code" you mean mainliy `sd_uid_get_display`? I tried to replicate @bam80's setup, and added `sd_uid_get_display` in case `
`sd_pid_get_session` failed (it does fail with `-ENODATA`). I do get a session it seems, at least I do not get  a return code. However, I then get:

```
[00:26:43.298] logind: cannot take control over session 3
[00:26:43.298] logind: cannot setup systemd-logind helper (-5), using legacy fallback
[00:26:43.298] fatal: drm backend should be run using weston-launch binary, or your system should provide the logind D-Bus API.
```

It seems `TakeControl` D-Bus call fails, I haven't looked further into why exactly.

**Comment by halfline** [comment]
are you logged in with the same user on a different VT? if so `sd_uid_get_display` will return that one and try to take control of a session that already has a controller. gnome doesnt really support logging in more than once for the same user. assuming you are trying yo log into two sessions with the same user at the same time, you could make it work by picking the newest session instead of the session returned by `sd_uid_get_display`

**Comment by agners** [comment]
@halfline Yes I was still logged in with the same user. I then logged out, and Weston worked fine from inside the toolbox container. I guess it is worth adding `sd_uid_get_display` without pid. I am not sure if I would go further than that at this point, since most application do not support two sessions anyway.

**Comment by agners** [comment]
Interestingly, `loginctl session-status` does show the session I entered toolbox on my Fedora 30 container, however, it seems to use the primary session (the one I logged in first) when using Fedora 33. Turns out this is due to a change in `loginctl` which used to lookup `XDG_SESSION_ID`, but this got removed by v243. The commit message claims the server side can do "something similar", but I guess in this case it really fails.
https://github.com/systemd/systemd/commit/544c4e1eda4b15beec8a9d7e3708b262b954e757

From what I understand `sd_pid_get_session` really uses the cgroup hierarchy to find the session this particular pid is attached to. This makes me wonder can w maybe make podman starting itself under the session scope?

**Comment by rhatdan** [comment]
@bam80 I will close this issue, I don;t believe this is a problem with Podman. Reopen if you disagree

**Comment by bam80** [comment]
I think I have no experience to decide

**Comment by japrogramer** [comment]
I run into this issue with 
`XDG_RUNTIME_DIR=/tmp/xdg weston --tty="1" --idle-time=0`

but not when i use sudo with the same command above, problem is ... I don't want everything running as sudo

**Comment by GrabbenD** [comment]
I was able to run Sway with Podman in a root container using Distrobox: https://github.com/89luca89/distrobox/issues/780#issuecomment-1585570640

Haven't figured out how to achieve this with a rootless container though
