### ISSUE TITLE
Partial image import/export

### ISSUE THREAD

**Issue by progtologist** [containers/podman#6503]
/kind feature

**Description**

There is no option to export an image partially, that is, choose to omit some layers because we know that another system might already have them. This functionality is automatically provided when using a container repository, but somehow this is not feasible with the cli save/load functions.

This has been proposed (and [implemented](https://github.com/moby/moby/pull/9304)) in the past to docker, but it has been rejected.

**Comment by mheon** [comment]
I don't think the team has any time to implement this at the moment, but I don't think we'd object to a PR adding support for it.

I do have some concerns about the user interface for such a system; how does one specify which layers to include/exclude, and how do we provide a sensible error message if someone tries to import the image on a system that does not have those missing layers? These seem solvable, but I want to make sure that we produce a good experience for users.

@mtrmac PTAL

**Comment by mtrmac** [comment]
The way `docker-archive:` currently pretends to use the schema2 format would not really work with missing layers. It might be fixable…

But, primarily, I’d recommend to use a registry. The `docker-archive:` format is quite inefficient to use (it requires extra I/O to create or consume a linear file, and creating the archive can’t be parallelized), and as implemented in c/image it does not allow any cross-image layer sharing. It’s a pretty good bet that starting a registry container, copying an image to that registry, stopping the container, copying the storage to a different system, starting a registry container with that storage there, and pulling from that registry, might be faster than `podman save`+`podman load`, and it’s pretty certain to be so if we are talking about a few images that share layers.

That also allows the registry users to automatically detect/reuse duplicates, without the user having to use some kind of extra logic to guess which layers are truly new / duplicate, including counting the layers of all the base image, or maybe specially synchronizing/orchestrating base image updates as special process, and what not.

So, I’m not very inclined to add extra features, and introduce new format variants to `docker-archive:`, a format that exists not because it works _efficiently_ but just for _compatibility_. Adding incompatible extensions to a compatibility format rather defeats the point.

That said, you haven’t talked about your use case, maybe it really is special and there is legitimate need.

**Comment by progtologist** [comment]
Thank you for taking the time to describe the underlying problems in detail. If you read through the docker merge request I have linked and the discussions linked on that as well, there are a few users/developers that have shown interest in this functionality. 
It has been requested (and implemented) from users numerous times and had two different MR rejected, dating back in 2015.

The use case is quite simple but most likely not very common, updating a docker image on an offline site (or on sites with very strict firewall rules). This would allow you to create a docker tar file with just the updated layers, reducing the size of the tarball significantly.

My go programming skills are quite limited so I am not claiming to taking on the matter on my own hands, but it would be interesting to know if the design goals of podman would also reject a MR implementing this functionality.

**Comment by rhatdan** [comment]
@progtologist We would certainly consider this, but would need a PR to review.

**Comment by vrothberg** [comment]
I will take a shot and close the issue.  @mtrmac gave a great explanation on the implications of the request.

For air-gapped environments, I suggest to have a look at [skopeo-sync](https://github.com/containers/skopeo/blob/master/docs/skopeo-sync.1.md) which is a great way of moving many images from A to B.  Where A and B may be a registry, or a local directory, or a mounted USB device etc.
