### ISSUE TITLE
Podman Mac Client tutorial is outdated

### ISSUE THREAD

**Issue by akhilles** [containers/podman#6830]
**Description**

The tutorial at `docs/tutorials/mac_client.md` seems outdated. The instructions specify the use of a `--remote-host` flag, but this flag doesn't seem to exist on the latest version of podman. There's also a broken link to https://github.com/containers/libpod/blob/master/docs/podman-remote.conf.5.md on the same page.

**Steps to reproduce the issue:**

```
podman --help
```

**Output of `podman version`:**

```
podman version 2.0.0
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
$ brew cask info podman
podman: 2.0.0
https://github.com/containers/libpod/
/usr/local/Caskroom/podman/2.0.0 (39.7MB)
From: https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/podman.rb
==> Name
podman
==> Artifacts
podman (Binary)
```

**Comment by vrothberg** [comment]
Thanks for opening the issue, @akhilles!

@ashley-cui, could you tackle it?

**Comment by afbjorklund** [comment]
The instructions on https://github.com/containers/libpod/blob/master/docs/tutorials/remote_client.md are in the same state.

And we have the same issue on https://minikube.sigs.k8s.io/docs/drivers/podman/ - in that it doesn't work with podman2...

So it's more of a generic issue, due to the breaking API changes in v2.
https://podman.io/blogs/2020/06/29/podman-v2-announce.html

We will recommend that people stay with v1.9.3 until it can be updated.
https://github.com/containers/libpod/releases/tag/v1.9.3

**Comment by afbjorklund** [comment]
Added a similar warning about the new podman v2 API to the front page of https://github.com/boot2podman/machine

Most likely people will have to set up their own Linux VM, with something that is compatible with the new Podman release.

https://podman.io/getting-started/installation

> Podman is a tool for running Linux containers. You can do this from a MacOS/Windows desktop as long as you have access to a linux box either running inside of a VM on the host, or available via the network. You need to install the remote client and then setup ssh connection information.

**Comment by afbjorklund** [comment]
Moved to `vagrant` instead of `podman-machine`. Most users seemed to be interested in the big Fedora ISO anyway:

https://developers.redhat.com/blog/2020/02/12/podman-for-macos-sort-of/

So if you prefer VirtualBox over qemu and Fedora over boot2podman, you might as well just use Vagrant for setup:

https://boot2podman.github.io/2020/07/22/machine-replacement.html

**Comment by rhatdan** [comment]
@ashley-cui @baude PTAL
