### ISSUE TITLE
Wrong image hash for pulls from hub.docker.com

### ISSUE THREAD

**Issue by abitrolly** [containers/podman#7179]
/kind bug

**Description**

`podman` either stores wrong image sha2 hash, or pulls wrong images. For example, `redis:alpine-4` at https://hub.docker.com/_/redis?tab=tags&page=1&name=4-alpine right now has the following signatures.

![image](https://user-images.githubusercontent.com/8781107/89092154-fa4c4600-d3b7-11ea-8072-8ac2bc788a24.png)

Note that there is no image hash starting with `e`, But `podman pull` computes the signature that starts with `e`

```
✗ podman pull redis:4-alpine
Trying to pull registry.fedoraproject.org/redis:4-alpine...
  manifest unknown: manifest unknown
Trying to pull registry.access.redhat.com/redis:4-alpine...
  name unknown: Repo not found
Trying to pull registry.centos.org/redis:4-alpine...
  manifest unknown: manifest unknown
Trying to pull docker.io/library/redis:4-alpine...
Getting image source signatures
Copying blob aa6ecacd3bee skipped: already exists  
Copying blob cbdbe7a5bc2a skipped: already exists  
Copying blob 152ffd6a3b24 skipped: already exists  
Copying blob 7c01860f13a3 [--------------------------------------] 0.0b / 0.0b
Copying blob dc0373118a0d [--------------------------------------] 0.0b / 0.0b
Copying blob cfd369fe6256 [--------------------------------------] 0.0b / 0.0b
Copying config e3dd0e49bc done  
Writing manifest to image destination
Storing signatures
e3dd0e49bca555d559ca2e97f06a1efa108ebd230fddcb17606723994f18ae3b
```
```
✗ podman images redis     
REPOSITORY               TAG       IMAGE ID      CREATED       SIZE
docker.io/library/redis  4-alpine  e3dd0e49bca5  3 months ago  21.6 MB
```

**Output of `podman version`:**

```
Version:      2.0.3
API Version:  1
Go Version:   go1.14.3
Built:        Thu Jan  1 03:00:00 1970
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.15.0
  cgroupVersion: v2
  conmon:
    package: conmon-2.0.19-1.fc32.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.19, commit: 5dce9767526ed27f177a8fa3f281889ad509fea7'
  cpus: 4
  distribution:
    distribution: fedora
    version: "32"
  eventLogger: file
  hostname: blackred
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.7.10-201.fc32.x86_64
  linkmode: dynamic
  memFree: 598708224
  memTotal: 8032100352
  ociRuntime:
    name: crun
    package: crun-0.14.1-1.fc32.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.14.1
      commit: 598ea5e192ca12d4f6378217d3ab1415efeddefa
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  rootless: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.4-1.fc32.x86_64
    version: |-
      slirp4netns version 1.1.4
      commit: b66ffa8e262507e37fca689822d23430f3357fe8
      libslirp: 4.3.1
      SLIRP_CONFIG_VERSION_MAX: 2
  swapFree: 8150577152
  swapTotal: 8196714496
  uptime: 12h 48m 35.04s (Approximately 0.50 days)
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - docker.io
store:
  configFile: /home/anatoli/.config/containers/storage.conf
  containerStore:
    number: 4
    paused: 0
    running: 0
    stopped: 4
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-1.1.2-1.fc32.x86_64
      Version: |-
        fusermount3 version: 3.9.1
        fuse-overlayfs: version 1.1.0
        FUSE library version 3.9.1
        using FUSE kernel interface version 7.31
  graphRoot: /home/anatoli/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 19
  runRoot: /run/user/1000
  volumePath: /home/anatoli/.local/share/containers/storage/volumes
version:
  APIVersion: 1
  Built: 0
  BuiltTime: Thu Jan  1 03:00:00 1970
  GitCommit: ""
  GoVersion: go1.14.3
  OsArch: linux/amd64
  Version: 2.0.3
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-2.0.3-1.fc32.x86_64
```

**Comment by rhatdan** [comment]
@mtrmac PTAL

**Comment by mtrmac** [comment]
> Copying config **e3dd0e49bc** done  
…
> **e3dd0e49bc**a555d559ca2e97f06a1efa108ebd230fddcb17606723994f18ae3b
…
> ✗ podman images redis     
> REPOSITORY               TAG       IMAGE ID      CREATED       SIZE
> docker.io/library/redis  4-alpine  **e3dd0e49bc**a5  3 months ago  21.6 MB

The value printed is not a “manifest digest”, it is an “image ID” that can be used to refer to the locally-pulled image (even if a new version is pulled later and the tag is moved). The “image ID” is the digest of the config, _if a config blob exists in the image representation_.

If you want to determine the “manifest digest” of an image after it has been puled, it should be listed in the `RepoDigests` field of `podman inspect` (although IIRC there are some corner cases when pulling multiple representations of the same image).

**Comment by abitrolly** [comment]
Checked with `docker`.
```bash
$ docker pull redis:4-alpine
4-alpine: Pulling from library/redis
cbdbe7a5bc2a: Pull complete 
dc0373118a0d: Pull complete 
cfd369fe6256: Pull complete 
152ffd6a3b24: Pull complete 
7c01860f13a3: Pull complete 
aa6ecacd3bee: Pull complete 
Digest: sha256:aaf7c123077a5e45ab2328b5ef7e201b5720616efac498d55e65a7afbb96ae20
Status: Downloaded newer image for redis:4-alpine
docker.io/library/redis:4-alpine
[node1] (local) root@192.168.0.13 ~
$ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
redis               4-alpine            e3dd0e49bca5        3 months ago        20.4MB
```
The `IMAGE ID` fits podman, but the digest `sha256:a...` doesn't match anything in Docker Hub. Why not to refer to local and remove image using the same hash? I expected this to work like IPFS.

**Comment by mtrmac** [comment]
`sha256:aaf7c123077a5e45ab2328b5ef7e201b5720616efac498d55e65a7afbb96ae20` is a “manifest digest” of the manifest list, that lists the individual per-architecture images; see `skopeo inspect --raw docker://redis:4-alpine` , or `skopeo inspect --raw docker://redis:4-alpine | sha256sum`.

If the Docker Hub UI chooses not to display that value (apparently even deep links to a specific image use one of the architecture-specific digests), that’s not ideal but not something we can solve here.

> Why not to refer to local and remove image using the same hash? I expected this to work like IPFS.

Do you mean “remote image” here?
1. It’s not _possible_: locally-built images don’t have manifests, so they can’t have manifest digests. Remote images don’t _always_ have configs, so they can’t use config digests (and lookup by config digests would require the registry to maintain an index, instead of being a dumb content-addressed store).
1. It’s not _efficient_: The “same image” (same contents, same configuration) can have different registry representations (notably differently-compressed layers, but other differences may exist) and those differences show up in manifest digests, so locally sharing, and identifying, images by the config digests instead of manifest digests allows local sharing more ima es and saving space
1. We don’t _quite_ have a choice if the goal of Podman is to be a drop-in replacement of the `docker` executable.

**Comment by abitrolly** [comment]
Ok. Manifest is just a catalog of images for different architecture under the same tag.

Then what are those digests for different architectures? Content addressable blobs with images? But then why the are not shown when pulling layers?

What is this "config" and why it is needed for the image that already has digest? I thought the local storage is the same dumb content-addressed store as remote registry. The presence of this config should spoil the ability to do reproducible builds on different machines.

**Comment by mtrmac** [comment]
Study/contrast https://github.com/docker/distribution/blob/master/docs/spec/manifest-v2-1.md https://github.com/docker/distribution/blob/master/docs/spec/manifest-v2-2.md .

> I thought the local storage is the same dumb content-addressed store as remote registry.

It isn’t and cannot be, when the registries store compressed tarballs and local storage must store exploded filesystems.

---

Or, maybe, please start by explaining what you are trying to do.

**Comment by abitrolly** [comment]
> Or, maybe, please start by explaining what you are trying to do.

I tried to speed up checks for image updates before running them. I use `podman run` as a command line tools wrapper, and it is slow to ping all repos before hitting Docker Hub. Then it appeared that its pull argument doesn't allow updating images.
```
      --pull string                              Pull image before creating ("always"|"missing"|"never") (default "missing")
```

**Comment by mtrmac** [comment]
If the goal is to check whether the image is up-to-date vs. the registry at all, the simplest thing you can probably do is to use fully-qualified image names (`podman run docker.io/library/busybox` instead of `podman run busybox`), so that only the relevant registry is contacted.

If you want to maintain a separate off-line list of images that should be run without contacting a registry at all, `podman inspect` and checking RepoDigests vs. a digest from a registry would probably work well, _as long as_ no locally-built images are involved. If locally-built images need to be involved, checking the Id value from `podman inspect` or `podman images` could work, but to determine that value you need to pull the image first and `inspect` it, in the general case (or read the manifest for schema2/OCI, but that hard-codes format knowledge).
