### ISSUE TITLE
Except for Podman V2.0,  which other release version will be also supported? such as: 1.9.x ？ 1.8.x ？

### ISSUE THREAD

**Issue by fhwsuper** [containers/podman#7506]
Except for Podman V2.0,  which other release version will be also supported? such as: 1.9.x ？ 1.8.x ？Are there any rules or documents for supported release version?

**Comment by afbjorklund** [comment]
There was a partial answer on https://podman.io/blogs/2020/08/01/deprecate-and-remove-varlink-notice.html

**Comment by mheon** [comment]
Generally speaking, we provide full support for the most recent version, and backports of security issues and major bugfixes to a few previous versions. At present, we're starting to spin the Podman v2.0 branch down to only critical backports as we prepare to begin cutting RCs for Podman 2.1.0

**Comment by afbjorklund** [comment]
We are currently building our own packages for 1.9.3, since there are no "subprojects" available for podman:

https://build.opensuse.org/project/show/devel:kubic:libcontainers:stable

It was recently added as a feature for cri-o, for users that wanted to stay on older releases (or on branches):

https://build.opensuse.org/project/subprojects/devel:kubic:libcontainers:stable

----

For podman there are source branches and release binaries, but no packages.

https://github.com/containers/podman/branches

https://github.com/containers/podman/releases

That is, there is only one "podman" package so if you upgrade - you'll be on 2.0.5

**Comment by rhatdan** [comment]
Issue was answered.
