### ISSUE TITLE
Any reason to support slirp4netns for rootful?

### ISSUE THREAD

**Issue by AkihiroSuda** [containers/podman#7530]
Is there any reason to keep support for `podman run --network=slirp4netns` on rootful?

During fixing up CI failures in https://github.com/containers/podman/pull/7460, I found it is hard to keep support for slirp4netns+rootful .

**Comment by rhatdan** [comment]
Would there be a use case where you want to run podman within a locked down container, without NET_ADMIN as root and still need to setup the network?

**Comment by mheon** [comment]
I think the request is usually for Podman in a container, or otherwise scenarios where modifying IPTables isn't really feasible.

It sounds like the amount of effort going into keeping it working when changes are made is high, though it generally doesn't seem to break or develop many bugs otherwise.
