### ISSUE TITLE
Feature request: be able to check for remote image changes before pull

### ISSUE THREAD

**Issue by filippog** [containers/podman#8128]
/kind feature

**Description**

When pulling new images via `podman pull` it would be useful to be able to check first if the pull is going to do something (and what). For example when running configuration management tools to preview changes (e.g. "`ansible --check`").

AFAICT this is already possible with skopeo, although having the same functionality in podman as well would simply deployments. What do you think ?

**Comment by rhatdan** [comment]
@QiWang19 @mtrmac PTAL
Is this possible with Skopeo

**Comment by vrothberg** [comment]
I think Skopeo is a better tool for that. There's the whole ambiguity of shortnames and registry mirrors that `skopeo inspect` is not subjected to.

**Comment by mtrmac** [comment]
First of all, that’s inherently racy: such a check can say that nothing would have to be pulled, only for the tag to be updated and the actual pull to need to copy data.

---

Somewhere around `checkRemoteImageForLabel` similar code could be used to fetch… something… about the remote image (but note that “remote” may mean “tens of gigabytes of compressed `docker save`-formatted data that will be decompressed just to read this information) and check whether a local one matches, sort of. Only “something” is format- and transport- specific (manifest digest? may be changed on conversion, and we don’t truly store RepoTags values; config digest? does not really exist for schema1). 

And all of this would have to account for pulling multi-arch images and choosing the right one.

This would have to be a (partial) heuristic, because to check whether “the result of a copy already exists at a destination”, the copy must, in the worst case, actually copy all the layers (to decompress/decrypt them) in order to create a destination-appropriate manifest. Sure, for the specific case of a c/storage destination, we can make _some_ assumptions about the (un)necessary conversions and the like, but the generic `copy.Image` code can’t easily make such assumptions, so we are more or less talking about a separate guess/shortcut heuristic either way.

----

Practically speaking, I’d recommend to:
- Pin specific images (either by digest, or by a tag that doesn’t change) at the _start_ of a deployment, and pass only the pinned references to Podman. (That also ensures that if the “same application” is deployed to multiple hosts, they all get exactly the same version.) I.e. don’t submit a `:latest` tag to Podman from Ansible.
- Given such a specific image reference, just use `podman inspect` to see whether that image is available locally — that can take advantage of the _application-level_ knowledge that the digest reference / tag reference is unique and unchanging, something c/image or Podman couldn’t assume in a `podman pull --check`.

**Comment by mtrmac** [comment]
There is https://github.com/containers/image/pull/1041 for some idea of the complexity involved in the general case (see also how deep in the call stack this is and how many checks/decisions have already happened by that point), and that’s just an _optimization_ where we can safely just continue copying if unsure, not a feature that should always return a correct yes/no answer.

**Comment by filippog** [comment]
Thanks for all the quite informative responses. It sounds like this isn't quite as easy as I thought when filing the issue. Nevertheless, if there isn't appetite to have this feature in `podman` itself then the next best thing I think would be to improve documentation and point folks to the right place/implementation for the "check mode" use case. What do you think ?

**Comment by rhatdan** [comment]
Interested in opening a PR to add the docs?

**Comment by filippog** [comment]
> Interested in opening a PR to add the docs?

Happy to take a stab at it, what repo / file(s) would be the best location for this type of information ?

**Comment by rhatdan** [comment]
Well I will turn it back on you, where was the first place you looked for this documentation?

I would think the man pages for podman pull, create and run?

**Comment by rhatdan** [comment]
@filippog Are you still interested in this?

**Comment by filippog** [comment]
Thank you for following up @rhatdan. I thought I was but realistically I haven't found the time, I'm ok to close the issue though
