### ISSUE TITLE
podman image exists, with vfs.imagestore and image from quay, fails

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#8176]
I have no idea how to even describe this, so someone please feel free to change the title to a more descriptive one.

Discovered during testing of #8165 -- a podman setup using `vfs` and `vfs.imagestore` will, under certain circumstances involving images from `quay.io`, falsely claim false on `image exists`. A reproducer is worth a thousand of my words:
```bash
#!/bin/bash

set -ex

PROOT=/dev/shm/mypodman
rm -rf $PROOT
mkdir -p $PROOT

# What's really weird is that this test *succeeds* with docker.io
IMAGE=quay.io/libpod/alpine:latest
#IMAGE=docker.io/library/alpine:latest

# Pull something in order to initialize imagestore
# Without this initial pull, the last pull below fails with:
# Error: error opening "/dev/shm/mypodman/cache/vfs-images/images.lock": no such file or directory
PODMAN="./bin/podman --root $PROOT/cache --storage-driver vfs"
$PODMAN pull -q $IMAGE

# And now, switch --root to something empty, and set imagestore to the above.
# Pull the same image, and boom.
# If you comment out the 'pull' below, 'image exists' succeeds.
PODMAN="./bin/podman --storage-opt vfs.imagestore=$PROOT/cache --root $PROOT/root --storage-driver vfs"
$PODMAN pull -q $IMAGE

# Shows two images, differing only in the rightmost 'R/O' column
$PODMAN images -a

# This fails!
$PODMAN image exists alpine
```

**Comment by edsantiago** [comment]
I don't think this is fixed; the [original test continues to fail](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5429634319777792/html/int-podman-fedora-31-rootless-host.log.html#t--podman-image-exists-in-local-storage-by-short-name--1). So does the reproducer in comment 0.

**Comment by rhatdan** [comment]
This test is being screwed up by the mirroring.

If you run images, you see that you have these images.
REPOSITORY             TAG     IMAGE ID      CREATED        SIZE     R/O
quay.io/libpod/alpine  latest  961769676411  15 months ago  5.85 MB  false
quay.io/libpod/alpine  latest  961769676411  15 months ago  5.85 MB  true

But the image exists is looking for 
docker.io/library/alpine

Since the image exists does not go through the mirror code, it fails.

**Comment by rhatdan** [comment]
@vrothberg @mtrmac This is happening in containers/image GetStoreImage() call.

Should this be translating the local users name to the mirror name?

**Comment by rhatdan** [comment]
img, err = is.Transport.GetStoreImage(ir.store, ref)

**Comment by mtrmac** [comment]
@rhatdan I assume by “mirror” you consistently mean `vfs.imagestore`, don’t you? There is no “mirror name” AFAICS, just two places to look up images with a name, and no way to name explicitly one or the other image if there is more than one in the multiple stores.

At a first glance, it’s not too surprising that `docker.io/*` and `quay.io/*` images behave differently (assuming `quay.io` is not in the unqualified-search-registries list), because the former one uses the https://github.com/containers/podman/blob/f01630acf35a11aecdbfb9b77b249dcec85e67b5/libpod/image/image.go#L462-L482 path (including the hard-coded `docker.io` default at the bottom).

For `quay.io`, this triggers the undocumented `findImageInRepotags` heuristic (which, ceterum autem censeo , probably should not exist at all, but I can’t find any record of why it exists so I’m not sure).

---

Just reading the code, without testing it at all: AFAICS in the `quay.io` case:
- https://github.com/containers/podman/blob/f01630acf35a11aecdbfb9b77b249dcec85e67b5/libpod/image/image.go#L486 finds both images (same name, different backing stores)
- `findImageInRepoTags` finds both as matches, fails with `errors.Wrapf(define.ErrMultipleImages, searchName)`
- The caller in https://github.com/containers/podman/blob/f01630acf35a11aecdbfb9b77b249dcec85e67b5/libpod/image/image.go#L496-L500 just throws away that value and returns `ErrNoSuchImage`…
- … causing the error value check in https://github.com/containers/podman/blob/f01630acf35a11aecdbfb9b77b249dcec85e67b5/pkg/domain/infra/abi/images.go#L43-L44 to not trigger, and `Exists` to return `false`.
