### ISSUE TITLE
aarch64 (Raspberry pi) fails to install podman container to network, error: rootless-podman-network-sandbox

### ISSUE THREAD

**Issue by rupert160** [containers/podman#8411]
Can somebody explain why podman networking fails to connect my container to the virtual network?
Fedora 33 aarch64, the following works fine:
```
podman run -dt --name hello-nginx nginx
```
However creating a container within a pod does not work:
```
podman network create podnet1 --subnet 192.168.0.1/24 --driver bridge

podman pod create --replace \
	--publish 53/tcp,53/udp,67/udp,80/tcp,443/tcp \
	--hostname ph2 \
	--name ph2 \
	--network podnet1

podman run -dt --pod ph2 --name hello-nginx2 nginx
```

ERRO[0000] error starting some container dependencies   
ERRO[0000] "cannot find rootless-podman-network-sandbox image for arm" 
Error: error starting some containers: internal libpod error

additionally attaching a container to the same `podnet1` network fails
```
podman run -dt --network podnet1 --name hello-nginx2 --publish 8080:80/tcp nginx
```
Error: cannot find rootless-podman-network-sandbox image for arm

It would appear that https://github.com/AkihiroSuda/podman-network-create-for-rootless-podman
has not been created for ARM or aarch64 - but I'm not sure. I cannot pull this image at least.

**Comment by mheon** [comment]
I'm pretty sure we're maintaining this one ourselves in Quay - @AkihiroSuda correct?
@TomSweeneyRedHat Do you know what architectures Quay builds us for by default?

**Comment by AkihiroSuda** [comment]
It is built manually, only for amd64 currently

**Comment by TomSweeneyRedHat** [comment]
@mheon, not ours on quay yet.  @barthy1 built Skopeo images with different arch types for us in quay.  I can't check at the moment as quay isn't happy, but I'm pretty sure our Podman images there by default are X86_64 as that's what they're built on.

**Comment by barthy1** [comment]
looks like update [here](https://github.com/containers/podman/blob/2aa6a8577d088271251604b028100f00a442f5cd/libpod/rootless_cni_linux.go#L27) is required to support other archs. So far only amd64 version is available

**Comment by barthy1** [comment]
and of course multi-arch build of `quay.io/libpod/rootless-cni-infra` is requried

**Comment by rupert160** [comment]
Thanks @barthy1 - I've tried to `podman pull quay.io/libpod/rootless-cni-infra` but the container can't be found... is this what you meant?

**Comment by barthy1** [comment]
@rupert160 
1. you have `manifest unknown` error because  `quay.io/libpod/rootless-cni-infra` image has no `latest` tag. Just use it as a [link](quay.io/libpod/rootless-cni-infra) and you can see all available tags
2. Anyway, at this moment this image(all available tags) has only amd64 version. So, you need to wait till @AkihiroSuda kindly publishes versions for other architectures
3. If you are interested to build image on your own for arm64 arch, you can use as starting point this [Containerfile](https://github.com/containers/podman/blob/fc34be780f156bab3df3a0f38aa92bdc0da2d146/contrib/rootless-cni-infra/Containerfile), provided by @AkihiroSuda in the PR 
4. `golang:1.15-alpine3.12` seems to be available https://hub.docker.com/_/golang?tab=tags&page=1&name=1.15-alpine3.12

**Comment by rhatdan** [comment]
I don't believe this is an upstream issue.  Reopen if I am mistaken.
