### ISSUE TITLE
podman build produces "SHELL is not supported for OCI image format"

### ISSUE THREAD

**Issue by svdHero** [containers/podman#8477]
Hi there,

I have Dockerfiles containing the command
```
SHELL ["/bin/bash", "-c"] 
```
for setting the default shell to bash.

When I try to build images from said Dockerfiles with podman version 2.1.1, I get the error message:
"SHELL is not supported for OCI image format".

What should I do? Do I have to modify the Dockerfiles or is there another way to do this? I thought podman was a drop-in replacement for docker. Am I missing something or doing something wrong?

**Comment by rhatdan** [comment]
You can use the --format docker flag, to support this option.  This option did not make it into the OCI specification.
Podman defaults to building OCI images.

**Comment by rhatdan** [comment]
If you use buildah bud, you would get this message.
WARN SHELL is not supported for OCI image format, [/bin/bash -c] will be ignored. Must use `docker` format

**Comment by svdHero** [comment]
Great. I did not know about the `--format` option. Thank you.
I will try to avoid non-OCI commands for new Containerfiles.

**Comment by Ferryistaken** [comment]
Is there some kind of alternative to the SHELL command with OCI containers? I would like to build an OCI image but I don't really know how to transition.

**Comment by mheon** [comment]
I can't find any documentation on what the `SHELL` command actually does - it's been removed from all current Dockerfile syntax references, which makes me think it's deprecated.

I think it may be similar to the `ENTRYPOINT` instruction?

**Comment by Ferryistaken** [comment]
I tried building with `buildah` instead of `podman build` and it worked. It makes me think that I now have a docker formate image instead of an OCI image. How do I check if my image is OCI? Is there some tool that automatically does that?

**Comment by mheon** [comment]
I believe `ManifestType` in `podman inspect` is what you're looking for. `application/vnd.docker.distribution.manifest.v2+json` for DockerV2, `application/vnd.oci.image.manifest.v1+json` for OCIv1

**Comment by johnziebro** [comment]
> **You can use the --format docker flag, to support this option**. This option did not make it into the OCI specification.

I have a very similar warning with:
`CMD ["start.sh", "jupyter", "lab"]`
> WARN[0217] SHELL is not supported for OCI image format, [/bin/bash -o pipefail -c] will be ignored. Must use `docker` format 

Do you have an example of how to use the paramater? I tried 
`docker build -t --format docker jupyterlab-datascience ./datascience`
> Error: accepts at most 1 arg(s), received 3

**Comment by nezartarbin** [comment]
> I can't find any documentation on what the `SHELL` command actually does - it's been removed from all current Dockerfile syntax references, which makes me think it's deprecated.
> 
> I think it may be similar to the `ENTRYPOINT` instruction?

@mheon I am late to this, but the `SHELL` command changes the default shell used by commands such as `RUN`, which defaults to /bin/sh by default.

Is there a OCI alternative to this? the closest equivalent would be `RUN bash -c [commands]" but I would have to insert `bash -c` everywhere, and wrapping string around commands messes up syntax highlighting, which is especially bad for long or multiple `&&`-chained commands in a single `RUN`.

**Comment by akostadinov** [comment]
How to request this feature in OCI?

**Comment by dusansimic** [comment]
@mheon sorry for the ping but I came across this same issue and researched it a bit.

I've found some info in [Dockerfile reference](https://docs.docker.com/engine/reference/builder/#shell). It seems like it's used to reduce the number of arguments for `RUN` instruction. Since when building an image in oci mode, this instruction is ignored, I'm guessing one could recreate it by looking at what the `SHELL` instruction arguments are and putting it into the `RUN` instruction instead. I'm not sure if that is really the case tho.

My assumption is that since Docker images are already built (I'm using one for example) and using them as a base image won't affect their contents (since they are already built), podman and buildah are just warning users that some image (in my case a base image) is built with those unsupported instructions. If a user would want to have the same behavior of the `RUN` instruction tho, they would need to use the run it through the shell specified in the `SHELL` instruction manually. Am I wrong thinking that?
