### ISSUE TITLE
Include a list of well-known signing keys by default

### ISSUE THREAD

**Issue by DemiMarie** [containers/podman#8502]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**
/kind feature

**Description*
Podman supports verifying image signatures.  However, this requires non-default configuration, with the result that most users do not enforce it.

To move to a world in which signature verification is the default, Podman should include a list of well-known signing keys and the images for which they are authoritative.  For example, Red Hat’s images are signed by the same keys used for Red Hat RPMs.

**Comment by rhatdan** [comment]
@jnovy @fatherlinux This seems like more of a RHEL packaging thing perhaps?  WDYT?
@mtrmac @vrothberg Thoughts?

**Comment by DemiMarie** [comment]
@rhatdan I was using Red Hat as an example only.  Debian, Fedora, and other vendors might also sign their images, and ideally Podman should include signing keys for all of them.  Fedora has a `distribution-gpg-keys` package, so there is some precedent for this in other software.

**Comment by rhatdan** [comment]
Sure but upstream does not package Podman, downstream does.  If we had some way to maintain the list of signing keys or could commit them into Podman, then maybe we could put them in the upstream repo for the use of downstream packagers.

**Comment by mtrmac** [comment]
IMHO it would be rather irresponsible to start distributing public keys without understanding, accepting and “operationalizing” the full responsibility that implicitly takes on, i.e. the need to be able to deal with changes and revocations (and, in the worst case, tradermark/project ownership disputes, in a possible future world with fractured DNS).

It’s easy to accept 2-3 PRs this month to add some public keys we find on web pages, and experimentally verify that they currently work.

But suppose that in 4.5 years any one of the distributions
- loses much market share and contributor base (1a) moves the remaining contributor team to a less-known more isolated country, and a non-English community), so that we can’t just rely on PRs coming
- experiences a breach, compromising the long-term public key.

How do the maintainers of the public key set in Podman:
- Notice the breach has happened at all
- Determine what to do (replace keys? with some coordination for re-signing older images, or not? how are the replacement keys authenticated? just give up, and revoke the key?)
- Ship the public key update in all relevant old releases of Podman
- Ensure that users are notified
- Ensure downstream redistributors can do, and mostly do, the same for their users
- Do all of that within an acceptably short time frame?

At a minimum, would we have a person (with a many-year continuity plan = a sponsored job description) with the responsibility to notice that something has happened?

If 50 single-company (or 50 single-person) registries/software vendors submit PRs to have their keys added, would those 50 PRs be accepted, and would Podman take on the responsibility to monitor those 50 registries/vendors for breaches?

Being a certificate authority is not to be taken lightly.

---

OTOH, sure, it’s a job that _someone_ has to do for every deployment, and letting all individual system administrators deal with this individually is not much better for the administrators.

Still, I’d argue that letting downstream distributors ship their own public keys, and letting the individual system administrators deal with public keys from projects/vendors they use, aligns the incentives a tiny bit better.

Maybe we can find a downstream with economic interest in maintaining the public key set for itself (and maybe some expected benefit from being in control of the “trusted” ecosystem) willing to take on the responsibility for maintaining the data, and allowing the upstream project to distribute the results — that could alleviate some of the concerns but not all (the upstream would still have to backport+notify), and bring some new ones (conflicts of interest / trying to benefit from the control downstream gets).

---

It might well make sense for a _very limited set_ to be shipped upstream, based on a history of contributions from the respective projects, so that we can rely on self-interest from these projects to maintain their own public keys. Still we would have to somehow deal with projects decreasing their contributions over time and “orphaning” the maintenance of the public keys (and if Podman ever becomes a stable mature software with few changes, “a history of contributions” would not qualify anyone any more).

**Comment by rhatdan** [comment]
With @mtrmac response, I do not believe this is something upstream wants to a handle.  Distributions might want to do this themselves in their packaging.
