### ISSUE TITLE
Podman fails to refresh devices passed in the container

### ISSUE THREAD

**Issue by ctron** [containers/podman#8731]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

**Steps to reproduce the issue:**

1. Attach device

2. Run podman with `--device <dir>`

3. Detach device

**Describe the results you received:**

The container will continue to show the devices that existed during startup. It does not add new or remove old devices.

**Describe the results you expected:**

The container should see the changes happening on the host.

**Additional information you deem important (e.g. issue happens only occasionally):**

The following shows a container which had the device attached during startup. But now the device is removed. Still it is visible in the filesystem of the container. Exiting and re-starting the container does a refresh.

~~~
root@bf6d57f194de:/# find /dev/snd
/dev/snd
/dev/snd/timer
/dev/snd/seq
/dev/snd/pcmC1D0p
/dev/snd/pcmC1D0c
/dev/snd/pcmC0D1p
/dev/snd/pcmC0D0p
/dev/snd/controlC1
/dev/snd/controlC0
root@bf6d57f194de:/# exit
[root@localhost ~]# podman run --rm -ti --device /dev/snd --entrypoint bash  ghcr.io/drogue-iot/hey-rodney-pocketsphinx:latest
root@ff86315988d4:/# find /dev/snd
/dev/snd
/dev/snd/timer
/dev/snd/seq
/dev/snd/pcmC0D1p
/dev/snd/pcmC0D0p
/dev/snd/controlC0

~~~

**Output of `podman version`:**

```
Version:      2.1.1
API Version:  2.0.0
Go Version:   go1.15.2
Built:        Sun Oct  4 23:25:48 2020
OS/Arch:      linux/arm64
```

**Output of `podman info --debug`:**

```
host:
  arch: arm64
  buildahVersion: 1.16.1
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.0.21-3.fc33.aarch64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.21, commit: 66d50d2f6c81e28bacd99ee8e8d222f028eef63f'
  cpus: 4
  distribution:
    distribution: fedora
    version: "33"
  eventLogger: journald
  hostname: localhost.localdomain
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.8.15-301.fc33.aarch64
  linkmode: dynamic
  memFree: 104620032
  memTotal: 980905984
  ociRuntime:
    name: crun
    package: crun-0.15-5.fc33.aarch64
    path: /usr/bin/crun
    version: |-
      crun version 0.15
      commit: 56ca95e61639510c7dbd39ff512f80f626404969
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  rootless: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 0
  swapTotal: 0
  uptime: 7h 14m 12.76s (Approximately 0.29 days)
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - docker.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageStore:
    number: 5
  runRoot: /var/run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 2.0.0
  Built: 1601853948
  BuiltTime: Sun Oct  4 23:25:48 2020
  GitCommit: ""
  GoVersion: go1.15.2
  OsArch: linux/arm64

```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

Fedora IoT: there is no `rpm` or `apt`.

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

No

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Same behavior on Fedora IoT as well as Fedora 33.

**Comment by rhatdan** [comment]
Podman is not watching the device directory to see changes, it really can not, since it goes away in the --detached mode.
Theoretically we could get conmon to watch the directory, and add/remove devices, but this would only work in rootfull mode.
if you mount the /dev/dir into the container then it should work, although SELinux might become MAD, and block some access.

**Comment by mheon** [comment]
I don't think this is expected behavior. If you explicitly tell Podman to mount, say, `/dev/sdb` into a container, and `/dev/sdb` suddenly becomes inaccessible, Podman can no longer do what you asked (mount the given device in) and should error.

If you want to monitor `/dev` for changes, mounting `/dev/` into the container seems appropriate.

**Comment by ctron** [comment]
My use case here is device hot-plugging, adding audio devices (or loosing them) during runtime of a container.

> If you want to monitor /dev for changes, mounting /dev/ into the container seems appropriate.

From what I read in the comment above, that would cause problems with SElinux?! And thus is not a viable solution.

IIRC there is a `:z` flag for `--volume`, would that do the trick?

**Comment by rhatdan** [comment]
No, but the SELinux Udica team is working on a solution. @wrabcak PTAL

**Comment by ctron** [comment]
@rhatdan Did I get that right: the solution would be that in a future version `--volume` plus `:z` would be sufficient to achieve this? That would be fine.

**Comment by wrabcak** [comment]
Hello @ctron, for your usecase this is not the right approach. Because also another processes and services can access devices you cannot change the SELinux label of the device (using :z will do that for you). For this purpose, you need to use custom SELinux policy for your container so the container can access` /dev ` and device you want to mount into container. Recently, I added new feature to the udica so you can generate the policy for your containers. Please look on the project [container/udica](https://github.com/containers/udica) . 

Your ideal steps should be: 
```
# dnf install udica -y
# podman inspect <name_of_the_container> | udica my_device_container_name
```

And follow the output from udica tool. 

If you have any question, please let me know.

**Comment by ctron** [comment]
Thanks @wrabcak for the help. I will try that out, but probably not this year anymore :grinning:

**Comment by rhatdan** [comment]
Not sure there is much podman can do with this, so closing.
