### ISSUE TITLE
podman search: --list-tags clobbers --format

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#8740]
`podman search --list-tags` will output a table, even if `--format` is requested (either `json` or `{{.Tag}}`):
```console
$  ./bin/podman search --list-tags --format json quay.io/podman/stable
NAME                   TAG
quay.io/podman/stable  v1.4.4
quay.io/podman/stable  v1.4.2
...
```
If possible, the requested `--format` should be honored. If not possible, there should be a run-time check throwing a conflicting-options error.

Related: #8276

**Comment by yufeifly** [comment]
hi, I am using podman 2.1.1.

**Comment by yufeifly** [comment]
Hi, I am using podman 2.1.1. When I run command `podman search --list-tags --format json quay.io/podman/stable`, I get this output `Error: unknown flag: --list-tags`. Is this due to the podman version?

**Comment by rhatdan** [comment]
Looks like this did not show up until podman-2.2, which should be available now.

**Comment by Afourcat** [comment]
Hello,
I was trying to fix this issue, but what kind of output are you waiting for?

This output following the same structure of the default option of the `podman search` command:
```JSON
{
    "Index": "",
    "Name": "docker.io/library/redis",
    "Description": "",
    "Stars": 0,
    "Official": "",
    "Automated": "",
    "Tag": "2.8.7"
}
```

Or this output following the structure of the `podman search --list-tags` command:
```JSON
{
    "Name": "docker.io/library/redis",
    "Tag": "2.8.7"
}
```

Thank you for your time and your work.

**Comment by Afourcat** [comment]
If it does not violate any conventions, Your suggestion seems better.

For me, the implementation looks feasible. It looks like it could be fixed in [this file](https://github.com/containers/podman/blob/master/cmd/podman/images/search.go#L153).

I will implement your output format, and when the community validates that it follows all necessary conventions, I will make a pull request. If it sounds right to you.
