### ISSUE TITLE
Add support for disabling the use of newuidmap and newgidmap

### ISSUE THREAD

**Issue by eriksjolund** [containers/podman#8929]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

Add command-line option(s) to `podman run` so that it is possible to disable the use of `/usr/bin/newuidmap` and `/usr/bin/newgidmap` (either individually or both at the same time).

In case the user want to disable, there is no need to output the warning _"using rootless single mapping into the namespace. This might break some images. Check /etc/subuid and /etc/subgid for adding sub*ids"_.

https://github.com/containers/podman/blob/41613bdb96953c9cea8a8fd46da211bd42660944/pkg/rootless/rootless_linux.go#L260

I mentioned this feature request idea on the Podman mailing list
https://lists.podman.io/archives/list/podman@lists.podman.io/thread/S6VG4F6WXVOOB7ROHOCUSKW54BG2P7ZT/

**Comment by giuseppe** [comment]
how would that be different than using `--uidmap 0:0:1`?

If the goal is to create the rootless user namespace only with a single mapping, I think we would need to have the option as part of `podman unshare`

**Comment by NickJLange** [comment]
**Disclaimer**: I'm not sure I understand the entire risk-profile of flattening things for __rootless__ containers. To the extent that:

- Container #1's ids can be flattened to a single id
- That ID has the same rights as invoking id
- It's explicit to prevent things like jailbreaking

I think this is a great feature for people looking at running simple containers in more traditional distributed contexts.

**Comment by giuseppe** [comment]
security-wise I think there is not much difference than running containers with `--uidmap 0:0:1`.

If additional IDs are allocated for the user, why not to take advantage of them for storing the images?

In general, I think it is safer to not flatten the image to single id when possible.  We are looking at supporting running containers without requiring root to be mapped, e.g. `--uidmap 10:0:1 --user 10`.  If you flatten the image, that won't be possible anymore as everything is owned by root.

If you really think it is different, a way for implementing it could be adding a way to override the `subuidmap` and `subgidmap` path using an env variable and you can set it to /bin/false, `NEWUIDMAP=/bin/false podman ...`.  It is more difficult to get it done through a command line setting (unless we limit it to `podman unshare` and require it to create the initial namespace) as there is code for joining the rootless user namespace that runs before the Go runtime starts.

**Comment by rhatdan** [comment]
I wrote an article about the security of running rootless containers as non root and it's benefits from a security point of view.

https://www.redhat.com/sysadmin/rootless-podman-makes-sense

Bottom line is, I believe it is more secure to run a rootless container with a user namespace to run it flattened the way you are suggesting  Since you can isolate the UIDs of process inside of the container from haveing UID permissions on valuable files in your homedir like ~/ssh/

**Comment by eriksjolund** [comment]
Thanks, I see, there is an easy workaround. `NEWUIDMAP=/bin/false podman ...`.

I thought before that you needed to fiddle around with the `PATH` environment variable to do something similar.
My workaround idea was (untested)

```
dir=`mktemp -d`
chmod 700 $dir
ln -s /bin/false $dir/newuidmap
PATH=$dir:$PATH podman ...
```

The scenario I was thinking about when creating this feature request, is when a newbie linux user
would like to be sure that no files could be created in the home directory that are not owned by the normal 
UID of the linux user. In the scenario the newbie linux user does not have sudo permissions to be able to modify /etc/subuid.

I'm not sure that this feature request is really needed, especially if the difference between

```
podman --uidmap 0:0:1 ...
```

and

```
NEWUIDMAP=/bin/false podman --uidmap 0:0:1 ...
```

is very small.

If  I understand you correctly, the difference between

```
podman --uidmap 10:0:1 --user 10
```

and

```
NEWUIDMAP=/bin/false podman--uidmap 10:0:1 --user 10 ...
```

should also be very small.

(I'm still learning how this all works)

I don't mind if you just close this feature request.

**Comment by NickJLange** [comment]
Thanks to Erik for the original sponsorship. I think there is a use-case for making this more straightforward for anyone focused more on the packaging side of containers than the isolation aspect. 

i.e. I could see --net host, --ipc host etc being explicit bedfellows for this use-case. 

Perhaps some big bold letters around using with trusted sources..

**Comment by giuseppe** [comment]
since we have a way to have just one mapping in the user namespace with `--uidmap 0:0:1` and that there is no need in skipping newuidmap, I am going to close the issue.

Please reopen if you disagree

**Comment by geofft** [comment]
FWIW I ran into a mild edge case with `--uidmap 0:0:1` which I'm noting here in case anyone else runs across it.

If the files /etc/subuid and /etc/subgid have a mapping for the current user, podman will always try to call `newuidmap`/`newgidmap` and use those mappings. If you repoint those at `/bin/true` (`/bin/false` just errors out, and I couldn't get the environment variables to work and had to rely on symlinks in my PATH), then you won't get any mappings, and a subsequent call to `setresgid(0, 0, 0)` will fail because you're not GID 0.

If there are no mappings for the current user in /etc/subuid and /etc/subgid, then podman will fall back on the unprivileged ability to add a single mapping of the current account, and things will work fine. (You'll then probably need the `fuse-overlayfs` driver with the `ignore_chown_errors` option, as [mildly documented](https://docs.podman.io/en/latest/markdown/podman.1.html#rootless-mode).)

Most of the time this heuristic works fine: if the files in /etc exist, they're probably usable. But I got myself pretty badly confused because I was testing on an account/system that had subuids configured in preparation for running on an account/system that didn't. I tried running podman under `setpriv --no-new-privs` to prevent the setuid `newuidmap`/`newgidmap` binaries from gaining privileges, but since doesn't affect the config files in /etc, podman's heuristic still expects `newuidmap`/`newgidmap` to work. There are also a few other cases where the setuid powers won't work, e.g., `strace -f` or running nested inside an unprivileged user namespace.

If you can't remove your /etc/uidmap and /etc/gidmap mappings, an entirely unprivileged workaround is to put the following script on your PATH as `newuidmap`:
```sh
#!/bin/sh
echo 0 "$(id -u)" 1 > /proc/"$1"/uid_map
```
and as `newgidmap`:
```sh
#!/bin/sh
echo deny > /proc/"$1"/setgroups
echo 0 "$(id -g)" 1 > /proc/"$1"/gid_map
```
i.e., unconditionally do the unprivileged self-map and ignore the arguments passed other than the PID.

I think it would be useful if podman had an explicit option not to call `newuidmap`/`newgidmap`, but I admit that my use case is a little unusual. (It would also be useful if this option automatically set the right storage driver options, too.)

Also, somewhat surprisingly, the correct syntax is indeed `--uidmap 0:0:1` as stated above, even if the host user is not UID 0. Using `--uidmap 0:$UID:1` doesn't work. Also it seems to imply `--gidmap 0:0:1`; you don't need to pass that explicitly.

**Comment by rhatdan** [comment]
Would be great if you put this into a Blog.

**Comment by hashkool** [comment]
> Would be great if you put this into a Blog.

Wouldn't the wiki be a better place? @geofft

**Comment by geofft** [comment]
I'll try to write up a blog post one I figure out how to get a storage driver to work for my use case... (non-root Kubernetes user in an "unprivileged" pod, which doesn't have access to /dev/fuse - otherwise fuse-overlayfs would work fine)

Happy to add this to the wiki if there's a good place, but I do want to repeat - I do think podman should have an explicit option as originally requested in this issue. It would make the writeup easier if the answer is "use `podman run --userns=none`" (or whatever) instead of "use `podman run --uidmap 0:0:1` but also make sure your /etc is configured in this way". And it provides a place to configure storage drivers too, if it turns out they need configuration for this. Then it can just be in the man page :)

**Comment by rhatdan** [comment]
@giuseppe WDYT of --userns=none?

**Comment by giuseppe** [comment]
setting up the rootless user namespace happens before we run the podman command, the `--userns` flag is related to the container payload, not the podman rootless user namespace.

The issue with using different settings for the user namespace is that they have an effect on the storage, all the mappings are relative to the mappings we picked the first time, so it cannot be something we can change at runtime.

We introduced this error because users on a system lacking newuidmap/newgidmap were not aware that it would create a single mapping.

If we decide to do anything about it, it should be a static setting in `containers.conf`.

**Comment by exaexa** [comment]
Hi all,
I'm adding myself to the loop here, we're very interested in having such a feature and I can spend some time implementing it. By any chance, is there possibly a known roadmap or the current best way to do this?
Thanks!

**Comment by giuseppe** [comment]
it would be helpful to first understand your use case.  Are newuidmap/newgidmap missing or you simply do not want to use them?

**Comment by exaexa** [comment]
We simply want to be able to conveniently run stuff in environments that don't/can't have user namespaces at all. Breakage of whatever that depends on the proper PIDs/GIDs in the container is a reasonable assumption and we can live with it.

**Comment by giuseppe** [comment]
newuidmap/newgidmap won't change the requirement of user namespaces.  The only difference is that only one UID/GID can be mapped it.

Shortly: there is no way to run rootless podman without user namespaces.

**Comment by exaexa** [comment]
ah ok, then I misread this completely. Apologies for the noise.

**Comment by rhatdan** [comment]
Well you can configure a user namespace with one UID/GID, and then when the image is pulled to your desktop, you would need to be squashed to that UID/GID combo. When run it would run as UID=0 inside of the container and everything inside of the container would be running as root inside the user namespace.  This is a mode that HPC community uses now, they have an app that runs with a single UID and owns all of the files within the container.

**Comment by geofft** [comment]
Yeah - the interesting thing is that _most_ Linux environments allow users to create user namespaces as an unprivileged action without any particular userspace support or configuration (that is, it's a feature of the kernel API so it's functional when running nested inside other containers etc. and it requires no root-level setup/cooperation). You can map any one UID/GID inside the container to your own; it's mapping additional ones that requires setup. If you haven't tested, see if your environment lets you do `unshare -U` (or idk see if Python `import ctypes; ctypes.CDLL("").unshare(0x10000000)` returns 0). If so, you can use podman in the mode where it's mapping a single UID and GID.

On the other hand, there are environments where even that is disabled (by kernel build-time config, sysctl, LSM, seccomp, etc.) and this won't help you. The common argument for this is attack surface reduction, since it does let you reach some kernel codepaths like mounting filesystems that you otherwise couldn't do as non-root.

One important case that people are probably going to run into is that [Ubuntu 23.10 onwards now disables unprivileged user namespaces for process that are not confined by some sort of AppArmor profile](https://discourse.ubuntu.com/t/mantic-minotaur-release-notes/35534) - any profile at all is sufficient for now, but they're planning on moving towards further restrictions in the future. I'm not sure if Ubuntu's packaged Podman gets an AppArmor profile; if it doesn't, it's probably worth someone filing a bug with Ubuntu (or Debian) so that unprivileged Podman works right. (But even if it did, that AppArmor profile is not guaranteed to apply to containers running on an Ubuntu host or other similar contexts.) I don't think there's any good workaround here since without unprivileged user namespaces you can't actually `mount`/`chroot`/etc. yourself into the container. You might be able to throw something like [proot](https://proot-me.github.io/) at the problem.

**Comment by exaexa** [comment]
@geofft thanks for the `proot` link, that seems extremely helpful!

**Comment by snowhanse** [comment]
I keep coming back to this too, where podman prints a big red error about the missing subuid entry, but it's really misleading because it's not an error for us. In our case we do not need/want to add users to /etc/subuid, but it really confuses them when this error pops up every time. Particularly there is any other issues as it send folks on a wild goose chase thinking the mapping is the issue.

**Comment by snowhanse** [comment]
> How do you have it configured? Are you just pulling images with only one UID or are you telling the system to squash the UID/GIDs?

The former.
Until now we have created a squashed / single layer base image that was built with a "chown -R root:root *`. 

In the last couple of days realised the `ignore_chown_errors = "true"` option, so will probably change to that, so it's easier to bump base image

**Comment by rhatdan** [comment]
Please open a new issue, to disable the warning when storage.conf is set to ignore_chown,
