### ISSUE TITLE
auto update without registry on local images

### ISSUE THREAD

**Issue by vrothberg** [containers/podman#9088]
/kind feature

**Description**

After a private chat with a user on auto updates, it became clear that auto updates could also be applied without having a container registry. For instance, when images built locally, the use case remains the same. Currently, auto updates only work when the image on the remote registry has changed.

There a couple of things to think about:
* Currently, containers configured for auto updates must use fully-qualified image references. Short names are not supported. Should this change? It seems _very_ common to just use short names locally.
* Should we introduce a new auto-update policy?  Currently it's called "image" (and maybe should be aliased to "registry"). The local one could be called "local". Then we could easily support short names.

@fatherlinux @mrguitar ... do you have feedback suggestions?

**Comment by mrguitar** [comment]
The majority of the "production" use cases seem to prefer separating builds from runtime environments. That said, I like this idea and it seems really useful for certain types of use cases. This would be valuable for my home systems and I can see other development-ish use cases where this would be helpful.

Agreed that short names are common for local use. I don't have a strong opinion on good options here, but would requiring "localhost/[name]" be an acceptable compromise? requiring a local policy feels cumbersome, but it's possible that's a better option.

**Comment by fatherlinux** [comment]
+1 Ben. Also, since we have the secure short names feature now (or will), I think this could probably be done in a way has defense in depth and prevents an attack from a man in the middle.

I could also see this being used in an environment with really slow internet connection. It might be cheaper to deliver a Dockerfile/Containerfile out and have the image build from some local cache of packages. It's probably an edge case, but could be really convenient if you happen to be a user with *that* edge case.

**Comment by rhatdan** [comment]
@vrothberg Is this is issue you wanted @ParkerVR to look at?

**Comment by ParkerVR** [comment]
@rhatdan touched based with @vrothberg on this and will discuss more in depth tmmr

**Comment by vrothberg** [comment]
Implemented in #10063.
