### ISSUE TITLE
system reset doesn't work after user has been recreated

### ISSUE THREAD

**Issue by quantum77** [containers/podman#9413]
/kind bug

**Description**
When creating a new user and deleting an old user podman no longer works.
$ podman images 
Error: error creating tmpdir: mkdir /run/user/1000: permission denied

$ podman system reset
Error: error creating tmpdir: mkdir /run/user/1000: permission denied

What does resolve the error:
$ rm -rf ~/.local/share/containers

**Comment by mheon** [comment]
Core of the issue seems to be that `system reset` requires Podman to successfully create the libpod Runtime before `system reset` will run. If you encounter an issue where the runtime cannot be created, e.g. a path issue like this, `podman system reset` cannot run, so the user can't reset their storage and fix the bug.

**Comment by rhatdan** [comment]
This looks like XDG_RUNTIME_DIR was not set correctly.  How do you get into this condition?

**Comment by mheon** [comment]
@rhatdan The paths cached in the database no longer match system configuration. `XDG_RUNTIME_DIR` does not come into this.

The solution will require a significant rewrite to `system reset`, which will have to be rewritten to be part of runtime init so we can avoid errors of this type.

**Comment by vrothberg** [comment]
> How do you get into this condition?

I wonder as well.

**Comment by vrothberg** [comment]
Closing in favor of https://github.com/containers/podman/issues/11377 which has some reproducer
