### ISSUE TITLE
Docker Compose CLI is not supported (missing top level context CLI command)

### ISSUE THREAD

**Issue by troyready** [containers/podman#9806]
/kind feature

**Description**

The [Docker Compose CLI](https://github.com/docker/compose-cli) (NOTE: this is related to but *not* docker-compose) sits in front of the traditional docker command and extends docker-compose capability to "cloud" deployments. Essentially, `docker-compose up` to test locally, `docker compose up` to deploy to (e.g.) AWS ECS.

It relies on a [context command](https://docs.docker.com/engine/reference/commandline/context/) (added in docker v19 from what I can see). Additional info on it is [available here](https://docs.docker.com/engine/context/working-with-contexts/).

The overall workflow is [fairly well walked through here.](https://aws.amazon.com/blogs/containers/deploy-applications-on-amazon-ecs-using-docker-compose/)

**Steps to reproduce the issue:**

1. Unpack [docker compose-cli](https://github.com/docker/compose-cli) into PATH

2. Symlink `com.docker.cli` to `podman`

3. Execute `docker --context default ps`

**Describe the results you received:**

`Error: unknown flag: --context`

**Describe the results you expected:**

List of containers

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:      3.0.1
API Version:  3.0.0
Go Version:   go1.15.8
Built:        Wed Dec 31 16:00:00 1969
OS/Arch:      linux/amd64
```

**Comment by vrothberg** [comment]
Thanks for reaching and apologies for the longer silence; we've been really busy.  The `--context` option along with the `context` commands relate to Docker Swarm which is something Podman does not support.

In your specific case `--context=default` is something that Podman could support (i.e., default context).  I also think that Podman could do a better job at error reporting and report that `docker context` isn't supported because of Swarm.

@containers/podman-maintainers PTAL
